### ISSUE TITLE
Smoke test package list

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/BinaryBuilder.jl#1]
Try building the following on the big three platforms:

- [ ] [FFTW.jl](https://github.com/JuliaMath/FFTW.jl): [`build.jl`](https://github.com/JuliaMath/FFTW.jl/blob/master/deps/build.jl), [C code](https://github.com/FFTW/fftw3)
- [ ] [Rmath.jl](https://github.com/JuliaLang/Rmath-julia): [`build.jl`](https://github.com/JuliaStats/Rmath.jl/blob/master/deps/build.jl), [C code](https://github.com/JuliaLang/Rmath-julia)
- [ ] [Openspecfun (`SpecialFunctions.jl`)](https://github.com/JuliaMath/SpecialFunctions.jl): [C/FORTRAN code](https://github.com/JuliaLang/openspecfun)
- [ ] [CUTEst.jl](https://github.com/JuliaSmoothOptimizers/CUTEst.jl): [`build.jl`](https://github.com/JuliaSmoothOptimizers/CUTEst.jl/blob/master/deps/build.jl), [C code](https://ftp.gnu.org/gnu/gsl/gsl-1.16.tar.gz)
- [ ] [AmplNLReader](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl): [`build.jl`](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/blob/master/deps/build.jl), [C code](https://github.com/ampl/mp/archive/3.1.0.tar.gz)

**Comment by ararslan** [comment]
It would also be great to try out openspecfun (currently in Base but will be moved to SpecialFunctions.jl) as it contains Fortran as well, which is particularly problematic across platforms.
