### ISSUE TITLE
`--deploy=local` should tell the user what it did

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#1039]
```
~/julia-1.6.0/bin/julia build_tarballs.jl --deploy=local x86_64-linux-gnu
[ Info: Building for x86_64-linux-gnu
[ Info: Directory "./ngspice" found
```

I think an extra info statement that would tell the user that it deployed to `~/.julia/dev` would be a nice addition, particularly for users who don't really know how BinaryBuilder works.

**Comment by Wimmerer** [comment]
This already occurs in when `--verbose` is used, although it only prints `local` rather than the directory. Do you want this active without verbose?﻿

**Comment by Keno** [comment]
Yes, just a single line to tell the end user what the result of the operation was. I do think the "Directory ... Found" message need not be active in non-verbose mode.

**Comment by Wimmerer** [comment]
There's a PR. The build/deploy message does occur before actual build/deploy happens. That is the original behavior so I kept it that way.

**Comment by Wimmerer** [comment]
The "Directory ... Found" info comes from BinaryBuilderBase
