### ISSUE TITLE
Update dependencies from within wizard

### ISSUE THREAD

**Issue by bramtayl** [JuliaPackaging/BinaryBuilder.jl#1043]
Very often, I'll go into a build blindly, run configure, and then realize I need a bunch of dependencies. Then I need to restart the wizard from scratch, reenter all the info, and then add the dependencies. It might be nice if there was a "try again with more dependencies" option in the wizard?

**Comment by giordano** [comment]
Something like a command
```console
# bb add PackageName_jll
```
to interactively install a new dependency?

**Comment by bramtayl** [comment]
Oh that would be perfect!

**Comment by giordano** [comment]
Good, it's already there :slightly_smiling_face:

**Comment by bramtayl** [comment]
Yay! Sorry for the bother
