### ISSUE TITLE
Module file `ieee_arithmetic.mod` missing on aarch64+musl and armv7l+musl

### ISSUE THREAD

**Issue by sloede** [JuliaPackaging/BinaryBuilder.jl#1050]
Is it possible that the `ieee_arithmetic.mod` file was (accidentally) left out of the `gfortran` builds for *Linux aarch64 {libc=**musl**}* and *Linux armv7l {call_abi=eabihf, libc=**musl**}*? I am trying to build a binary that depends on that module, and all other platforms work (specifically, ARM with glibc or any other platform with musl). On these two platforms, I get an error like this:
```
gfortran -c -cpp -O  -o FTValueClass.o /workspace/srcdir/ftobjectlibrary/Source/FTObjects/FTValueClass.f90
/workspace/srcdir/ftobjectlibrary/Source/FTObjects/FTValueClass.f90:71:11:

   71 |       USE IEEE_ARITHMETIC
      |           1
Fatal Error: Cannot open module file ‘ieee_arithmetic.mod’ for reading at (1): No such file or directory
compilation terminated.
make: *** [Makefile:260: FTValueClass.o] Error 1
```

Please excuse if this is the wrong repo to open this issue at - if it is, I'd appreciate it if you can point me to the correct venue.

**Comment by giordano** [comment]
Looking to the gfortran package in Alpine Linux, it looks like the ieee* modules are missing for all non-Intel platforms:

* [x86_64](https://pkgs.alpinelinux.org/contents?file=&path=&name=gfortran&branch=v3.13&repo=main&arch=x86_64)
* [x86](https://pkgs.alpinelinux.org/contents?file=&path=&name=gfortran&branch=v3.13&repo=main&arch=x86)
* [aarch64](https://pkgs.alpinelinux.org/contents?file=&path=&name=gfortran&branch=v3.13&repo=main&arch=aarch64)
* [armhf](https://pkgs.alpinelinux.org/contents?file=&path=&name=gfortran&branch=v3.13&repo=main&arch=armhf)
* [ppc64le](https://pkgs.alpinelinux.org/contents?file=&path=&name=gfortran&branch=v3.13&repo=main&arch=ppc64le)
* [s390x](https://pkgs.alpinelinux.org/contents?file=&path=&name=gfortran&branch=v3.13&repo=main&arch=s390x)
* [armv7](https://pkgs.alpinelinux.org/contents?file=&path=&name=gfortran&branch=v3.13&repo=main&arch=armv7)
* [mips64](https://pkgs.alpinelinux.org/contents?file=&path=&name=gfortran&branch=v3.13&repo=main&arch=mips64)

I don't know _why_ these modules aren't built for non-Intel platforms with musl C library, but like #1053 this looks to me an upstream issue we can do very little about.

**Comment by sloede** [comment]
I was just about to open an issue at Alpine Linux, when I stumbled across the [GCC docs](https://gcc.gnu.org/onlinedocs/gfortran/IEEE-modules.html):
> **10.3 IEEE modules: IEEE_EXCEPTIONS, IEEE_ARITHMETIC, and IEEE_FEATURES**
> 
> [...] These modules are only provided on the following supported platforms:
>
>   * i386 and x86_64 processors
>   * platforms which use the GNU C Library (glibc)
>   * platforms with support for SysV/386 routines for floating point interface (including Solaris and BSDs)
>   * platforms with the AIX OS 

Thus, if I read it correctly (as an "inclusive or" list), this confirms what you wrote above, i.e., these modules are built on Intel platforms *or* where glibc is used, but not on non-Intel platforms with musl...

To summarize, I guess it's fair to assume that this won't fix (since it's not just an issue of a missing parameter file etc.) and can be closed.
