### ISSUE TITLE
Check for git config settings 

### ISSUE THREAD

**Issue by tshort** [JuliaPackaging/BinaryBuilder.jl#106]
I hit this when running from a new virtual machine, so not much was set. There was an error that 'user.name' was not found.

`git config --global user.name ...` and `... user.email ...` fixed it.

Suggestion is to check for this and prompt if not set globally.

**Comment by staticfloat** [comment]
This will be fixed by https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/178
