### ISSUE TITLE
Meson version >0.52.0

### ISSUE THREAD

**Issue by fcdimitr** [JuliaPackaging/BinaryBuilder.jl#1065]
Is there a way to use a newer version of Meson (>0.52.0) within the sandbox?

I am trying to build the following C/C++ package
https://github.com/fcdimitr/sgtsnepi

which requires at least meson >=0.53.0

**Comment by giordano** [comment]
https://github.com/JuliaPackaging/Yggdrasil/blob/60e20b7278c99c06e23e0c2107c67e31dd36bea7/G/GTK3/build_tarballs.jl#L51
```sh
apk add meson --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
```

**Comment by fcdimitr** [comment]
Thanks for the quick reply!
