### ISSUE TITLE
powershell based build

### ISSUE THREAD

**Issue by hros** [JuliaPackaging/BinaryBuilder.jl#1067]
I am trying to create a jll package from a library which has a cross platform compilation script based on powershell and dotnet (you guessed it... developed by Microsoft)

is there a working project or a template that installs powershell and dotnet as part of the BinaryBuilder project build scripts?

**Comment by staticfloat** [comment]
You know, there isn't, but conceptually this is possible.  I think it's going to require a number of hoops to jump through, but there's no fundamental reason this can't work.  I would put money on it being not worth the effort (and better to instead mimic the build system in bash/make) but you're free to try and get it working.  :P

**Comment by hros** [comment]
thanks
the library has an optional cmake based build, so I can postpone the powershell struggle for now
