### ISSUE TITLE
c++ 17 support

### ISSUE THREAD

**Issue by hros** [JuliaPackaging/BinaryBuilder.jl#1071]
When building a library for Linux I get the following error:
```
CMake Error in src/core/CMakeLists.txt:
  The compiler feature "cxx_std_17" is not known to CXX compiler

  "GNU"

  version 4.8.5.

CMake Generate step failed.  Build files cannot be regenerated correctly.
```
is it possible to change to a different version of g++, with support for c++-17?

**Comment by giordano** [comment]
```julia
build_tarballs(...; preferred_gcc_version=v"5")
```
or the first version that implements the features you need: https://gcc.gnu.org/projects/cxx-status.html#cxx17

**Comment by hros** [comment]
Since I am using `run_wizard`, please  explain how `build_tarballs` should be used in place of / in conjunction with `run_wizard`

**Comment by giordano** [comment]
In the wizard you're asked whether you want to customise the set of compilers

**Comment by hros** [comment]
thanks!
the c++-17 error disappeared, but I have another build error:
```
[  1%] Building C object src/core/CMakeFiles/core.dir/ack_tracker.c.o
cd /workspace/srcdir/msquic/build/src/core && /opt/bin/x86_64-linux-gnu-libgfortran5-cxx11/cc -DCX_PLATFORM_LINUX -DQUIC_DISABLE_CLIENT_CERT_TESTS -DQUIC_DISABLE_DEFERRED_CERT_TESTS -DQUIC_EVENTS_STUB -DQUIC_LOGS_STUB -DVER_BUILD_ID=0 -DVER_SUFFIX=-private -D_GNU_SOURCE -I/workspace/srcdir/msquic/src/inc  -Ofast  -DNDEBUG   -fms-extensions -fPIC -pthread -Werror -Wall -Wextra -Wformat=2 -Wno-type-limits -Wno-unknown-pragmas -Wno-multichar -Wno-missing-field-initializers -o CMakeFiles/core.dir/ack_tracker.c.o   -c /workspace/srcdir/msquic/src/core/ack_tracker.c
You used one or more of the unsafe flags: -Ofast, -ffast-math, -funsafe-math-optimizations
Please repent.
```
I've tried changing the g++ compiler all the way from version 7 to version 10

note, that my laptop can natively build the library without error, I'm running Ubuntu 20.04 with g++ version 9.3.0


Is there any thing special regarding `-Ofast` in BinaryBuilder build environment?

**Comment by giordano** [comment]
Changing compiler version won't help since we never allow to use those flags, because they're...well...unsafe. You have to patch the build system to not use them.
