### ISSUE TITLE
Add macOS-aarch64 to supported platform on the docs

### ISSUE THREAD

**Issue by gbaraldi** [JuliaPackaging/BinaryBuilder.jl#1097]
The title basically.

**Comment by giordano** [comment]
For context, the list of supported platforms show in [the documentation](https://docs.binarybuilder.org/v0.4.1/building/#Platforms) is automatically generated from `supported_platforms()` (it's literally the command shown in the REPL example), so technically there is no issue.  You're referring to the fact that `aarch64-apple-darwin` at the moment is an experimental platform, which is a different issue.
