### ISSUE TITLE
Check package name earlier

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/BinaryBuilder.jl#1108]
I just tried to build a package called `MPIwrapper-MPICH`. After 10 minutes of building (successfully!), I received the error that the package name is not an identifier. (I needed to switch the hyphen for an underscore.)

It would be convenient if that error was reported in the beginning, not at the end of the build process.

**Comment by giordano** [comment]
With the wizard or simply by running the `build_tarballs.jl` script?  I believe the wizard would check the name as soon as you type it, I don't remember when this is checked in `autobuild`.

**Comment by eschnett** [comment]
I was using `build_tarballs.jl`.

**Comment by Keno** [comment]
Fixed by #1117, but the commit message there had an extra `#`, so this wasn't closed.
