### ISSUE TITLE
Set `lock_microarchitecture=false` as default for rust builds using the wizard

### ISSUE THREAD

**Issue by jeremiahpslewis** [JuliaPackaging/BinaryBuilder.jl#1131]
This seems to be the new standard / be required to ensure that builds go through successfully, it might make sense to set this as a default option.

**Comment by giordano** [comment]
I'd rather like the compiler to not set `-march`, to be honest.

**Comment by giordano** [comment]
> This seems to be the new standard / be required to ensure that builds go through successfully

Judging by https://github.com/JuliaPackaging/Yggdrasil/pull/4092/files, this seems to not be even true?

**Comment by jeremiahpslewis** [comment]
Agree.
