### ISSUE TITLE
Fictional UUID created for non JLL package

### ISSUE THREAD

**Issue by vchuravy** [JuliaPackaging/BinaryBuilder.jl#1132]
In a local version of https://github.com/JuliaPackaging/Yggdrasil/pull/4073 I am experimenting with adding a non `jll` dependency.
Thanks to @giordano who pointed me to the right place. We should look up the UUID instead of synthesizing a new one.

https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/084d75b38aa9d0a0240d328d9ff3adbc9c7d9068/src/AutoBuild.jl#L1442

cc: @staticfloat

**Comment by staticfloat** [comment]
Heh, yeah.  This is making use of the fact that JLLs all have deterministic UUIDs; so if you've got two different BBs generating JLLs that don't exist in the registry yet, they generate consistent UUIDs, etc...

But you're right, we should do a lookup in the registry first, and only do the hashing thing if it doesn't already have a match.
