### ISSUE TITLE
How can I run `julia` in a BinaryBuilder script?

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/BinaryBuilder.jl#1134]
It seems I can run C, C++, Fortran, Go, and Rust compilers in the build script, but – ironically – I don't know how to run Julia!

**Comment by giordano** [comment]
Contrary to GCC, LLVM, Rust and Go compilers, Julia is not a cross-compiler :wink: Not at the moment at least.

If we had an up-to-date [`Julia_jll.jl`](https://github.com/JuliaBinaryWrappers/Julia_jll.jl), also for `x86_64-linux-musl`, you could use it as a `HostBuildDependency`, in case you want to run a Julia script during the build.

**Comment by eschnett** [comment]
I want to run some Julia code that generates C++ code, and I then want to use that C++ code in the build script.

Would it be acceptable to run that Julia script from within `build_tarballs.jl`? I would use `run(Base.julia_cmd)` to run the Julia script. I don't need anything that's architecture dependent.

**Comment by eschnett** [comment]
... but I also need access to the downloaded source, which is not yet available at that time. Too bad.

**Comment by fingolfin** [comment]
It is not really necessary to use `Julia_jll.jl`, though -- esp. if it is sufficient to have one Julia version available (which is usually the case). So you could e.g. add `https://julialang-s3.julialang.org/bin/musl/x64/1.6/julia-1.6.5-musl-x86_64.tar.gz` as one of the "sources" for your JLL. Then as part of the build script, just unpack it somewhere, and invoke that Julia binary.

**Comment by eschnett** [comment]
@fingolfin Thanks! This is working for me.
