### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by dpo** [JuliaPackaging/BinaryBuilder.jl#1136]
Towards the bottom of https://docs.binarybuilder.org/latest/FAQ/#Can-I-publish-a-JLL-package-locally-without-going-through-Yggdrasil?-1, the link "building a custom JLL package locally" leads to a 404. I presume it refers to `--deploy=local`, but it would be great to have documentation about that.

**Comment by giordano** [comment]
https://docs.binarybuilder.org/stable/building/#Building-a-custom-JLL-package-locally
