### ISSUE TITLE
Autobuild package does not use correct Julia compat version

### ISSUE THREAD

**Issue by jeremiahpslewis** [JuliaPackaging/BinaryBuilder.jl#1160]
Running:
https://github.com/jeremiahpslewis/Yggdrasil/blob/boost-gcc-11/B/boost/build_tarballs.jl

with `—deploy` yields a project file like:

https://github.com/jeremiahpslewis/boost_jll.jl/blob/34e8a87bf8572ca774f6018e46f270b2064134a2/Project.toml

E.g. with` compat / julia = 1.0` instead of `compat / julia = 1.6`.

**Comment by giordano** [comment]
Maybe needs to propagate `julia_compat` in https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/15334fde1b7e9fbaed23f4f929575d179d37eb1d/src/AutoBuild.jl#L346
