### ISSUE TITLE
Docker builds fail on Mac M1

### ISSUE THREAD

**Issue by jeremiahpslewis** [JuliaPackaging/BinaryBuilder.jl#1166]
Running a build on Mac yields the following error (tried on a couple different `build_tarballs.jl`:

For `Expat`:

```julia
ERROR: LoadError: MethodError: no method matching artifact_exists(::Nothing)
Closest candidates are:
  artifact_exists(::Base.SHA1; honor_overrides) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Artifacts/src/Artifacts.jl:252
Stacktrace:
  [1] _broadcast_getindex_evalf
    @ ./broadcast.jl:670 [inlined]
  [2] _broadcast_getindex
```

Full output: https://gist.github.com/jeremiahpslewis/a8117fc13c9aa4f3a08a9655eab4117e

**Comment by giordano** [comment]
We only support x86_64 hosts, it's unlikely we'll ever support other architectures, that'd be a combinatorial explosion of lots of tools.

**Comment by jeremiahpslewis** [comment]
Ok, great to know.
