### ISSUE TITLE
Building a library with optional AVX2 support

### ISSUE THREAD

**Issue by cjdoris** [JuliaPackaging/BinaryBuilder.jl#1187]
I'd like to build a library which offers optional AVX2 support at build-time. If I enable this, I get a warning from BinaryBuilder about using instructions not in generic x86_64.

Is there a way I can provide both options? Do I need to expand the list of platforms somehow to include options with and without these instructions?

**Comment by giordano** [comment]
Basically a duplicate of https://github.com/JuliaPackaging/Yggdrasil/issues/4252, I didn't have the time yet to fix the remaining bits

**Comment by cjdoris** [comment]
Actually my question was about how to build such a package, but I can follow the example from the linked issue thank you.
