### ISSUE TITLE
Function to query for bit choice

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPackaging/BinaryBuilder.jl#119]
In many cases one may need to set options a little differently for 32 vs 64 bit, so it would be good easily get a true/false between the two. For example,

```julia
if [ $target = "i686-w64-mingw32" ]; then
cmake -DCMAKE_INSTALL_PREFIX=/ -DCMAKE_TOOLCHAIN_FILE=/opt/$target/$target.toolchain -DCMAKE_BUILD_TYPE=Release -DEXAMPLES_ENABLE=OFF -DKLU_ENABLE=ON DKLU_INCLUDE_DIR=$WORKSPACE/srcdir/SuiteSparse/KLU/Include/ -DKLU_LIBRARY_DIR=$WORKSPACE/srcdir/SuiteSparse/lib -DSUNDIALS_INDEX_TYPE=int32_t ..
else
cmake -DCMAKE_INSTALL_PREFIX=/ -DCMAKE_TOOLCHAIN_FILE=/opt/$target/$target.toolchain -DCMAKE_BUILD_TYPE=Release -DEXAMPLES_ENABLE=OFF -DKLU_ENABLE=ON DKLU_INCLUDE_DIR=$WORKSPACE/srcdir/SuiteSparse/KLU/Include/ -DKLU_LIBRARY_DIR=$WORKSPACE/srcdir/SuiteSparse/lib ..
fi
```

is there a good way to make that "if target is 32-bit, then ..., else ..."?

**Comment by ararslan** [comment]
Your example code there is in shell rather than Julia so I'm not sure whether you're looking for something in shell, but in Julia you can do this with `wordsize(::Platform)`. So you could do something like
```julia
if wordsize(target) == 32
    # add the flag -DSUNDIALS_INDEX_TYPE=int32_t
end
```
which would catch `Windows(:i686)`, `Linux(:i686)`, and `Linux(:armv7l)`. You could reduce to one particular platform with `if target == Windows(:i686)`, for example.

**Comment by ChrisRackauckas** [comment]
It needs to be something that can handle the `target` in shell to be used in the build script, right? I'm looking at:

https://github.com/JuliaDiffEq/SundialsBuilder/blob/sundials_only/build_tarballs.jl#L35-L39

**Comment by ararslan** [comment]
Oh sorry, I misunderstood. Yeah, I guess it would indeed have to be in shell.

Since the only 32-bit architectures supported here are i686 and ARMv7, you could do something like
```sh
if [ $target = i686-* ] -o [ $target = arm-* ]; then
    cmake ... -DSUNDIALS_INDEX_TYPE=int32_t ...
else
    cmake ...
fi
```

**Comment by Keno** [comment]
We can add arbitrary bash functions to the bash prologue, or add extra environment variables (e.g. `$bitness`).

**Comment by staticfloat** [comment]
We'll have `${nbits}` and `${proc_type}` available to us in the `bash` environment after https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/176.  I'll update my `OpenBLASBuilder` to use those once that's merged.

**Comment by staticfloat** [comment]
Aaaaand done.
