### ISSUE TITLE
Dynamic Loader (ELF interpreter) not working under NixOS

### ISSUE THREAD

**Issue by schlichtanders** [JuliaPackaging/BinaryBuilder.jl#1214]
The documentation states that the BinaryBuilder.jl julia binaries are meant to be run on every linux where julia can be installed.

On NixOS there is julia installable (called `julia-bin`), but the binarybuild packages sometimes fail, because of dynamic linking and assumptions on the linux file system.

See the following issues for concrete failures and nixos-specific explanations of the error
- https://github.com/NixOS/nixpkgs/issues/181960#issuecomment-1188468664
- https://github.com/JuliaPackaging/Yggdrasil/issues/4046#issuecomment-992382322

The linked nixos resources for explanation are:
- https://unix.stackexchange.com/questions/522822/different-methods-to-run-a-non-nixos-executable-on-nixos/522823#522823
- https://nixos.wiki/wiki/Packaging/Binaries

It would be great to have a full julia support on NixOS in the near future.

**Comment by giordano** [comment]
See https://github.com/JuliaPackaging/Yggdrasil/issues/5022 and https://github.com/JuliaPackaging/Yggdrasil/issues/4046

**Comment by schlichtanders** [comment]
Thank you so much for the additional link 4046, as it indeed referred to the discourse thread
https://discourse.nixos.org/t/making-lib64-ld-linux-x86-64-so-2-available/19679/2 
where two generic fixes for Julia on Nixos are listed

**Comment by schlichtanders** [comment]
To summarize: the only missing piece is the hardcoded dependency on `/lib64/ld-linux-x86-64.so.2`
if this could be solved without using a hard-coded path, it would run under julia without the above mentioned fixes

**Comment by giordano** [comment]
All other distributions on this planet need that hardcode path. L
