### ISSUE TITLE
Question: build script for C library that uses Premake instead of CMake?

### ISSUE THREAD

**Issue by dylanxyz** [JuliaPackaging/BinaryBuilder.jl#1224]
There's a library called [nanovg](https://github.com/memononen/nanovg) which i want to port to Julia, it is self-contained with just a few files, but it uses the Premake build system instead of CMake. I searched for any mentions of building libraries with Premake within the BinaryBuilder docs but i could not find anything. I'm sorry if i've missed something. Is there a way to use Premake in the build script or i have to convert the premake file to a CMakeLists.txt file?

**Comment by ararslan** [comment]
The sandbox environment that BinaryBuilder uses is based on Alpine Linux, which has `premake` available via its package manager, so you should be able to `apk add premake` inside the script part of your builder recipe.

**Comment by dylanxyz** [comment]
@ararslan When running `apk add premake` i got the following error:

```bash
sandbox:${WORKSPACE}/srcdir # apk add premake
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  premake (no such package):
    required by: world[premake]
```

Running from the BinaryBuilder Wizard, with WSL (Debian).

**Comment by ararslan** [comment]
Did you do an `apk update` first?

**Comment by giordano** [comment]
`premake` is only in [edge](https://pkgs.alpinelinux.org/contents?file=&path=&name=premake&branch=edge&repo=testing&arch=x86_64), not [v3.15](https://pkgs.alpinelinux.org/contents?file=&path=&name=premake&branch=v3.15&repo=testing&arch=x86_64).  Try instead
```console
sandbox:${WORKSPACE} # apk add premake --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/1) Installing premake (5.0.0_beta1-r0)
Executing busybox-1.34.1-r3.trigger
OK: 288 MiB in 118 packages
```

**Comment by dylanxyz** [comment]
@giordano Thanks, that solution works and i'm able to use premake with this script:

```bash
cd ${WORKSPACE}/srcdir

if [[ "${target}" == *-freebsd* ]]; then
    os=bsd
elif [[ "${target}" == *-mingw32* ]]; then
    os=windows
elif [[ "${target}" == *-linux* ]]; then
    os=linux
elif [[ "${target}" == *-apple-* ]]; then
    os=macosx
fi

atomic_patch -d nanovg/ -p1 patches/0001-Build-shared-lib-and-ignore-examples.patch
atomic_patch -d nanovg/ -p1 patches/0002-Fix-missing-headers.patch

apk add premake --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing

cd nanovg
premake5 --os=${os} gmake2

cd build
make -j${nproc} config=release_x${nbits} nanovg

mkdir $libdir
mkdir $includedir

mv *nanovg.${dlext}             ${libdir}/libnanovg.${dlext}
mv ../src/nanovg.h              ${includedir}/
mv ../src/nanovg_gl.h           ${includedir}/
mv ../src/nanovg_gl_utils.h     ${includedir}/

install_license ../LICENSE.txt
```

However, the project won't build because nanovg uses a few opengl types and functions, so the compiler complains to me about some undefined types. How can i include opengl in this project, so the compiler won't be mad at me?

**Comment by dylanxyz** [comment]
Never mind, i figured out 🧐.

**Comment by ararslan** [comment]
Sounds like the issue is resolved so I'll close.
