### ISSUE TITLE
CMAKE_CXX_STANDARD=14 leads to -std=c++1y instead of -std=c++14 when compiling ROOT

### ISSUE THREAD

**Issue by lucifer1004** [JuliaPackaging/BinaryBuilder.jl#1226]
To reproduce, use the wizard to compile 

https://root.cern/download/root_v6.26.06.source.tar.gz

No other dependencies are needed for now.

In `srcdir`, run the command:

```
cmake -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14 -Dminimal=ON root-6.26.06
```

And from the printed information, it can be seen that C++ flag is 

`-std=c++1y -pipe  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -pthread -O3 -DNDEBUG`

But when I did this on my local system (Ubuntu 22.04), the flag is 

`-std=c++14 -pipe  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -pthread -O3 -DNDEBUG`

So I think there is something wrong with the environment provided by BinaryBuilder. But currently, I do not know the root cause of this.

**Comment by lucifer1004** [comment]
Also, it seems that CXX_STANDARD above 14 is not supported yet in the sandbox.

**Comment by giordano** [comment]
Use a version of GCC which actually supports the C++14 standard?  See https://gcc.gnu.org/projects/cxx-status.html#cxx14

**Comment by lucifer1004** [comment]
So this should be solved with `preferred_gcc_version` option?

**Comment by lucifer1004** [comment]
How should I do this in wizard mode?

**Comment by giordano** [comment]
> So this should be solved with `preferred_gcc_version` option?

Yes

> How should I do this in wizard mode?

When you're asked "Do you want to customize the set of compilers?" you have to answer yes:
https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/c3ab9105f9f4787eda1deee5586a58738d4c9f40/src/wizard/obtain_source.jl#L382

**Comment by lucifer1004** [comment]
Thanks!

**Comment by lucifer1004** [comment]
I have never used that option before.
