### ISSUE TITLE
Option `--debug` doesn't work sometimes

### ISSUE THREAD

**Issue by juliohm** [JuliaPackaging/BinaryBuilder.jl#1235]
The option is very helpful to launch a session on the platforms that are failing. It worked nicely when I had a compilation issue: I could directly access the platform after the failure, edit files and retry the build. However, in some cases, the compilation is successful, but the products are not generated as expected. In these cases, the debug option doesn't open a session as expected.

You can reproduce with

```
$ julia --project build_tarballs.jl --debug i686-linux-gnu
```

and with the build_tarballs.jl in https://github.com/juliohm/cross-platform-clfft

**Comment by giordano** [comment]
> However, in some cases, the compilation is successful, but the products are not generated as expected. In these cases, the debug option doesn't open a session as expected.

Do you mean that the failure happens during audit, so _after_ the build process completed? If so, `--debug` only works within the boundaries of the build process itself, during audit you don't need to re-enter the build environment.

**Comment by juliohm** [comment]
Wouldn't it be a good idea to open the prompt anyways so that the user could see what went wrong with the final steps? I don't remember exactly which step the error was thrown, but the end-user experience is not the smoothest.

**Comment by giordano** [comment]
Why?  What shell do you want to open?  The files are already in the `build/` subdirectory, you can just move there.  And you [can already](https://docs.binarybuilder.org/stable/reference/#Command-Line) use `--debug=end` to drop into the shell at the of the job in any case.

**Comment by jeremiahpslewis** [comment]
`--debug=end` is an awesome feature I hadn’t heard about, but would have used frequently. Any good way to make this more visible?

> Why? What shell do you want to open? The files are already in the `build/` subdirectory, you can just move there. And you [can already](https://docs.binarybuilder.org/stable/reference/#Command-Line) use `--debug=end` to drop into the shell at the of the job in any case.

**Comment by giordano** [comment]
Apart from reading the documentation?

**Comment by juliohm** [comment]
> Apart from reading the documentation?

Yes @giordano , you have to assume that most of us are busy doing these jll contributions with the minimum amount of time available. We are sharing the perspective of end-users of BinaryBuilder.jl who would appreciate it if `--debug=end` was the default in case the build failed at the end for example. That is the feature request. Assume less of end-users and the experience will be even more smooth than what it is currently.

**Comment by giordano** [comment]
Well, I also don't have a whole amount of time myself, I work on this stuff on my spare time, and I spend most of my PR reviews posting links to documentation, it's very frustrating because it makes me wonder why I wasted time putting the information in the docs in the first place if no one is going to read it anyway.

**Comment by juliohm** [comment]
It happens to all of us 🤷‍♂️ Most people I know switch tasks so often that little time is left to read verbose documentation pages. In my own packages I feel that I am more productive spending time in helpful error messages, good defaults, good copy/paste tutorials, etc. The users ask less questions and open less issues that way. That has been my experience at least.
