### ISSUE TITLE
Automatically generate diff of any source files

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#125]
Sometimes you end up having to modify files to make the build go through.
We should identify this situation, generate a diff of the file at the end of the build
and give the user the option to apply the diff at the beginning of the build.

**Comment by staticfloat** [comment]
I wonder if we can auto-generate this from the `overlayfs` work directories?  That would be pretty sweet.

**Comment by staticfloat** [comment]
Ah, no, the workspace is the _one_ place that isn't covered by an overlayfs.  We'd just have to keep track of the original state of the files, then diff everything.
