### ISSUE TITLE
Unable to build using `autoreconf`

### ISSUE THREAD

**Issue by RexWzh** [JuliaPackaging/BinaryBuilder.jl#1254]
Hi. I'm writing a wrapper of [zbar](https://github.com/mchehab/zbar), which uses the command `autoreconf -vfi` to generate the executable file `configure`. However, it failed with the following message:

```bash
autoreconf Can't exec "autopoint": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 345
```

**Version info**
```jl
Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, icelake-client)
```

It seems that `autopoint` is missing in the default environment of the container. I've tried the `apt-get` command but failed. How can I fix it? Thanks in advance!

**Comment by RexWzh** [comment]
This error might have to do with the discussion https://github.com/JuliaPackaging/Yggdrasil/pull/3002#issuecomment-841906956 and https://github.com/JuliaPackaging/Yggdrasil/pull/365: The tool `autopoint` is not included in the environment of container.

**Comment by giordano** [comment]
> The tool autopoint is not included in the environment of container.

Yes, we don't include out-of-the-box all possible build tools anyone will ever needs.  But [you can install them](https://docs.binarybuilder.org/stable/build_tips/#Dependencies-for-the-target-system-vs-host-system).  The [build environment is based on Alpine Linux](https://docs.binarybuilder.org/stable/building/#Build-script) v3.15, whose package manager is called `apk`, not `apt-get`.  `autopoint` [is in the `gettext` package](https://pkgs.alpinelinux.org/contents?file=autopoint&path=&name=&branch=v3.15&repo=main&arch=x86_64), so you can install it with `apk add gettext`.  Some recipes in Yggdrasil [do something similar](https://github.com/JuliaPackaging/Yggdrasil/search?q=autopoint).
