### ISSUE TITLE
Add support for non-glibc Linux

### ISSUE THREAD

**Issue by ararslan** [JuliaPackaging/BinaryBuilder.jl#126]
Alpine Linux, which is based on musl rather than glibc, supports Julia but cannot use the glibc-based Linux binaries that we produce here. Like FreeBSD (#32), Alpine users will not be able to use packages with binary dependencies once everything is switched over to BinaryBuilder/BinaryProvider.

**Comment by Keno** [comment]
A bit ironic of course, since the rootfs we use is alpine.

**Comment by staticfloat** [comment]
The latest RootFS contains stealth-support for this; you can get at it via `Linux(:x86_64, :musl)` or `Linux(:i686, :musl)`.  I haven't built it for any other architectures yet, but we of course could.  These platforms are not yet enumerated within `supported_platforms()`, I just need someone to try this out and see if there are any bugs as I'm not 100% confident I have built the `musl` parts of the cross-compiler properly.

**Comment by staticfloat** [comment]
This is now generally available.
