### ISSUE TITLE
Unable to use a version of Rust more recent than 1.61 when building locally

### ISSUE THREAD

**Issue by Taaitaaiger** [JuliaPackaging/BinaryBuilder.jl#1262]
I've written a recipe for Yggdrasil to build a Rust crate that I want to test locally. This crate requires at least Rust 1.65, but the builder always downloads the 1.61 artifact. Looking at the [Ygdrassil RootFS](https://github.com/JuliaPackaging/Yggdrasil/blob/master/0_RootFS/Rust/build_tarballs.jl) and this [BinaryBuilderBase commit](https://github.com/JuliaPackaging/BinaryBuilderBase.jl/commit/f782dc5d327dfa21cc26ae582e4d6424f7df8bc5) 1.65 should be available, but I'm not sure what I'm doing wrong.

**Comment by giordano** [comment]
What version of BinaryBuilderBase.jl do you have? You can see it in the Pkg REPL with
```
] st -m BinaryBuilderBase
```

**Comment by Taaitaaiger** [comment]
```
(@v1.9) pkg> st -m BinaryBuilderBase
Status `~/.julia/environments/v1.9/Manifest.toml`
  [7f725544] BinaryBuilderBase v1.20.0
```

**Comment by giordano** [comment]
I just realised we haven't tagged a new version since November, before we got the new Rust toolchain. This is going to be fixed by https://github.com/JuliaRegistries/General/pull/77520

**Comment by Taaitaaiger** [comment]
Thanks!
