### ISSUE TITLE
Adding more platforms / build options with Pkg Extensions

### ISSUE THREAD

**Issue by rayegun** [JuliaPackaging/BinaryBuilder.jl#1283]
As we hopefully come up on a new LTS within the next year or so (1.9, or 1.10 has been mentioned as possibilities) we should gain Pkg extensions. Would this allow us to add more variants to packages? Thinking HIP/OneAPI Sycl/CUDA for instance.

There's lots more examples of variants but those are probably the most important.

If I wanted to take a stab at platforms for other accelerators for instance would Pkg Extensions be a reasonable choice, or are there other plans?

**Comment by fingolfin** [comment]
I don't understand what you are suggesting / requesting here. What do you mean by "gain Pkg extensions", what should gain them? JLLs? For what purpose, exactly?
