### ISSUE TITLE
Minimum kernel version?

### ISSUE THREAD

**Issue by matbesancon** [JuliaPackaging/BinaryBuilder.jl#1289]
On my work machines, I get the feared warning:
```
┌ Warning: Unable to run unprivileged containers on this system! This may be because your kernel does not support mounting overlay filesystems within user namespaces. To work around this, we will switch to using privileged containers. This requires the use of sudo. To choose this automatically, set the BINARYBUILDER_RUNNER environment variable to "privileged" before starting Julia.
```

Even though the kernel seems more recent than the ones causing troubles:
```shell
$ uname --all
Linux htc-cmp502 5.10.0-25-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux
```

**Comment by matbesancon** [comment]
Specifically, compared to the versions mentioned here:
https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/366

**Comment by giordano** [comment]
What's your operating system?

**Comment by matbesancon** [comment]
```
Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-25-amd64
Architecture: x86-64
```

**Comment by giordano** [comment]
Yeah, on Debian you have to use the privileged runner.

**Comment by matbesancon** [comment]
so with sudo only? From the docs I misunderstood that was a bug that was patched since then. Thanks!

**Comment by giordano** [comment]
Where exactly in the docs? There's a patch applied only by Ubuntu, but any other distribution will likely not have it.
