### ISSUE TITLE
Update `ObjectFile` dependency

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/BinaryBuilder.jl#1307]
BinaryBuilder.jl depends on `ObjectFile = "0.3.6"`. This conflicts with Metal.jl which requires `ObjectFile = "0.4"`. Could this dependency be updated? The latest version is 0.4.1.

**Comment by giordano** [comment]
There is #1277 already, but tests are broken and I don't know why. I don't know what changed in the ObjectFile package.

**Comment by eschnett** [comment]
@giordano How do I see which tests are broken? There doesn't seem to be any Github CI tests.

@staticfloat Do you know what changed in ObjectFile.jl between 0.3.7 and 0.4.1?

**Comment by giordano** [comment]
> @giordano How do I see which tests are broken? There doesn't seem to be any Github CI tests.

I think I ran the tests locally.

**Comment by giordano** [comment]
I'm moderately sure it was https://github.com/staticfloat/ObjectFile.jl/pull/38 which broke it (the minor version number was bumped there), it changed the API of some commands, but never tracked how.

**Comment by eschnett** [comment]
Can we create a new release with the by-now updated ObjectFile dependency?

**Comment by eschnett** [comment]
@giordano Can we release a new version of this package?
