### ISSUE TITLE
Write documentation how one is supposed to handle binary dependencies

### ISSUE THREAD

**Issue by davidanthoff** [JuliaPackaging/BinaryBuilder.jl#131]
Would be great if someone could write a one page doc file that explains how to handle something like ReadStat, which itself requires IConv. So one would end up with a IConvBuilder and a ReadStatBuilder repo, and it would just be good to have documentation that explains end-to-end how that scenario is supposed to work.

**Comment by staticfloat** [comment]
[Here's the little snippet](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/master/docs/src/build_tips.md#builds-with-binary-dependencies) that tells you both how to do this within the Wizard, and how to do it manually in your own `build_tarballs.jl` files.
