### ISSUE TITLE
CMAKE_SYSROOT in the CMake toolchain file

### ISSUE THREAD

**Issue by tshort** [JuliaPackaging/BinaryBuilder.jl#133]
In the CMake toolchain provided in `/opt/$target/$target.toolchain`, `CMAKE_SYSROOT` is set as follows:

```
set(CMAKE_SYSROOT /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/)
```

I think this is causing a [problem](https://github.com/JuliaDiffEq/SundialsBuilder/issues/3) with our KLU build of SundialsBuilder. The CMake scripts have calls to `find_library(KLU_LIBRARY klu ${KLU_LIBRARY_DIR})` that fail (`KLU_LIBRARY_DIR` is `$WORKSPACE/destdir/lib`). I think they fail because CMake prefixes all paths with the `CMAKE_SYSROOT` value, so `find_library` is looking in the wrong place. I tested this by copying the entire `$WORKSPACE` to `$CMAKE_SYSROOT/$WORKSPACE`. Then, the CMake scripts worked fine, and `find_library` found the KLU libraries.

If that makes sense, should the `CMAKE_SYSROOT` be removed from the toolchain file? Or, do we need something different in our CMake call? I think there's also `CMAKE_FIND_ROOT_PATH` that allows you to specify multiple prefix paths to look at. Maybe that could be set to include `/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/` as well as `/` (or maybe `$WORKSPACE/destdir`). Other options or suggestions?

**Comment by tshort** [comment]
I added the following to the CMake invocation, and it worked. Maybe that's the easiest solution.

```
-DCMAKE_FIND_ROOT_PATH=$WORKSPACE/destdir
```

**Comment by tshort** [comment]
Closing as the `CMAKE_FIND_ROOT_PATH` seems like the correct way to handle this. We might need a "building tips" section for things like this.

**Comment by staticfloat** [comment]
That's a good tip; we can also set `CMAKE_FIND_ROOT_PATH` automatically, if that's a good idea.  Do you think it is?  Pinging @keno on this as well, as he knows CMake better than I.

**Comment by tshort** [comment]
I don’t know if auto setting is generally appropriate.
