### ISSUE TITLE
Wizard: Integrate auto-fix

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#14]
Right now the wizard disables auto-fix. I would suggest that rather than performing the auto-fix explicitly, it edits the build script to include the appropriate command.

**Comment by staticfloat** [comment]
This should also alert the user to the fact that these auto-fixes are necessary, so that we can hopefully upstream any build systems fixes we need to.

**Comment by staticfloat** [comment]
This is fixed
