### ISSUE TITLE
Github operations are unreliable, but should be easily recoverable

### ISSUE THREAD

**Issue by aviks** [JuliaPackaging/BinaryBuilder.jl#141]
So at stage 7 of the wizard, we try to create a github token etc. This is inherently a error-prone operation, I've had it fail for multiple reasons. We should ensure that we can recover better from such failure. A few specific ideas: 

* The wizard state is returned from the function. But the user often forgets to save -- running any other command will clear `ans`. It may be better to save the state to a global at that point. 
* When the `.travis.yml` is printed to stdout at the end of stage 6, it does not contain the `deploy` section of the yml. That section is added once the github token is generated. However, printing a template of the `deploy` section at stage 6 (maybe commented) will help the user manually recover from github errors. 
* On failure of the github operations, maybe it should fall back to creating a local repo

**Comment by KristofferC** [comment]
Yeah, I had the GitHub operations fail multiple time for different reasons and having to re-enter the build name, repo name, etc was pretty annoying.

**Comment by staticfloat** [comment]
We've removed most of this stuff, so it should be more robust now.
