### ISSUE TITLE
Too much of a path is recorded in build.jl

### ISSUE THREAD

**Issue by davidanthoff** [JuliaPackaging/BinaryBuilder.jl#144]
Take a look at the generated ``build.jl`` at https://github.com/davidanthoff/ReadStatBuilder/releases/tag/v0.1.1-build.2. The ``ExecutableProduct`` constructor call gets a long path string passed that includes Travis specific paths, which seems wrong to me.

**Comment by staticfloat** [comment]
Excellent catch Sir Anthoff.  Fixed in #155
