### ISSUE TITLE
Auto-download new config.{sub,guess}

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/BinaryBuilder.jl#160]
As we continue to expand our build system to newer and more exotic configurations, we are rapidly going to require the latest and greatest `config.{sub,guess}` files for any project that we build.  For instance, `x86_64-alpine-linux-musl` is not recognized as a valid target except by very recent `config.{sub,guess}` configurations.

We should probably either automatically download the latest ones after unpacking source code, or print it out as one of the hints.  (Perhaps provide a `update_configure` executable or something?)

**Comment by staticfloat** [comment]
This is now available through `update_configure_scripts`.

**Comment by vchuravy** [comment]
We should probably file a report upstream about config.guess using ldd to
differentiate between musl and glibc and tha can screw up cross-compiles
