### ISSUE TITLE
Wizard: Allow git repository for source download

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#17]
The wizard claims it can get the source from a git repository, but that's a lie.
Allow that functionality by auto-detecting what kind of URL it is (tarball or git repo)
and asking for a tag or commit hash if it's a git repo.

**Comment by ararslan** [comment]
> asking for a tag or commit hash if it's a git repo.

Would we allow just pulling master or the tip of another branch?

**Comment by Keno** [comment]
> Would we allow just pulling master or the tip of another branch?

We could allow, it but I think we should capture whatever commit that is for the generated script.

**Comment by ararslan** [comment]
That would be a pretty easy thing to check.

**Comment by staticfloat** [comment]
This was added in https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/11/commits/d30dd2500ad5a29680a8e7b582953c9381b0fe4f
