### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by quinnj** [JuliaPackaging/BinaryBuilder.jl#171]
Source: https://prdownloads.sourceforge.net/tcl/tcl8.7a1-src.tar.gz

this error happens when I first run the build script, then edit it (so it runs the build script again):
```
SystemError: opening file /tmp/julia6HpJjH/yvjjvn0m/destdir/bin/tclsh8.7: Too many open files
```

build script for linux x86_64
```
cd tcl8.7a1/unix
./configure --prefix=$prefix --host=$target
make && make install
```

**Comment by quinnj** [comment]
I realized this is actually an issue of my host process, not the builder image. Setting `ulimit -n 10000` allowed the wizard to continue

**Comment by staticfloat** [comment]
When you say "host process", to what do you refer?

**Comment by staticfloat** [comment]
I just ran into this when building CMake.  Difficult to track down; the julia process itself did not have very many files open as far as I could tell through `lsof`.

**Comment by staticfloat** [comment]
This seems to be fixed; probably because this was all with the QEMU builder.
