### ISSUE TITLE
Generated build.jl file issues

### ISSUE THREAD

**Issue by quinnj** [JuliaPackaging/BinaryBuilder.jl#174]
see the example generated `build.jl` file [here](https://github.com/quinnj/MbedTLSBuilder/releases/download/v0.5/build.jl). It doesn't contain any `download_info` entries. Luckily, we can always glean these from the travis logs, but thought I'd open an issue about it.

**Comment by staticfloat** [comment]
My guess is because [this segment](https://github.com/quinnj/MbedTLSBuilder/blob/19d9e3f246e69f86c1f4bc328e64123615caa0eb/build_tarballs.jl#L84-L91) of your `build_tarballs.jl` is overwriting the `build.jl`.  I don't think you need that chunk of code; why did you add it?

**Comment by quinnj** [comment]
I don't get a `build.jl` release asset w/o it.

**Comment by staticfloat** [comment]
Ah, my bad, you're right.  We've got an architectural problem here.  Solving it would involve a lot of people having to make a small change to their `build_tarballs.jl` files, but those are getting so unwieldly it's time to make yet another layer of abstraction.  :)

**Comment by staticfloat** [comment]
This is fixed now that #175 is merged
