### ISSUE TITLE
Trying to build libxls crashes wizard

### ISSUE THREAD

**Issue by davidanthoff** [JuliaPackaging/BinaryBuilder.jl#183]
I can't copy the error log out of my VM right now, but this is super easy to repo (it happens both on master and the latest tagged versions of BinaryProvider/BinaryBuilder):
1. Start the wizard
2. Get sources from https://github.com/svn2github/libxls ``master``
3. View it crash when it drops into the cross compilation environment

**Comment by staticfloat** [comment]
Good catch David!  This is due to a broken symlink which, while sloppy repository management, definitely shouldn't kill the wizard.  Fix pending in https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/186
