### ISSUE TITLE
BinaryBuilder lies ...

### ISSUE THREAD

**Issue by aviks** [JuliaPackaging/BinaryBuilder.jl#195]
... when it asks me `Press any key to continue...`.  It really wants me to press `Enter`

**Comment by staticfloat** [comment]
Interesting.  We use `read(stdin, Char)` here; perhaps this is a buffered/unbuffered I/O problem?  What OS are you running on?  (Note this is only mild curiosity driving this, I don't actually care)

**Comment by aviks** [comment]
Linux, ubuntu, bash.

**Comment by staticfloat** [comment]
Okay, looks like this is a TTY setting that STDIN is line-buffered on some systems.  I don't particularly want to mess around with that, so I'm just going to change the text to say `Press enter to continue...`.

"Thank you for playing Wing Commander"

**Comment by aviks** [comment]
I think BB master does this again!

![image](https://user-images.githubusercontent.com/378918/83878680-6f8ef800-a734-11ea-99db-c00ce007154d.png)

**Comment by giordano** [comment]
Yeah
```julia
read(stdin, Char)
```
does need Enter, doesn't return immediately after reading the single character

**Comment by aviks** [comment]
Which is fine, the message needs to be updated to say "Press enter..."
