### ISSUE TITLE
Use the wiki to store a list of Builders?

### ISSUE THREAD

**Issue by aviks** [JuliaPackaging/BinaryBuilder.jl#196]
At least to begin with. Helps to discover what people have been building. Should be better than searching for `*Builder` repos in people's account.

**Comment by staticfloat** [comment]
https://github.com/JuliaPackaging/BinaryBuilder.jl/wiki

**Comment by aviks** [comment]
The wiki is set to be editable by committers only. Maybe change that to be more open? 

https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by Gnimuc** [comment]
How about creating an Org for storing all of these builders? Then one can do searching within the Org and people can work together.

**Comment by davidanthoff** [comment]
I can't edit the wiki, so here are three more that maybe someone could add: https://github.com/davidanthoff/SnappyBuilder, https://github.com/davidanthoff/IConvBuilder, https://github.com/davidanthoff/ReadStatBuilder.

**Comment by aviks** [comment]
A few more

* https://github.com/aviks/SnowballBuilder
* https://github.com/aviks/GumboBuilder
* https://github.com/JuliaGeo/GEOSBuilder
* https://github.com/JuliaGeo/PROJBuilder

**Comment by staticfloat** [comment]
> I can't edit the wiki

Hmmm, I kind of thought that was the whole point of having a Wiki.  :P

**Comment by davidanthoff** [comment]
You can change the setting to allow non-collaborators to also edit the wiki.

**Comment by staticfloat** [comment]
I've flipped that setting, so I'm going to close this now.  Feel free to add stuff to the wiki until it gets unwieldy, then we can start organizing it a little bit better.  :)
