### ISSUE TITLE
Repeatedly opening dynamic libraries can have side-effects

### ISSUE THREAD

**Issue by vchuravy** [JuliaPackaging/BinaryBuilder.jl#199]
I was attempting to build LLVM using BinaryBuilder and during the verification phase I encountered
the issue that dlopen is not side-effect free and so repeatedly opening related dynamic libraries can
cause unforseen behaviour (also possible that I misdiagnosed this and this it more has to do with the age-old problem of two libLLVM with different versions being opened in the same process). In any case isolating the verification step would be good.

```
Info: Checking shared library lib/libclang.so
Info: Checking shared library lib/libclang.so.6
Info: Checking shared library lib/libclang.so.6.0
Info: Checking shared library lib/libLLVM-6.0.0.so
Info: Checking shared library lib/libLLVM-6.0.so
Info: Checking shared library lib/libLLVM.so
Info: Checking shared library lib/libLTO.so
: CommandLine Error: Option 'asm-instrumentation' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
vchuravy@anubis:~$ 
```

**Comment by staticfloat** [comment]
I think a library that cannot be `dlopen()`'ed more than once would be a bug in the library.  :P

This however looks to be more of an LLVM thing; especially since it just kills the `julia` process, I'm willing to bet that it triggered some kind of assert within Julia itself, which is really kind of unfortunate, and is likely something that we cannot detect or recover from.

Probably the only way to actually isolate ourselves here would be to create a little C program that just runs `dlopen(argv[1])` or something, and returns 0 if it is able to `dlopen()` it....... but I don't particularly like that either, because I don't want to know if a little `C` program can `dlopen()` it, I want to know if `julia` can `dlopen()` it.

**Comment by vchuravy** [comment]
Yeah it looks more like a LLVM specific thing and it only happens if I build clang as well... We could also just spawn a Julia process in which we execute the dlopen, so that the main process doesn't get killed

**Comment by staticfloat** [comment]
I've added a layer of insulation around `dlopen()` now, so this shouldn't happen anymore.

**Comment by vchuravy** [comment]
```
[14:40:36]  ---> ninja install
[14:40:37] [1/3] Building CXX object Enzyme/CMakeFiles/LLVMEnzyme.dir/Enzyme.cpp.o
[14:40:38] [2/3] Linking CXX shared module Enzyme/LLVMEnzyme.so
[14:40:38] [2/3] Install the project...
[14:40:38] -- Install configuration: ""
[14:40:38] -- Installing: /workspace/destdir/lib/LLVMEnzyme.so
[14:40:38]  ---> ninja install
[14:40:38] espace
[14:40:38] Child Process exited, exit code 0
Info: Beginning audit of /home/vchuravy/src/Enzyme/jlpkg/contrib/build/x86_64-linux-gnu-gcc8/9Cf4SoXy/destdir
Info: Checking lib/LLVMEnzyme.so with RPath list SubString{String}["\$ORIGIN/../lib"]
Info: Ignored system libraries libm.so.6, libc.so.6, libstdc++.so.6, libgcc_s.so.1
Info: Checking shared library lib/LLVMEnzyme.so
[ Info: Found a valid dl path BugpointPasses.so while looking for LLVMEnzyme
[ Info: Found a valid dl path LLVMEnzyme.so while looking for LLVMEnzyme
[ Info: /home/vchuravy/src/Enzyme/jlpkg/contrib/build/x86_64-linux-gnu-gcc8/9Cf4SoXy/destdir/lib/LLVMEnzyme.so matches our search criteria of LLVMEnzyme
: CommandLine Error: Option 'asm-instrumentation' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

**Comment by staticfloat** [comment]
Can you give me your `build_tarballs.jl` so I can check this against the upcoming BB release?

**Comment by vchuravy** [comment]
> Can you give me your build_tarballs.jl so I can check this against the upcoming BB release?

Would love to but it is for a currently private package :/

But as far as I can tell it is the call to `satisfied` that is part of the deps file in https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/af0b4853b2b95b1c411f06f834dcbf461bb50264/src/AutoBuild.jl#L409
