### ISSUE TITLE
objdump: File format not recognized

### ISSUE THREAD

**Issue by stevengj** [JuliaPackaging/BinaryBuilder.jl#206]
I've been trying to put together a BinaryBuilder package for Blosc.jl (at https://github.com/stevengj/BloscBuilder), but am running into an odd problem with the MacOS build:
```
Running `sudo mount /home/travis/build/stevengj/BloscBuilder/downloads/rootfs-x86_64-apple-darwin14.squashfs /home/travis/.julia/v0.6/BinaryBuilder/deps/shards/x86_64-apple-darwin14 -o ro,loop`
............Warning: Linked library /usr/lib/libstdc++.6.dylib could not be resolved and could not be auto-mapped
/opt/super_binutils/bin/objdump: libblosc.1.14.2.dylib: File format not recognized
```
When I run the build on my Mac I get an ordinary `dylib` file here:
```
$ file c-blosc/build/install/lib/libblosc.1.14.2.dylib
c-blosc/build/install/lib/libblosc.1.14.2.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```
Any ideas?

And should I be worried about the `libstdc++.6.dylib` warning?  Is there a problem cross-compiling C++ libraries?

(Unfortunately, none of my machines can run BinaryBuilder directly, so I'm forced to work remotely with Travis.)

**Comment by stevengj** [comment]
Seems like the warning may be innocuous, but in that case it would be good to suppress/avoid it in the first place.

**Comment by staticfloat** [comment]
> Unfortunately, none of my machines can run BinaryBuilder directly

Is there a problem with your OSX machine running BinaryBuilder?

> Seems like the warning may be innocuous, but in that case it would be good to suppress/avoid it in the first place.

Yes, these are sometimes innocuous and we're slowly building up a library of libraries to ignore.  This library should be added to [this list](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/123b0278431763a367e8be63630003041a6fb32e/src/auditor/dynamic_linkage.jl#L108-L113).

> `/opt/super_binutils/bin/objdump: libblosc.1.14.2.dylib: File format not recognized`

That's interesting. I think it's a problem with our `super_binutils`; our `objdump` doesn't know how to open Mach-O files.  I'll look into it.

**Comment by stevengj** [comment]
> Is there a problem with your OSX machine running BinaryBuilder?

Yes, it didn't work.  It may be that the CPU in my office is too old, and I didn't try my laptop at home since I thought only Linux was supported (and my Debian Linux box seems to be too old too).

**Comment by staticfloat** [comment]
OSx is "supported" in that it works for some projects but not others, because there are bugs in the plan9 filesharing setup that exists right now.  Those bugs are documented in some issues that Keno has opened on the upstream repos, but it'll likely be a while before they're fixed, unfortunately.

**Comment by staticfloat** [comment]
https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/221

**Comment by staticfloat** [comment]
This should be fixed now, please pull down the latest `BinaryBuilder` and see if the new rootfs fixes things for you.

**Comment by staticfloat** [comment]
I'm closing this for now, as it seems to have been fixed.
