### ISSUE TITLE
debugging lack of build products

### ISSUE THREAD

**Issue by stevengj** [JuliaPackaging/BinaryBuilder.jl#208]
I created a https://github.com/stevengj/BloscBuilder repo (manually, because the wizard wasn't supported on any of my local machines), and it seems to be mostly running — travis runs, executes the cross-compilers, is clearly producing `.dylib` and `.so` and `.dll` libraries because they are mentioned in the logs, and is creating a new github release when I push a tag (so the OAuth token seems to be working).  There are no error messages (other than the #206 warning, which seems to be innocuous).

However, no build products are attached to the release.   Shouldn't it give an error if it doesn't find the `LibraryProduct` I specified in the `products` argument, or give some kind of diagnostic output?

**Comment by stevengj** [comment]
I added a `println` to my build scripts to output the contents of `readdir("products")`, and it indeed contains the build products:
```
PRODUCTS = String["build.jl", "ZMQ.aarch64-linux-gnu.tar.gz", "ZMQ.arm-linux-gnueabihf.tar.gz", "ZMQ.i686-linux-gnu.tar.gz", "ZMQ.i686-w64-mingw32.tar.gz", "ZMQ.powerpc64le-linux-gnu.tar.gz", "ZMQ.x86_64-apple-darwin14.tar.gz", "ZMQ.x86_64-linux-gnu.tar.gz", "ZMQ.x86_64-w64-mingw32.tar.gz"]
```
so for some reason they are just not getting uploaded to the github release when I tag, even though the release is being created and there is no other error message.

**Comment by stevengj** [comment]
Oh, pushing a `vX.Y.Z` tag automatically creates a "release" on github, so probably it is an authorization problem.

**Comment by staticfloat** [comment]
If you haven't done the Travis setup, then Travis can't (and won't) upload the files back to your Github release.  See this travis documentation for how that works: https://docs.travis-ci.com/user/deployment/releases/, and see [e.g. this `.travis.yml` file](https://github.com/staticfloat/NettleBuilder/blob/e22c8a5441ba2a82b91062ec6fad3fca2b39caf5/.travis.yml#L29-L32) for what it looks like when it's setup properly.

**Comment by stevengj** [comment]
I have done the travis setup, with `travis setup releases`; that's how I got the OAuth key in my .travis.yml file.

**Comment by staticfloat** [comment]
Your travis logs have this in them:

```
Already up to date!
Not currently on any branch.
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	downloads/
	products/
nothing added to commit but untracked files present (use "git add" to track)
Dropped refs/stash@{0} (d53157cb0fdebcc9b37bf2e1642ecdcad1fe29e9)
```

I've never seen this before.  The way I usually do this is to create a GitHub release, which creates a tag on my repository, and that triggers a new travis build.  Have you tried that?

**Comment by stevengj** [comment]
I tried creating a release before and it didn't work, but maybe things have improved.  Trying again now: https://travis-ci.org/stevengj/BloscBuilder/builds/362368700

**Comment by staticfloat** [comment]
Aha, hidden in the warnings is this:

> Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.

In my `.travis.yml` files, I typically do set `skip_cleanup: true`, and I also have a `.gitignore` file that ignores `build` and `products`.  Either of those two steps should be sufficient to fix this.

**Comment by stevengj** [comment]
Ah, I missed the `skip_cleanup: true` line... I originally had copied that from MbedTLSBuilder, but I think it got overwritten by `travis setup releases`.  Trying again now.

**Comment by stevengj** [comment]
Success!  That was the problem.

Would be nice if there was a clearer error message.
