### ISSUE TITLE
Please clarify the details of BinaryBuilder philosophy

### ISSUE THREAD

**Issue by yurivict** [JuliaPackaging/BinaryBuilder.jl#209]
The "Philosophy" section is rather superficial, and doesn't cover a lot of facets of this matter. Therefore, I have several questions:

1. If binaries are going to be distributed by many parties maintaining Julia packages, how will it be guaranteed that such binaries won't be infected with malware in the future? There needs to be a repeatable build process that is able to produce binary-identical packages such that anybody can verify their authenticity. I would like to see the section in the specification covering this, how this will be done.

2. This approach is linux-centric. It assumes that all packages are easy to build for all OSes. But this isn't true at least on BSDs. There are ports on BSD systems, which sometimes go to great lengths patching the otherwise linux-centric packages to build on BSDs. How will BinaryBuilder address this? It seems like using prebuilt packages is beneficial compared to the binary distribution approach.

**Comment by stevengj** [comment]
> There needs to be a repeatable build process that is able to produce binary-identical packages such that anybody can verify their authenticity.

Anyone (with appropriate hardware running Linux) can download the BinaryBuilder root image and build identical binaries.

> This approach is linux-centric. It assumes that all packages are easy to build for all OSes. But this isn't true at least on BSDs.

If something compiles on Linux, Mac, and Windows, then BSD is probably straightforward (especially sinces Macs are a BSD flavor).  Getting things to compile on Windows is usually the hard part.   (Also getting things to support cross-compiling if they have a complicated build system.)

Non-portable binary dependencies are indeed a challenge with no easy answer.  But there are a lot of libraries, especially math/numerical libraries, that port fairly easily, and distributing binaries for these makes life a lot easier for users.

**Comment by staticfloat** [comment]
I'm closing this for now, please let me know if I can clarify anything else further.
