### ISSUE TITLE
missing C++11 <type_traits> header on MacOS

### ISSUE THREAD

**Issue by stevengj** [JuliaPackaging/BinaryBuilder.jl#214]
When compiling ZMQ, I'm getting the error:
```
make[1]: Entering directory '/workspace/srcdir/libzmq'
  CC       external/unity/unity.o
  AR       external/unity/libunity.a
  CXX      src/src_libzmq_la-address.lo
In file included from src/address.cpp:33:
In file included from ./src/ctx.hpp:43:
./src/options.hpp:51:10: fatal error: 'type_traits' file not found
#include <type_traits>
```
The corresponding lines of `options.hpp` are:
```c
#if __cplusplus >= 201103L
#include <type_traits>
#endif
```
Since this is guarded by `__cplusplus >= 201103L`, it means that the C++ compiler is advertising C++11 compliance but is missing the `type_traits` header, which seems to be a bug.

I'll try to work around it by compiling with `-std=c++03`, but in the longer run the MacOS build image should be fixed.

**Comment by stevengj** [comment]
Ah, the ZMQ `configure` script is explicitly calling `AX_CXX_COMPILE_STDCXX_11`, and as a result it is passing the `-std=gnu++11` flag.  That's why it thinks it is C++11.

Still, it is 2018.  Can't we get a C++11 compliant compiler and stdlib?

**Comment by stevengj** [comment]
Other people seem to have encountered this problem with the MacOS SDK: https://stackoverflow.com/questions/22855113/type-traits-file-not-found-xcode-5 ... In openMVG/openMVG#316 they say you need to build with `"-stdlib=libc++ -std=c++11"`

On my own Mac it built as-is, though, so there does seem to be something specific to cross-compiling here.

**Comment by visr** [comment]
> maybe the cross-compile setup is problematic because it is supporting older MacOS versions?

Could be, but we can raise the minimum supported version manually. Being fully explicit here:
```
clang++ -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.10 test.cpp
```
With `test.cpp` being simply `#include <array>`

Will cause
```
test.cpp:1:10: fatal error: 'array' file not found
#include <array>
         ^~~~~~~
```

**Comment by visr** [comment]
Tried to do a little more digging, and came across [osxcross](https://github.com/tpoechtrager/osxcross), which mentions in the README

> [Clang/LLVM is a cross compiler by default](http://clang.llvm.org/docs/CrossCompilation.html) and is now available on nearly every Linux distribution, so we just need a proper [port](https://github.com/tpoechtrager/cctools-port) of the cctools and the OS X SDK.

The cctools-port from this project [is used](https://github.com/staticfloat/julia-docker/blob/77401a2f6bb86afdfd47ab5984431fa44afcd3a7/workerbase/lib/build_crosscompiler.sh#L468), but I don't see any of the SDK re-packaging that is supposedly needed in [BinaryBuilder.jl/download_osx_sdk](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/c984db1f460c9e0edcd91aa4e3ea8f843bfbff83/src/RootFS.jl#L278-L291) or [julia-docker/install_osx_sdk](https://github.com/staticfloat/julia-docker/blob/77401a2f6bb86afdfd47ab5984431fa44afcd3a7/workerbase/lib/build_crosscompiler.sh#L428-L440).

In osxcross this is suggested [here](https://github.com/tpoechtrager/osxcross/blob/474f359d2f27ff68916a064f0138c9188c63db7d/build.sh#L336-L339). That `v1` directory indeed does not exist, there is only a `4.2.1` there.

The re-packaging uses Xcode which does not seem present currently, where it [takes the libc++ headers from](https://github.com/tpoechtrager/osxcross/blob/f02abb415b326859f686e1f4721db6939ee9b40e/tools/gen_sdk_package.sh#L112-L140).

**Comment by Keno** [comment]
I think some of this confusion is that we're shipping both GCC and Clang for OS X. To support clang, we should probably also ship libc++. The dlopen error @stevengj is reporting above looks like we're building against a C++11 version of libstdc++ but loading it on julia built against libc++ (or an older version of libstdc++). Frankly, I think we should discontinue supporting GCC for OS X and only support Clang with a properly built libc++.

**Comment by stevengj** [comment]
Thanks for the clarification @Keno.  Switching to `clang++ -std=c++03` fixed the `dlopen` problem.

**Comment by staticfloat** [comment]
This is a known problem, I've been working on a new rootfs version that will have a much happier `clang`, that is linked against `libc++` by default, as it should be.

**Comment by staticfloat** [comment]
This should be fixed by https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/221

**Comment by staticfloat** [comment]
Okay, please pull down the latest `BinaryBuilder` and try again

**Comment by staticfloat** [comment]
Great, so looks like OSX is working and you're hitting the FreeBSD relocation issue (related to https://github.com/staticfloat/julia-docker/issues/13), so I'm going to close this.
