### ISSUE TITLE
Could not download https://julialangmirror.s3.amazonaws.com/binarybuilder-rootfs-base-2017-12-05.tar.gz

### ISSUE THREAD

**Issue by gtsotsos** [JuliaPackaging/BinaryBuilder.jl#245]
```
julia> Pkg.build("BinaryBuilder")
INFO: Building MbedTLS
INFO: Building BinaryBuilder
INFO: Downloading https://julialangmirror.s3.amazonaws.com/binarybuilder-rootfs-base-2017-12-05.tar.gz to /home/***/.julia/v0.6/BinaryBuilder/deps/downloads/rootfs-base.tar.gz...
[02:29:59] -=#=#   #   #
[02:29:59] curl: (22) The requested URL returned error: 404 Not Found
==================================================================================================================================================[ ERROR: BinaryBuilder ]===================================================================================================================================================

LoadError: Could not download https://julialangmirror.s3.amazonaws.com/binarybuilder-rootfs-base-2017-12-05.tar.gz to /home/***/.julia/v0.6/BinaryBuilder/deps/downloads/rootfs-base.tar.gz
while loading /home/***/.julia/v0.6/BinaryBuilder/deps/build.jl, in expression starting on line 7

=============================================================================================================================================================================================================================================================================================================================

======================================================================================================================================================[ BUILD ERRORS ]=======================================================================================================================================================

WARNING: BinaryBuilder had build errors.

 - packages with build errors remain installed in /home/***/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("BinaryBuilder")`
 - build a single package by running its `deps/build.jl` script

=============================================================================================================================================================================================================================================================================================================================
```
IJulia dependency --> ZMQ --> BinaryBuilder

**Comment by gtsotsos** [comment]
julia> Pkg.add("ZMQ")
INFO: Installing ZMQ v0.6.0
INFO: Building ZMQ
=======================================================================================================================================================[ ERROR: ZMQ ]========================================================================================================================================================

LoadError: MethodError: no method matching BinaryProvider.Linux(::Symbol, ::Symbol, ::Symbol)
Closest candidates are:
  BinaryProvider.Linux(::Symbol, ::Symbol) at /home/***/.julia/v0.6/BinaryProvider/src/PlatformNames.jl:11
  BinaryProvider.Linux(::Symbol) at /home/***/.julia/v0.6/BinaryProvider/src/PlatformNames.jl:11
while loading /home/***/.julia/v0.6/ZMQ/deps/build.jl, in expression starting on line 14

=============================================================================================================================================================================================================================================================================================================================
ERROR: UndefVarError: BinaryProvider not defined
deserialize_module(::SerializationState{IOStream}) at ./serialize.jl:757
handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:698
deserialize(::SerializationState{IOStream}) at ./serialize.jl:637
deserialize_datatype(::SerializationState{IOStream}, ::Bool) at ./serialize.jl:972
handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:677
deserialize(::SerializationState{IOStream}, ::DataType) at ./serialize.jl:1079
handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:690
deserialize(::SerializationState{IOStream}, ::DataType) at ./serialize.jl:1079
handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:690
(::Base.Pkg.Entry.##54#55{Dict{Any,Any}})(::IOStream) at ./pkg/entry.jl:639
open(::Base.Pkg.Entry.##54#55{Dict{Any,Any}}, ::String, ::String) at ./iostream.jl:152
build!(::Array{String,1}, ::Dict{Any,Any}, ::Set{Any}) at ./pkg/entry.jl:636
build(::Array{String,1}) at ./pkg/entry.jl:650
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at ./pkg/entry.jl:570
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at ./pkg/entry.jl:479
edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N} where N) at ./pkg/entry.jl:30
(::Base.Pkg.Entry.##1#3{String,Base.Pkg.Types.VersionSet})() at ./task.jl:335
Stacktrace:
 [1] sync_end() at ./task.jl:287
 [2] macro expansion at ./task.jl:303 [inlined]
 [3] add(::String, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:51
 [4] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at ./pkg/dir.jl:36
 [5] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at ./file.jl:70
 [6] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{String,N} where N) at ./pkg/dir.jl:36
 [7] add(::String) at ./pkg/pkg.jl:117

**Comment by gtsotsos** [comment]
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel Core Processor (Haswell)
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

on an Ubuntu 18.04 instance

**Comment by KristofferC** [comment]
You can use

````
```
code
```
````

to quote your code.

**Comment by gtsotsos** [comment]
Thank you - I don't post often

**Comment by staticfloat** [comment]
You do not need `BinaryBuilder` in order to run `ZMQ`: you only need `BinaryProvider`.

Also, that build system image is very old.  If you `Pkg.update()` to get the latest version of `BinaryBuilder` I think you will be much happier.

**Comment by gtsotsos** [comment]
Thanks - it worked! It maps now to a 2018.04 file.

The issue initially came up after running Pkg.update(). Upgrading IJulia to 1.8.0 from 1.7.0 kept failing due to ZMQ. Hence, i tried to build ZMQ and BinaryBuilder separately.

Cheers,
Giorgos
