### ISSUE TITLE
Default system choices in the wizard

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/BinaryBuilder.jl#250]
I noticed that picking all the systems listed in the wizard creates way too many combinations that timeout Travis. I think it would help if the default platforms were the commonly used ones.

@Keno also mentioned that there may be a way to turn on Travis sharding by default in the wizard.

**Comment by staticfloat** [comment]
That's a good idea; we should time the build on your local machine, and if `# platforms` * `build time` is over 10 minutes or so, we should automatically shard it.  I do wish we could shard on Travis without embedding too much information (e.g. supported platforms list) into the `.travis.yml` file.  Oh well.

**Comment by ViralBShah** [comment]
I just saw the `matrix` stuff in OpenBLASBuilder. Seems fairly easy to do it by default, if that's all there is to it. I guess the other benefit of the sharded builds is that you know exactly which architecture failed.

**Comment by ViralBShah** [comment]
Yes. This issue was to suggest emitting that as the default from the wizard.

**Comment by stevengj** [comment]
Breaking it up into 3 parts (`--part=1/3`,  `--part=2/3`, and `--part=3/3`) by default seems pretty reasonable.

**Comment by staticfloat** [comment]
Now that we have our own buildfarm in Yggdrasil, we don't need to worry about sharding.  (Indeed it automatically runs all builds in parallel)
