### ISSUE TITLE
Switching between different BLAS

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/BinaryBuilder.jl#264]
It would be greatly useful to have a way to switch between different BLAS implementations in BinaryBuilder, and perhaps a general way to have different packages provide the same API.

**Comment by staticfloat** [comment]
I'm not sure what this has to do with `BinaryBuilder`; there's nothing BLAS-specific within this repository.

**Comment by ViralBShah** [comment]
Should this be resolved in the package system? If I have ArpackBuilder.jl and I want to depend on some BLAS provider, how do I do that? For now, I actually include OpenBLASBuilder's build.jl in there.

Maybe this is not the right place to ask this question.

**Comment by staticfloat** [comment]
Yes, I think what you're looking for is a feature within Pkg3 that will allow you to specify that "any one of these sets of packages will satisfy this particular dependency".

I'm going to close this, I think you should ask the question over in https://github.com/JuliaLang/Pkg.jl/issues
