### ISSUE TITLE
Support other archieve formats? (other than gzipped tarball)

### ISSUE THREAD

**Issue by oxinabox** [JuliaPackaging/BinaryBuilder.jl#268]
I got up to 

```
                        # Step 2a: Obtain the source code
Please enter a URL (git repository or gzipped tarball) containing the source code to build:
>
```

And then was blocked.
The source code I want to use is available as a `.zip`
(I'm going to dig around and see if someone has put it on Github)

**Comment by staticfloat** [comment]
yeah....... `.zip` actually works.  Sorry about that.  We support pretty much everything, the actual list is [here](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/8f1318c0db202351632ab98c5c4e889974d9c523/src/wizard/utils.jl#L190-L199).  If you want to edit that string to make it a little more reasonable, feel free to submit a PR editing [this source file[(https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/8f1318c0db202351632ab98c5c4e889974d9c523/src/wizard/obtain_source.jl#L75-L76).

**Comment by ViralBShah** [comment]
I ran into the following:
```
Info: Downloading https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.10.sdk.tar.xz to /home/travis/build/JuliaMath/GMPBuilder/downloads/MacOSX10.10.sdk.tar.xz...
[21:41:21] ######################################################################## 100.0%
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
ERROR: LoadError: Could not unpack /home/travis/build/JuliaMath/GMPBuilder/downloads/MacOSX10.10.sdk.tar.xz into /home/travis/.julia/v0.6/BinaryBuilder/deps/shards/MacOSX10.10.sdk
```

**Comment by ViralBShah** [comment]
Maybe just replace `gzipped` with `compressed`?
