### ISSUE TITLE
Automatically set `--no-same-owner` for tar in sandbox

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#28]
Tar detects that we have (virtual) uid 0 and disables the `--no-same-owner` option. That's not what we want since the only uid we allow is uid 0. Add a bash wrapper to automatically set that option.

**Comment by staticfloat** [comment]
Added in https://github.com/staticfloat/julia-docker/commit/96806e15d1de611f3b07ad311090fa09f49179f7

**Comment by Keno** [comment]
Have you made sure that this is correct. I was under the impression that you also need add a `-` to the first argument if there isn't one, i.e. turn
`tar xf file` into `tar --no-same-owner -xf file`

**Comment by Keno** [comment]
This doesn't seem to have worked. Just encountered this problem again with the latest rootfs.

**Comment by staticfloat** [comment]
Hmmm, post a MWE?

**Comment by Keno** [comment]
Sure
```
$ curl -OL ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.41.tar.gz
bash-4.3# tar xzf pcre-8.41.tar.gz
tar: pcre-8.41/pcre_scanner.h: Cannot change ownership to uid 1169, gid 1169: Invalid argument
tar: pcre-8.41/LICENCE: Cannot change ownership to uid 1169, gid 1169: Invalid argument
...
```
and so on

**Comment by staticfloat** [comment]
Yeah I don't know how I ever thought this was resolved.  My fix just plain never worked.  I'm looking into it.

**Comment by staticfloat** [comment]
Okay NOW this is fixed.  :)
