### ISSUE TITLE
Print platform in error message when build fails

### ISSUE THREAD

**Issue by andreasnoack** [JuliaPackaging/BinaryBuilder.jl#280]
I think it's great that the while build now fails if a single platform fails but it would make it easier to figure out which of the `supported_platforms` failed if the platform is printed in the error message. Currently, I only get, e.g.
```julia
ERROR: LoadError: Build for OpenBLAS did not complete successfully
```

**Comment by staticfloat** [comment]
Yes, great point.  I always end up scrolling back through the buildlog to try and figure out which shard this was built within.
