### ISSUE TITLE
creating github auth on package init means package can't get loaded if you are rate limited

### ISSUE THREAD

**Issue by KristofferC** [JuliaPackaging/BinaryBuilder.jl#285]
I think I loaded BinaryBuilder too many times and got rate limited...

**Comment by staticfloat** [comment]
Oh wow.  That's...... uhh........ that's kind of crazy.  I thought that GitHub doesn't rate-limit the `/auth` endpoint though?

**Comment by Keno** [comment]
That's not a real endpoint. However, the endpoint we use for testing whether the credentials works is `/`. But we send it with an authenticated token, so something else must be going on here.

**Comment by KristofferC** [comment]
It is possible something else happened... All I know is they is messing around with BinaryBuilder.jl a lot and then I was rate limited. But feel free to close if it is likely o misunderstood the cause.

**Comment by KristofferC** [comment]
Although, even though perhaps BinaryBuilder didn't cause the rate limit, it is a fact that I couldn't load it due to being rate limited.
