### ISSUE TITLE
We should version build products

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/BinaryBuilder.jl#294]
both autogenerated `build.jl` files and `.tar.gz` files should have the version embedded within them.  Right now we generate:

```
build.jl
Foo.x86_64-linux-gnu.tar.gz
Foo.i686-w32-mingw32.tar.gz
...
```

I argue we should generate something more similar to:

```
build_Foo-v1.2.0.jl
Foo.v1.2.0.x86_64-linux-gnu.tar.gz
Foo.v1.2.0.i686-w64-mingw32.tar.gz
```

It is unfortunate that version numbers naturally have `.` within them, which kind of breaks the natural separation between fields that we've been using so far (e.g. `$(name).$(platform).tar.gz`).

**Comment by davidanthoff** [comment]
What about underscores for the separation?

**Comment by staticfloat** [comment]
I figured it was much more likely for users to put underscores in names than dots, but so far I haven't seen any names with underscores within them.  That's a decent proposal; note first that `x86_64` would kinda-sorta screw that up, and also that the only parsing we do on these files so far is to grab `\.(.*)\.tar\.gz` as the target triplet, which doesn't rely on any kind of separation between fields.
