### ISSUE TITLE
x86_64 glibc bootstrap does not work properly

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#297]
While things mostly work, we end up trying to load `libgcc_s.so`, which then gets confused because the libc `memset` is an ifunc while the musl one is not:
```
/workspace/usr/bin/julia: Relink `/usr/lib/libgcc_s.so.1' with `/usr/glibc-compat/lib/libc.so.6' for IFUNC symbol `memset'
```
Possible options are:
1. Give libgcc a static version of memset/memcpy
2. Don't use the ifunc mechanism in glibc. 
3. Change the glibc dynamic linker to explicitly reject anything linked against musl.

The full list of symbols libgcc_s gets from libc are:
```
                 U abort
                 U calloc
                 w __cxa_finalize
                 U dl_iterate_phdr
                 U free
                 U malloc
                 U memcpy
                 U memset
                 w pthread_cancel
                 w pthread_getspecific
                 w pthread_key_create
                 w pthread_mutex_lock
                 w pthread_mutex_unlock
                 w pthread_once
                 w pthread_setspecific
                 U realloc
```
which is fairly limited, so I think we can do something here.

Looks like we're not the only ones with this problem. I found https://github.com/sgerrand/alpine-pkg-glibc/issues/58.

**Comment by Keno** [comment]
Unfortunately, it looks like we have the same problem with libstdc++ also, so hacking the dynamic linker to reject any musl-linked libs seems fairly appealing.

**Comment by Keno** [comment]
Ok, I have a patch to the glibc dynamic linker, which seems to help here: https://gist.github.com/Keno/044fe82b77c71981c4cede6da550cee4

**Comment by staticfloat** [comment]
You're a binzard, Keno.  I'm going to carry that patch in my [GlibcBuilder](https://github.com/staticfloat/GlibcBuilder) and eventually see if it fixes things for me.  Slowly but surely, I'm going to try and transition the `julia-docker` build to instead be a horrifying software ouroboros of BinaryBuilder-built software that is then used to assemble the BinaryBuilder rootfs.

**Comment by Keno** [comment]
The patch is written against 2.27 (to replace the one in the rootfs). They've been tweaking that code quite a bit, so it doesn't apply to earlier versions.

**Comment by staticfloat** [comment]
Yeah, I added a second patch for older versions, and it seems to all just work:

```
ll products/
total 613040
drwxr-xr-x 2 sabae sabae     4096 Jun 23 02:09 ./
drwxr-xr-x 7 sabae sabae     4096 Jun 23 01:15 ../
-rw-r--r-- 1 sabae sabae     1671 Jun 23 01:23 build_Glibc.v2.12.2.jl
-rw-r--r-- 1 sabae sabae     1991 Jun 23 01:34 build_Glibc.v2.17.0.jl
-rw-r--r-- 1 sabae sabae     1991 Jun 23 01:53 build_Glibc.v2.19.0.jl
-rw-r--r-- 1 sabae sabae     2154 Jun 23 02:09 build_Glibc.v2.25.0.jl
-rw-r--r-- 1 sabae sabae 35961139 Jun 23 01:19 Glibc.v2.12.2.i686-linux-gnu.tar.gz
-rw-r--r-- 1 sabae sabae 38307674 Jun 23 01:23 Glibc.v2.12.2.x86_64-linux-gnu.tar.gz
-rw-r--r-- 1 sabae sabae 41179113 Jun 23 01:32 Glibc.v2.17.0.aarch64-linux-gnu.tar.gz
-rw-r--r-- 1 sabae sabae 38023834 Jun 23 01:34 Glibc.v2.17.0.arm-linux-gnueabihf.tar.gz
-rw-r--r-- 1 sabae sabae 40537185 Jun 23 01:26 Glibc.v2.17.0.i686-linux-gnu.tar.gz
-rw-r--r-- 1 sabae sabae 43693409 Jun 23 01:30 Glibc.v2.17.0.x86_64-linux-gnu.tar.gz
-rw-r--r-- 1 sabae sabae 41501324 Jun 23 01:49 Glibc.v2.19.0.aarch64-linux-gnu.tar.gz
-rw-r--r-- 1 sabae sabae 38142544 Jun 23 01:53 Glibc.v2.19.0.arm-linux-gnueabihf.tar.gz
-rw-r--r-- 1 sabae sabae 40726096 Jun 23 01:38 Glibc.v2.19.0.i686-linux-gnu.tar.gz
-rw-r--r-- 1 sabae sabae 43837944 Jun 23 01:44 Glibc.v2.19.0.x86_64-linux-gnu.tar.gz
-rw-r--r-- 1 sabae sabae 41789828 Jun 23 02:03 Glibc.v2.25.0.aarch64-linux-gnu.tar.gz
-rw-r--r-- 1 sabae sabae 41673975 Jun 23 02:06 Glibc.v2.25.0.arm-linux-gnueabihf.tar.gz
-rw-r--r-- 1 sabae sabae 41809367 Jun 23 01:56 Glibc.v2.25.0.i686-linux-gnu.tar.gz
-rw-r--r-- 1 sabae sabae 55223947 Jun 23 02:09 Glibc.v2.25.0.powerpc64le-linux-gnu.tar.gz
-rw-r--r-- 1 sabae sabae 45275484 Jun 23 02:00 Glibc.v2.25.0.x86_64-linux-gnu.tar.gz
```

**Comment by Keno** [comment]
Two more things:
- We need to replace /usr/bin/ldd with something like:
```
#!/bin/sh
if test ! -e "$1"; then
    echo "ldd: $1:" "No such file or directory" >&2
    exit 1
fi
if interp=$(/usr/local/bin/patchelf --print-interpreter $1); then
    LD_TRACE_LOADED_OBJECTS=1 exec -a ldd $interp $@
fi
needed=$(/usr/local/bin/patchelf --print-needed $1)

if test "${needed#*libc.musl-x86_64.so.1}" != "$needed"; then
    exec -a ldd /lib/ld-musl-x86_64.so.1 $@
else
    LD_TRACE_LOADED_OBJECTS=1 exec -a ldd /usr/glibc-compat/lib/ld-linux-x86-64.so.2 $@
fi
```
- We need to add `/usr/glibc-compat/lib` to the default search path (the one we get from alpine may do this already).

**Comment by staticfloat** [comment]
This is fixed now, but we will eventually need to do the same for `musl`, I believe.
