### ISSUE TITLE
Install GNU findutils in sandbox

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#30]
@aviks reports
```
xargs: unrecognized option: P
```
when the build script tries to do
```
xargs -0 -n 5 -P $NUM_WORKERS sh -c "$DOWNLOAD_PART" 
```
This is because we use busybox `xargs`, not the gnu version. The gnu version
is in the `findutils` alpine package, so we can simply add that to the container image.

**Comment by staticfloat** [comment]
Added in https://github.com/staticfloat/julia-docker/commit/845ccc823c475b7529e3636b4b32f533734bcd96, when I push the new version of `BinaryBuilder.jl` that I've been working on that integrates the Binzard and automatically downloads the proper rootfs image and everything (hopefully in the next couple of days) this should be included.
