### ISSUE TITLE
long builds time out on travis

### ISSUE THREAD

**Issue by tanmaykm** [JuliaPackaging/BinaryBuilder.jl#300]
Builds which take longer than usual time out. Can it be split into multiple jobs?

https://travis-ci.org/tanmaykm/JuliaThriftBuilder/jobs/399056043

**Comment by KristofferC** [comment]
https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/234 perhaps.

**Comment by tanmaykm** [comment]
Ah, thanks!
Trying it out now.
