### ISSUE TITLE
binaries can not load correct libstdc++.so on travis

### ISSUE THREAD

**Issue by tanmaykm** [JuliaPackaging/BinaryBuilder.jl#304]
Getting error while trying to use binaries built [here](https://github.com/tanmaykm/JuliaThriftBuilder/releases/tag/julia0.6-thrift0.11.0) in a travis test [here](https://travis-ci.org/tanmaykm/Thrift.jl/jobs/399549923)

Error message

```
thrift: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by thrift)
thrift: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by thrift)
thrift: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by thrift)
```

**Comment by tanmaykm** [comment]
maybe related: #253 ?

**Comment by staticfloat** [comment]
Try setting `LD_LIBRARY_PATH` to point to your julia installation folder before running any external binaries.  This is because we ship the libraries your external binaries (such as `thrift`) need, (we ship them with Julia) but you need to tell `thrift` to look there.

**Comment by tanmaykm** [comment]
I got around the issue by statically linking my binary. But it may not be possible to do that in every case.

Shouldn't the appropriate `LD_LIBRARY_PATH` be set always / automatically?

**Comment by staticfloat** [comment]
This is fixed by JLL packages now loading the appropriate compiler support libraries that ship with Julia.
