### ISSUE TITLE
distribute license files in binary tarballs

### ISSUE THREAD

**Issue by stevengj** [JuliaPackaging/BinaryBuilder.jl#309]
I just noticed that the binary tarballs typically created by BinaryBuilder don't include any license/copyright file.   That may technically be a violation of many free/open-source licenses.  Even the MIT license says *The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.*

One solution would be to include a `license` argument to `build_tarballs` that gives the path of a file to include in every tarball, or an array/tuple of paths to handle the case of multiple license/copyright files.

Another alternative would be to just encourage build scripts to install something into `$prefix/license/` (outputting a warning if this directory is empty).  This has the advantage that up-to-date licensing info can be installed from the upstream source.

**Comment by tshort** [comment]
Lack of a license file is also an issue for binary releases at [JuliaBinaryWrappers](https://github.com/JuliaBinaryWrappers). It'd be nice if each repo included a license file or a link to the governing license file. It'd also be nice to have a link back to the builder script that created the binaries.

**Comment by giordano** [comment]
We're working on it 🙂

**Comment by giordano** [comment]
In https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/441 there a script to manually install license files, but this shouldn't be needed in most cases as license files whose names match a list of common license files are automatically installed at the end of the build.  In addition, a warning is showing during the auditing stage if no license file is found in the tarball.

**Comment by staticfloat** [comment]
We do this now, and throw an error when it doesn't happen properly.  We will continue to refine this as we integrate our warnings/errors with the CI process more deeply.
