### ISSUE TITLE
Better hints for autoconf projects

### ISSUE THREAD

**Issue by aviks** [JuliaPackaging/BinaryBuilder.jl#31]
In a project where I had to run autoconf to generate the `configure` script, hints were empty.

**Comment by staticfloat** [comment]
Could you provide a link to the project you used?  I'd like to make sure this works properly.

**Comment by aviks** [comment]
https://github.com/openvenues/libpostal

**Comment by Keno** [comment]
I've added checks for `configure.in` and `configure.ac` which print the autoconf hints now.
