### ISSUE TITLE
Generated build*.jl file has wrong version number

### ISSUE THREAD

**Issue by davidanthoff** [JuliaPackaging/BinaryBuilder.jl#310]
For example, a version tagged ``v0.1.1-build.3`` gets a file named ``build_ReadStat.v0.1.1-dev.jl``, whereas I would expect a file with name ``build_ReadStat.v0.1.1-build.3.jl``.

**Comment by staticfloat** [comment]
The version is completely dependent upon the `version` variable embedded within your `build_tarballs.jl` file, it has nothing to do with the git tag.  It would be nice if we could auto-link those two.

**Comment by vchuravy** [comment]
I suspect that something very similar to [`version_git.sh`](https://github.com/JuliaLang/julia/blob/master/base/version_git.sh) would do the trick.

**Comment by staticfloat** [comment]
Yes, the question is what to do if you're not on a tag.  Just auto-version as `v1.2.3+2` or something?  I could get behind that actually.  That makes a lot of sense.

**Comment by staticfloat** [comment]
The workflow has changed, making this not really an issue now.
