### ISSUE TITLE
File locking necessary to get `apk` working, QEMU fails

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/BinaryBuilder.jl#318]
Sometimes users need to `apk add foo`, but that seems to be broken when running inside of QEMU.  I'm not entirely sure why this is happening (I can't even `flock` something within a `tmpfs` that I mount within the interactive shell, so I don't think it's a 9pfs thing) but it's a bit of a problem for us.

**Comment by NHDaly** [comment]
Saw a similar issue trying to use `apk` on a mac:
```
# apk add go
ERROR: Unable to lock database: Function not implemented
ERROR: Failed to open apk database: Function not implemented
# which apk
/sbin/apk
```

The advice was to install Docker and use the `docker` backend instead:
> set `BINARYBUILDER_RUNNER=docker` and try running it on OSX again; it will use `docker` as the execution engine under the hood, which will dodge many of the `qemu` problems, at the expense of requiring you to have `docker` installed.

**Comment by giordano** [comment]
Not applicable as QEMU runner is not a thing anymore?
