### ISSUE TITLE
Add cross-compilation for FreeBSD

### ISSUE THREAD

**Issue by ararslan** [JuliaPackaging/BinaryBuilder.jl#32]
As of Julia v0.7, FreeBSD is a "first-class citizen," so to speak, for Julia. In an effort to further Julia's usability on FreeBSD, BinaryBuilder should support it, especially since there will be no source build fallback as there is with BinDeps. Without support in BinaryBuilder, any Julia package with binary dependencies will be unusable on FreeBSD.

To encourage work on this issue, I've posted a bounty using BountySource. It's not much, but hopefully it's some incentive. I encourage others who would like to see this addressed to donate as well, provided they have the financial means to do so.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=50925719)](https://www.bountysource.com/issues/50925719-add-cross-compilation-for-freebsd?utm_source=50925719&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by iblis17** [comment]
https://github.com/sandvine/freebsd-cross-build
Just found this, but I don't try it yet.

**Comment by helgee** [comment]
Is this working, yet? The signals are unclear 😉 

* https://github.com/staticfloat/NettleBuilder/blob/master/build_tarballs.jl#L28
* https://github.com/staticfloat/FLACBuilder/blob/master/build_tarballs.jl#L42

**Comment by ararslan** [comment]
I've been busy with other stuff so I haven't been closely following this, unfortunately. @staticfloat, would you say this is effectively resolved?

**Comment by ararslan** [comment]
I think this is sufficiently resolved to warrant closing and awarding the bounty. @wdv4758h, please log into BountySource and claim the bounty. I should get an email that lets me award it to you. Let me know if you run into any trouble, and thanks so much for your work on this!
