### ISSUE TITLE
Build Julia tarballs for all platforms

### ISSUE THREAD

**Issue by barche** [JuliaPackaging/BinaryBuilder.jl#320]
When depending on Julia itself, it is difficult or impossible to extract the dmg or .exe for cross-compilation. Would it be possible to provide official tarballs for all platforms, at least for v0.7-latest and v1.0-latest? My current workaround was to extract natively on each platform and then recompress, putting the tarballs in this repository: https://github.com/barche/julia-binaries/releases

It would be nice to keep this naming scheme, to be consistent with `$target` environment variable from BinaryBuilder.

Ref: https://github.com/JuliaLang/julia/issues/27740

**Comment by fingolfin** [comment]
it seems progress was made on this, yay: https://github.com/JuliaPackaging/Yggdrasil/pull/1048

**Comment by barche** [comment]
Yes, this can be closed 🎉
