### ISSUE TITLE
Switching between BINARYBUILDER_USE_SQUASHFS options is dangerous

### ISSUE THREAD

**Issue by omus** [JuliaPackaging/BinaryBuilder.jl#324]
I was using this ENV option for a while:
```
export BINARYBUILDER_USE_SQUASHFS=true
```
Later, I rebooted my VM and forgot to re-enable the option. This resulted in the GCC not existing inside of the environment.

**Comment by staticfloat** [comment]
I think I tracked down the sequence of events that caused this to happen.  :)
