### ISSUE TITLE
Build should not change cwd to rootfs

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/BinaryBuilder.jl#325]
This makes opening a new tab in tmux while the build is running really annoying.

**Comment by Keno** [comment]
Yeah, also messes up NewPkgEval ;)

**Comment by staticfloat** [comment]
Fixed in https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/321/commits/8a878b1f129274108baae382670cf7771249cb46
