### ISSUE TITLE
Error using docker image

### ISSUE THREAD

**Issue by quinnj** [JuliaPackaging/BinaryBuilder.jl#329]
Using the provided `docker_images/` docker image mostly worked well, but it seemed that I could only build up to 3-4 platforms. Trying to build on additional platforms all resulted in errors like:
```
 			# Attempting to build for Linux(:aarch64, :musl)

Info: Downloading https://julialangmirror-s3.julialang.org/binarybuilder-rootfs-aarch64-linux-musl-2018-05-26.squashfs to /shards/rootfs-aarch64-linux-musl.squashfs...
[13:12:40] ######################################################################## 100.0%
Info: No hash cache found
Info: Calculated hash 631c6acd70a32b07d6c202369bea24ece17a1a09f85257f3a88a3dc6cd9ff281 for file /shards/rootfs-aarch64-linux-musl.squashfs
Info: Mounting /shards/rootfs-aarch64-linux-musl.squashfs to /root/.julia/v0.6/BinaryBuilder/deps/shards/aarch64-linux-musl
mount: /shards/rootfs-aarch64-linux-musl.squashfs: failed to setup loop device: No such file or directory
failed process: Process(`mount /shards/rootfs-aarch64-linux-musl.squashfs /root/.julia/v0.6/BinaryBuilder/deps/shards/aarch64-linux-musl -o ro,loop`, ProcessExited(32)) [32]
Stacktrace:
 [1] pipeline_error(::Base.Process) at ./process.jl:682
 [2] run(::Cmd) at ./process.jl:651
```
The main common error being `failed to setup loop device`. I'm running on an osx host system, but I'm not sure that matters w/ docker involved.

**Comment by staticfloat** [comment]
This should be ameliorated now, but can still happen if too many builds happen in parallel.  The answer is to increase the number of loopback devices available via [`MAKEDEV` and all that mcjiggery](https://unix.stackexchange.com/questions/55356/how-do-i-setup-more-then-10-loopback-device).
