### ISSUE TITLE
Alternative editors

### ISSUE THREAD

**Issue by simonbyrne** [JuliaPackaging/BinaryBuilder.jl#331]
If you're one of [many people who can't figure out vim](https://stackoverflow.blog/2017/05/23/stack-overflow-helping-one-million-developers-exit-vim/), it would be nice to be given an alternative. I would suggest providing emacs and GNU nano.

**Comment by giordano** [comment]
I'm among them. I'm not sure that this is ever going to be fixed, as adding new packages will inevitably make the image larger (maybe nano is light enough, though).

For the record, people can always install packages within the build environment with `apk`:
```
apk add emacs
```

**Comment by staticfloat** [comment]
We have `nano` now, at least.

**Comment by fingolfin** [comment]
Can this be closed then, given that nano was made available?
