### ISSUE TITLE
generated build script has "<tag>" in `bin_prefix`

### ISSUE THREAD

**Issue by ssfrr** [JuliaPackaging/BinaryBuilder.jl#336]
[this build_tarballs.jl](https://github.com/JuliaAudio/RingBuffersBuilder/blob/2c4ec510d24e47fd724ea95c3c3b0fbb29cc71e3/build_tarballs.jl) generated a build script with the following bin_prefix:

```
# Download binaries from hosted location
bin_prefix = "https://github.com/JuliaAudio/RingBuffersBuilder/releases/download/<tag>"
```

I assume the `<tag>` is supposed to be filled in with the actual git tag (which might be an issue here because there is no tag).

Not an urgent issue for me as I'm manually changing the prefix to point to my S3 bucket anyways, but it seemed like an issue.

Here's the build log:
https://travis-ci.org/JuliaAudio/RingBuffersBuilder/builds/422591064

**Comment by KristofferC** [comment]
Seems like this happens here as a fallback:

https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/10ba47d09cc2f2c1b8682775748df949d82e7cc2/src/AutoBuild.jl#L224-L228

**Comment by ssfrr** [comment]
Cool, looks intentional then.
