### ISSUE TITLE
generated build script has FileProduct with full local path from build machine

### ISSUE THREAD

**Issue by ssfrr** [JuliaPackaging/BinaryBuilder.jl#337]
[this build_tarballs.jl](https://github.com/JuliaAudio/RingBuffersBuilder/blob/2c4ec510d24e47fd724ea95c3c3b0fbb29cc71e3/build_tarballs.jl) generated a build script with the following `products` entry. seems like that `FileProduct` path shouldn't be pointing to a path on the build machine.

```
products = [
    LibraryProduct(prefix, ["pa_ringbuffer"], :pa_ringbuffer),
    FileProduct("/home/travis/build/JuliaAudio/RingBuffersBuilder/include/pa_ringbuffer.h", :pa_ringbuffer_h),
]
```

Here's the build log:
https://travis-ci.org/JuliaAudio/RingBuffersBuilder/builds/422591064

**Comment by staticfloat** [comment]
Hahahaha, this is terrible.

**Comment by staticfloat** [comment]
Yes, we'll obviously find a way to fix this.

**Comment by staticfloat** [comment]
Just as note, you can manually work around this for now by changing your `build.jl` file to be of the same form, dynamically calculated from `prefix`.

**Comment by staticfloat** [comment]
I believe this is fixed now.
