### ISSUE TITLE
registry?

### ISSUE THREAD

**Issue by bjarthur** [JuliaPackaging/BinaryBuilder.jl#368]
how does one search for builder repos that others have already created?  google'ing "FooBuilder github" returns many.  but maybe not safe to assume all.  is there a registry like for julia packages?  i ask, because i just created https://github.com/bjarthur/GperfBuilder and wanted to ensure no one duplicated the effort.

**Comment by fredrikekre** [comment]
I think the future is https://github.com/JuliaPackaging/Yggdrasil

**Comment by staticfloat** [comment]
Fredrik is correct, I would like to encourage users to pool all the builder scripts together into one repository.  That being said, there is also a [very incomplete wiki page](https://github.com/JuliaPackaging/BinaryBuilder.jl/wiki) on this repository listing some builder repositories.

**Comment by giordano** [comment]
The future is now, so this can probably be closed
