### ISSUE TITLE
"Open a clean session for this platform" kills the wizard

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/BinaryBuilder.jl#37]
A "Not Implemented Yet" shouldn't kill the wizard, it should loop back to the choice it started from, so as to not increase user blood pressure.

**Comment by Keno** [comment]
to be fair, if you run `run_wizard(ans)` it'll resume where you left off always as a blood pressure safe guard, but yes, I should just implement that.

**Comment by staticfloat** [comment]
That's cool; we need a way to make that obvious to the user
