### ISSUE TITLE
i686-linux-gnu-gcc: error: unrecognized command line option '-V'

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaPackaging/BinaryBuilder.jl#372]
Not sure if this is an issue with the environment or with ImageMagick:
```
configure:5173: $? = 0
configure:5162: /opt/i686-linux-gnu/bin/i686-linux-gnu-gcc -v >&5
Using built-in specs.
COLLECT_GCC=/opt/i686-linux-gnu/bin/i686-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/opt/i686-linux-gnu/bin/../libexec/gcc/i686-linux-gnu/4.8.5/lto-wrapper
Target: i686-linux-gnu
Configured with: /workspace/srcdir/gcc-4.8.5/configure --prefix=/workspace/destdir --target=i686-linux-gnu --host=x86_64-linux-gnu --build=x86_64-linux-gnu --disable-multilib --disable-werror --disable-bootstrap --enable-host-shared --enable-threads=posix --with-sysroot=/workspace/destdir/i686-linux-gnu/sys-root --enable-languages=c,c++,fortran,objc,obj-c++
Thread model: posix
gcc version 4.8.5 (GCC) 
configure:5173: $? = 0
configure:5162: /opt/i686-linux-gnu/bin/i686-linux-gnu-gcc -V >&5
i686-linux-gnu-gcc: error: unrecognized command line option '-V'
i686-linux-gnu-gcc: fatal error: no input files
compilation terminated.
```
Full log:
https://gist.github.com/SimonDanisch/fb87d53ce5efd1409168c53c73c6e6b9#file-config-log

**Comment by leo60228** [comment]
This is a buggy interaction between libtool and autoconf. A workaround was discussed in 2004(!) but I don't believe it was ever implemented. The suggested solution was to run `./configure LDFLAGS=-static; make LDFLAGS=-all-static`. I don't know how to implement that in BinaryBuilder, though.

**Comment by leo60228** [comment]
Horrible hack solution:
```sh
#!/bin/sh
WRAPPED_BIN="gcc"
ARGS=("$@")
ARGS=("${ARGS[@]/#-all-static/-static}")
ARGS=("${ARGS[@]/-V}")
"$WRAPPED_BIN" "${ARGS[@]}"
```

**Comment by staticfloat** [comment]
Why not just do the `./configure LDFLAGS=-static; make LDFLAGS=-all-static` in the builder repository?

**Comment by leo60228** [comment]
...because I'm an idiot sorry. I'll see if BinaryBuilder works on NixOS first, though. Not sure how to setup Travis on a fork.

**Comment by leo60228** [comment]
Wait a second. ImageMagickBuilder explicitly specifies -all-static. Why is it doing this? How did this ever work?

**Comment by staticfloat** [comment]
If I had a nickel for every time I thought that to myself.......

I'll try running it locally without that.  Looks like it's a very recent commit that Simon added to try and fix Windows: https://github.com/JuliaIO/ImageMagickBuilder/commit/22377e5f55f0f037d983d8b355b9beb0fce90c01

**Comment by leo60228** [comment]
Wait, there's already a PR for this. Hm. https://github.com/JuliaIO/ImageMagickBuilder/pull/5

**Comment by staticfloat** [comment]
Confirmed that removing that `LDFLAGS` export fixes this.

**Comment by SimonDanisch** [comment]
Sorry about this, I just copy & pasted that flag from the imagemagick forums and messed up when trying to make sense of the error log....
