### ISSUE TITLE
Automatically generated travis file is for Juiia 0.6

### ISSUE THREAD

**Issue by piever** [JuliaPackaging/BinaryBuilder.jl#374]
I think it's due to [this code](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/db2247562697ef6e2cc0509e15bd4afddb8899f4/src/wizard/deploy.jl#L77): it's a bit confusing as the user will then be relying on different versions of BinaryBuilder on Travis and locally.

**Comment by staticfloat** [comment]
Thanks!
