### ISSUE TITLE
Binaries not even used on TravisCI or Appveyor?!

### ISSUE THREAD

**Issue by dpo** [JuliaPackaging/BinaryBuilder.jl#382]
I set up BinaryBuilder for a project and while I managed to build binaries for a variety of flavors of Linux and Windows, I'm a bit disappointed to see that the Linux binaries aren't even used on TravisCI: 
https://travis-ci.org/JuliaSmoothOptimizers/AmplNLReader.jl/jobs/443779601#L631 (I do a cat of `build.log` after the build).

That makes me wonder how often they'll actually match the user's platform in "real life".

**Comment by dpo** [comment]
The same happens on Windows/MinGW:
```
Warning: no binaries for platform ("x86_64-w64-mingw32", parsed as "x86_64-w64-mingw32-gcc4-cxx11"): attempting source build
```
https://ci.appveyor.com/project/dpo/amplnlreader-jl/builds/19644528/job/kbpimcmmy3qhfwnh#L95. 

In the releases prepared by BinaryBuilder, the target tarball is named `x86_64-w64-mingw32`.

**Comment by staticfloat** [comment]
You've wrapped the whole installation block in a giant `try/catch`; my bet is that something else is going wrong.  Try printing out the actual exception; let's see if there is some error that is getting raised somewhere that explains why you're entering the `catch` branch.
