### ISSUE TITLE
Unreachable statements in build.jl?

### ISSUE THREAD

**Issue by dpo** [JuliaPackaging/BinaryBuilder.jl#383]
The `build.jl` generated by BinaryBuilder contains
```julia
# Install unsatisfied or updated dependencies:
unsatisfied = any(!satisfied(p; verbose=verbose) for p in products)
dl_info = choose_download(download_info, platform_key_abi())
if dl_info === nothing && unsatisfied
    # If we don't have a compatible .tar.gz to download, complain.
    # Alternatively, you could attempt to install from a separate provider,
    # build from source or something even more ambitious here.
    error("Your platform (\"$(Sys.MACHINE)\", parsed as \"$(triplet(platform_key_abi()))\") is not supported by this package!")
end
```
But rather than returning `nothing`, `choose_download()` raises an error when it doesn't find a binary to download. So the following `if` is never executed in that case. It looks like the above should be a `try ... catch` instead.

**Comment by staticfloat** [comment]
This is a really good point.  Looks like I crossed two wires in my head and broke consistency.

I think I like returning `nothing` better than throwing an exception.  I'll open a PR to BP.

**Comment by staticfloat** [comment]
This will be fixed by https://github.com/JuliaLang/METADATA.jl/pull/19669

**Comment by dpo** [comment]
Thanks!
