### ISSUE TITLE
MXE usage?

### ISSUE THREAD

**Issue by barche** [JuliaPackaging/BinaryBuilder.jl#386]
I was looking at cross-compiling Qt, and is seems the recommended way is using [MXE](https://mxe.cc):
https://stackoverflow.com/questions/14170590/building-qt-5-on-linux-for-windows?answertab=votes#tab-top

Is this somehow supported from BinaryBuilder? I think one of the main problems will be running qmake, not sure if there is already another solution for that?

**Comment by staticfloat** [comment]
I have not yet tried to run `MXE` at all.  Conceptually, it does some of the similar things we do inside of BB.  I suggest just trying to do this, and opening issues when you run into specific problems.

**Comment by Keno** [comment]
IIRC from my Qt days, Qt should be quite cross compilable, as long as you get a proper host qmake compiled.

**Comment by barche** [comment]
MXE is indeed not needed, and Qt5 building is tracked in #393
