### ISSUE TITLE
Cannot build without MacOS SDK

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/BinaryBuilder.jl#397]
I am trying to run BinaryBuilder on a Linux box. I do not want to use the MacOS SDK.

When I see the respective question, possible answers are indicated as `(y/N)?`. Hitting "enter" then does not work; the error is something like "answer needs to be either 'y' or 'n'". Explicitly answering "N" does not work. Answering "n" makes BinaryBuilder abort the wizard. Continuing the wizard leads back to the same question. Only the answer "y" works (and downloads the SDK).

**Comment by staticfloat** [comment]
When you are running through the wizard, the very first question asks for which operating systems you wish to build for.  What do you respond with?

**Comment by eschnett** [comment]
I think I responded with the default, which is to build for all operating systems.

**Comment by staticfloat** [comment]
This would explain the behavior; you have requested for it to build for MacOS, and so when you refuse to download the MacOS build shard, it fails the entire build.  You need to, at the beginning of the build process, tell the wizard that you are only building for Linux/Windows/FreeBSD, or something like that.
