### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by dpo** [JuliaPackaging/BinaryBuilder.jl#403]
I'm trying to build OpenBLAS using OpenBLASBuilder.jl on macOS 10.12.6 (Sierra) with docker, but I keep getting this error:
```
x86_64-linux-gnu-objcopy:../libopenblas64_p-r0.3.0.dev.a.renamed: No space left on device
make[1]: *** [Makefile:139: ../libopenblas64_p-r0.3.0.dev.a.renamed] Error 1
make[1]: Leaving directory '/workspace/srcdir/OpenBLAS-0.3.0/exports'
make: *** [Makefile:90: shared] Error 2
ERROR: LoadError: Build for OpenBLAS on x86_64-linux-gnu-gcc4 did not complete successfully
```
I tried increasing the system limits:
```
$ ulimit -S -n 65535
$ sudo sysctl -w kern.maxfilesperproc=65535
$ sudo sysctl -w kern.maxfiles=65535
```
but those don't seem to help. I'm using Julia 1.0.3. I run the build script using
```
$ BINARYBUILDER_RUNNER=docker julia build_tarballs.jl
```
There's more than 65Gb left on the disk I'm using. It's hard to believe building OpenBLAS would take that much disk space.

Any suggestions?

Thanks!

**Comment by barche** [comment]
I just got the same error, for me it was `/tmp` being full.

**Comment by barche** [comment]
Just in case anyone else hits this problem, when running the actual build script (instead of the wizard, which was the case for my previous comment), the source dir is mounted in `tmpfs`, so before starting the compilation you can increase its size using this line in the build script:

`mount -o remount,size=12G tmpfs /workspace/srcdir`

**Comment by staticfloat** [comment]
You probably need to increase your docker image size; you go into docker's settings and increase the disk image size

![image](https://user-images.githubusercontent.com/130920/70287903-7341c200-1785-11ea-8108-f4e641699489.png)

**Comment by dpo** [comment]
I don't have this issue any more.

**Comment by divital-coder** [comment]
hiya this issue still persists for the users who build using the wizard,
i am trying to build SimpleITK using BinaryBuilder using wizard for the linux platforms, but it produces errors in the end relating to no space left on device within the sandbox.
