### ISSUE TITLE
Investigate virtio-fs for qemu

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#404]
Most of our remaining problems with BB on OS X was due to the file system. There's now a new approach to sharing files with the host (https://lwn.net/Articles/774495/) that should deliver higher performance and less confusion. We should try it and see if it improves the situation.

**Comment by giordano** [comment]
If this is QEMU-specific it's probably not applicable anymore, as we don't have a QEMU runner
