### ISSUE TITLE
Cross compiling?

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/BinaryBuilder.jl#411]
The README states: "All packages are cross compiled." Yet I see QEMU being used. Is that statement outdated? Or is cross-compiling only used for Windows?

**Comment by ararslan** [comment]
Everything is indeed cross compiled. Last I checked, QEMU is only used for running BinaryBuilder locally on macOS, and the base platform for building is an Alpine Linux container which cross compiles libraries for each platform using the corresponding toolchains and system files.

**Comment by eschnett** [comment]
I misunderstood.

**Comment by ararslan** [comment]
No worries!
