### ISSUE TITLE
fatal error: Windows.h: No such file or directory

### ISSUE THREAD

**Issue by felipenoris** [JuliaPackaging/BinaryBuilder.jl#413]
I don't know if this is some basic stuff, but isn't the windows toolchain suposed to have `Windows.h`  header file?

```
/workspace/srcdir/mongo-c-driver-1.14.0/src/libmongoc/src/mongoc/mongoc-client.c:22:21: fatal error: Windows.h: No such file or directory
 #include <Windows.h>
                     ^
compilation terminated.
```

**Comment by Gnimuc** [comment]
That's probably due to the wrong cross-compile settings in libmoongoc's Makefile/CMakeLists.txt.  I'm pretty sure BB2's mingw shards work well.

**Comment by felipenoris** [comment]
@Gnimuc Thank you! I'll take a look at that.

**Comment by vchuravy** [comment]
It might also be that it is "windows.h" (didn't check but I did run into case-sensitivity issues https://github.com/staticfloat/LLVMBuilder/blob/master/build_tarballs.jl#L263)
