### ISSUE TITLE
increase verbosity

### ISSUE THREAD

**Issue by felipenoris** [JuliaPackaging/BinaryBuilder.jl#416]
I would suggest to remove the `verbose` option for the build script, so that all output gets printed to `build.log` as if `verbose=true`.

When something goes wrong in the build process, it is sometimes hard to setup a build so that `verbose=true`, and this is kind of silly since now everything gets dumped to a log file.

**Comment by staticfloat** [comment]
JLL packages make this nonapplicable anymore.  Thanks though!
