### ISSUE TITLE
BinaryBuilder wizard should use generate a single Pkg command and use the API interface instead of REPL interface

### ISSUE THREAD

**Issue by KristofferC** [JuliaPackaging/BinaryBuilder.jl#424]
`- julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder#master"; Pkg.build()'`

should be

`- julia -e 'using Pkg; Pkg.add([PackageSpec(name="BinaryProvider"), PackageSpec(name="BinaryBuilder", rev="master")]); Pkg.build()'`

**Comment by staticfloat** [comment]
We don't generate this anymore, but thanks for the tip.  :)
