### ISSUE TITLE
Define OBJC environment variable

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/BinaryBuilder.jl#426]
Sometimes we need to explicitly set the Objective-C compiler (e.g., see https://github.com/JuliaIO/FFMPEGBuilder/pull/5), it'd be useful to have the `OBJC` environment variable already set.

**Comment by giordano** [comment]
This is relevant also for meson #437.  Something like `$CC -x objective-c` should be good for both Clang and GCC

**Comment by staticfloat** [comment]
The next version of BB will make this a little bit easier; I'm generating shell scripts that allow us to "force" more complex compiler behavior; so we can make a general objective-c wrapper script that forces `-x objective-c` into the compiler flags, so that we no longer need to rely so heavily on `LDFLAGS` or `CFLAGS` making it through.  ;)

**Comment by staticfloat** [comment]
What is the typical Objective-C environment variable name? (`$OBJC`?)  Is there a typical compiler executable name for it? (`objcc`?)

We will just need to add it here: https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/sf/pkg_bp_merge/src/Runner.jl#L149-L154

and here
https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/sf/pkg_bp_merge/src/Runner.jl#L190-L195

**Comment by giordano** [comment]
My understanding is that there isn't a standard `OBJC` variables as they usually use `$CC` and relies on auto-detection of the language based on the file extension, however `OBJCFLAGS` is pretty common.  However there are cases where BB users may need to specify the compiler (see FFMPEBuilder above) and having the variable available is very handy.

Meson allows specifying the Objective-C compiler in the cross file, also in that case having the variable available makes it easier to write the file.

**Comment by giordano** [comment]
Fixed by https://github.com/JuliaPackaging/BinaryBuilder.jl/commit/7106456295f34a1e7d791b4b2af8f28a41dd260a
