### ISSUE TITLE
Wizard: MacOS doesn't have arch field

### ISSUE THREAD

**Issue by davidanthoff** [JuliaPackaging/BinaryBuilder.jl#43]
I get an error message during the Wizard saying that ``MacOS`` doesn't have an ``arch`` field.

**Comment by ararslan** [comment]
Is there any backtrace saying where the error occurred? Getting the arch from a `Platform` should use the `arch` function rather than trying to access the `.arch` field, which isn't there in the `MacOS` type.

**Comment by davidanthoff** [comment]
I think it was line 917, the one you fixed in the PR.
