### ISSUE TITLE
Request to FreeBSD-12.0 target (most resent release)

### ISSUE THREAD

**Issue by RobvanW** [JuliaPackaging/BinaryBuilder.jl#433]
Could the latest FreeBSD release, version 12.0 since December 2018, be included as target?

At present various pkg's install fail because of this.

**Comment by ararslan** [comment]
Can you provide more information? It's been my experience that binaries built using FreeBSD 11.x can be used without issue on 12.0, while the reverse is not true.

**Comment by RobvanW** [comment]
I got the issue when trying to install Arpack (see GitHub). The Arpack maintainer suggested to try with the official julia binaries instead of the ports version I have installed.

Will try this out in the coming days and report back.

**Comment by ararslan** [comment]
> The Arpack maintainer suggested to try with the official julia binaries instead of the ports version I have installed.

That was me :smile:

**Comment by RobvanW** [comment]
Solved when using the [official FreeBSD binaries](https://julialang.org/downloads) instead of the default FreeBSD install.

**Comment by ararslan** [comment]
In general we always recommend people install Julia using the official binaries; we have no control over how Julia is packaged by system package managers, so it may be misconfigured or otherwise built in such a way that not everything that's expected to work actually works.
