### ISSUE TITLE
Cross compiling emulators required i.e. setting `CMAKE_CROSSCOMPILING_EMULATOR` 

### ISSUE THREAD

**Issue by ianshmean** [JuliaPackaging/BinaryBuilder.jl#434]
From what I gather, emulators aren't currently available. For instance, they'd be required to cc ITK. See https://github.com/ianshmean/ITKBuilder/issues/1

**Comment by staticfloat** [comment]
This is basically tracked by https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/10
