### ISSUE TITLE
Can BB deal with circular dependencies?

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/BinaryBuilder.jl#440]
There are cases of circular dependencies, e.g. HarBuzz is an optional dependency of Cairo and vice versa, it's possible to eventually build each library with support for the other one: http://www.linuxfromscratch.org/blfs/view/svn/general/harfbuzz.html.

I think that BB can deal with it just as described on Linux From Scratch, I'm dropping this issue just to remember in the future to check this.

**Comment by giordano** [comment]
HarfBuzz is required by Pango in order to enable support for FontConfig, which is then required to enable support for Cairo.  It looks like we have to test this feature soon.

**Comment by staticfloat** [comment]
I don't think we're ever going to support circular dependencies; you will just have to build both at the same time.
