### ISSUE TITLE
Define an Any platform that matches all platforms

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/BinaryBuilder.jl#455]
In [`Yggdrasil`](https://github.com/JuliaPackaging/Yggdrasil/) we have now a few platform-independent packages, like all `Xorg_*proto` (they're just a bunch of header files).  To save a little bit of compilation time and space on disk we could have an `Any` platform that matches all platforms, so that we can build a single tarball and is it everywhere.  This kind of match-them-all target is used also in GNU/Linux distros, like Debian and Arch Linux (I'm familiar with these, but probably other distros adopt the same strategy)

**Comment by staticfloat** [comment]
This should be pretty easy.  Something that does:

```julia
struct AnyPlatform <: Platform; end
Pkg.BinaryPlatforms.platform_name(p::AnyPlatform) = "AnyPlatform"
Base.show(io::IO, p::AnyPlatform) = write(io, "AnyPlatform")
```

Build it with a default set of compiler shards (`x86_64-linux-musl`, probably).  Then have the JLL wrapper generation bind it as a non-platform-specific artifact, generate a single wrapper, and throw an error i someone tries to pass in an `ExecutableProduct` or a `LibraryProduct`; we will only support `FileProduct`s for such JLL packages.
