### ISSUE TITLE
Long delay without output when first downloading shards

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#461]
I installed BinaryBuilder from scratches without any shards cached and nothing happened for a minute or so while it was downloading the shard. If I didn't know what was happening, I'd have probably interrupted the process thinking it was stuck. It would be good to have a progress bar, but even just a simple `Downloading shard, this may take a few minutes...` would be good as an initial fix.

**Comment by staticfloat** [comment]
This should be fixed now.
