### ISSUE TITLE
GitHub password entry has echo enabled

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#465]
The convention for CLI entry of passwords is to disable terminal echo so people looking over your shoulder don't see your password.

**Comment by giordano** [comment]
This uses `readline`, which doesn't seem to support not echoing the input.  Is there any function that already has this feature?

**Comment by Keno** [comment]
https://github.com/JuliaLang/julia/blob/1df2dbe2a3485053330747a831353b53ddecd27c/base/util.jl#L508
