### ISSUE TITLE
sys/clonefile.h missing for macOS

### ISSUE THREAD

**Issue by barche** [JuliaPackaging/BinaryBuilder.jl#500]
Qt includes the header `sys/clonefile.h`, but it seems to be missing from the SDK included in BinaryBuilder.

On my Mac, this file is found in `/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/clonefile.h`

On the BinaryBuilder shell, it is missing from `/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/include/sys/`

**Comment by giordano** [comment]
Maybe this file has been included in a recent version of the SDK?

**Comment by giordano** [comment]
The copyright years point to 2015: https://opensource.apple.com/source/xnu/xnu-3789.1.32/bsd/sys/clonefile.h.auto.html. BinaryBuilder.jl is using macOS SDK 10.10, which should be from 2014 as far as I can see, to support all macOS versions supported by julia

**Comment by barche** [comment]
Aha, thanks. I'm not seeing where the newer SDK is installed and used in that PR, however.

**Comment by giordano** [comment]
Yeah, I think it's hidden in the history, maybe lost in one of the force pushes 😆  You can see in https://github.com/JuliaPackaging/Yggdrasil/blob/ea72d8999277dd28e615ff05452d1e2d8b87b16c/0_RootFS/GCCBootstrap/build_tarballs.jl how the SDK is installed in the BB environment

**Comment by barche** [comment]
OK, so I managed to replace the `usr` directory for the SDK and that fixed the compile error, but now I get lots of linker errors like these:

```
[16:46:26] Creating qmake...
[16:48:07] Undefined symbols for architecture x86_64:
[16:48:07]   "_kUTTagClassFilenameExtension", referenced from:
[16:48:07]       __ZL9isPackageRK19QFileSystemMetaDataRK16QFileSystemEntry in qfilesystemengine_unix.o
```

Is anything special needed to make it pick up the libraries after replacing the SDK?

**Comment by giordano** [comment]
> but now I get lots of linker errors like these:

Have you tried looking at https://stackoverflow.com/a/19240716/2442087?

> Is anything special needed to make it pick up the libraries after replacing the SDK?

I don't think so.  You can see in the `build_tarballs.jl` I linked above what is done to create the environment.

**Comment by barche** [comment]
Thanks, I'll take a look. In the mean time I have found out it is trying to build qmake using the target compilers, so I have to fix that first. This issue can be closed for me.
