### ISSUE TITLE
FreeBSD binaries not picked up?

### ISSUE THREAD

**Issue by dpo** [JuliaPackaging/BinaryBuilder.jl#512]
I'm experimenting with CirrusCI and the FreeBSD binaries compiled with BinaryBuilder. The latter refer to FreeBSD 11.1, a version [not available on CirrusCI](https://cirrus-ci.org/guide/FreeBSD/#list-of-available-image-families). As a result the binary isn't picked up by BinaryProvider: https://cirrus-ci.com/task/6209740715065344?command=build#L89.

NB: I'm currently cheating a bit waiting for https://github.com/JuliaRegistries/General/pull/5667 to be merged. I'm providing the binaries for Julia 1.2 by way of the TOML file using [my own `build.jl`](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/blob/binprovider2/deps/build.jl). All is well on Linux, macOS and Windows, but not FreeBSD.

**Comment by ararslan** [comment]
We build binaries using FreeBSD 11.1 because binaries built on 11.1 are able to be used on later versions. The same is not true of 12.0; binaries built on 12.0 can't be used on 11.x. I don't think that's relevant to this situation, as I've never seen this with any other Julia packages with binary dependencies testing on FreeBSD.

**Comment by giordano** [comment]
> I'm currently cheating a bit waiting for JuliaRegistries/General#5667 to be merged.

The PR to the General registry is useful only if you're going to use a JLL package for Julia 1.3+.  If you want to install the binaries on user's system with `BinaryProvider.jl` you need a `build.jl` file.  In Yggdrasil there a script to do this: [`generate_buildjl.jl`](https://github.com/JuliaPackaging/Yggdrasil/blob/ece7b5dd77f03cf6cf1c4c52243d8386630ea5bf/generate_buildjl.jl).

You can see the syntax of the command by passing no arguments to the script
```
julia --color=yes generate_buildjl.jl ${dir}/build_tarballs.jl
```
The first argument is the path to the builder script in Yggdrasil, the other ones are mandatory only if the JLL package has not been registered yet (like in this case) or if you don't want to get the `build.jl` file for the latest registered version.  The second argument is the specification of the repository  where the JLL package is (https://github.com/JuliaBinaryWrappers/ASL_jll.jl) and the tag version you're interested in:
```
julia --color=yes generate_buildjl.jl ${dir}/build_tarballs.jl A/ASL/build_tarballs.jl JuliaBinaryWrappers/ASL_jll.jl ASL-v0.1.0+0
```

**Comment by dpo** [comment]
Ok, thank you. I couldn't find documentation on that, which is why I hacked my own script. I'm getting a little further now. The tar ball is downloaded on FreeBSD, but Julia isn't happy with it:
```
ERROR: LoadError: LibraryProduct(nothing, ["libasl"], :libasl, "Prefix(/tmp/cirrus-ci-build/deps/usr)") is not satisfied, cannot generate deps.jl!
```
https://cirrus-ci.com/task/6197823992758272?command=build#L86

Here's the [`build.jl`](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/blob/binprovider2/deps/build.jl). Any ideas? I don't have access to a FreeBSD system to test.

**Comment by giordano** [comment]
> Ok, thank you. I couldn't find documentation on that, which is why I hacked my own script.

I opened this PR https://github.com/JuliaPackaging/Yggdrasil/pull/221 to document this process.

> Any ideas?

That error message basically means that the shared library could not be dlopened.  Try running

```julia
using Libdl
@show dllist()
@show dlopen(libasl)
```

at the beginning of the `runtests.jl` script, to see if you get more information.

Something that usually happens is that you're missing some dependencies, but I don't think this is the case, as your library doesn't have dependencies apart from system ones.  This is also confirmed by `objdump`:

```
sandbox:${WORKSPACE} # x86_64-unknown-freebsd11.1-objdump -p libasl.so | grep NEEDED
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.5
  NEEDED               libgcc_s.so.1
  NEEDED               libc.so.7
```

However I'm seeing that it depends on `libsdtd++.so.6`.  @ararslan I don't see this library in Julia's tarball for FreeBSD while it's in the one for Linux, is this expected?

> I don't have access to a FreeBSD system to test.

Me neither, and it's always fun to debug via Cirrus :upside_down_face:

**Comment by dpo** [comment]
The answer is `ERROR: LoadError: UndefVarError: libasl not defined`: https://cirrus-ci.com/task/5462958175420416?command=test#L3.

**Comment by giordano** [comment]
> The answer is ERROR: LoadError: UndefVarError: libasl not defined

That's because I told you something stupid: the build failed, so there is no `deps.jl` file defining that variable.  You have to use the explicit path to the shared library.  If it isn't `/tmp/cirrus-ci-build/deps/usr/libasl.so` you should try to find it out yourself.

**Comment by giordano** [comment]
@dpo: any particular reason why you're forcing GCC here:
https://github.com/JuliaPackaging/Yggdrasil/blob/867d1d4bdc402bfe6cda0e81bf4fcad1c6930c6f/A/ASL/build_tarballs.jl#L50-L51
?  I think you should just remove those lines, `CC` and `CXX` are already set to the appropriate values

**Comment by dpo** [comment]
I added that while trying to build locally and the macOS build failed consistently. At this point, it's probably a remnant of old attempts at getting the builds to complete. Many thanks for getting your hands dirty with this build formula!

**Comment by giordano** [comment]
@dpo did you have a chance to test whether #223 fixed the problem with loading of binaries on FreeBSD?

**Comment by dpo** [comment]
All green lights!!! https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/pull/83

Many thanks!
