### ISSUE TITLE
Integrate AZP logging rules

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/BinaryBuilder.jl#513]
It would be neato burrito to have things like our audit passes be cognizant of Azure Pipelines' [logging output infrastructure](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash).  This would allow us to have the audit warnings all be visible from GitHub's summary page, which would be especially useful for Yggdrasil.

**Comment by oxinabox** [comment]
To talk on how I would do this with LoggingExtras:
Becausee you need to control exactly how the message is formatted a `TransformLogger` can't help you.
As the composable loggers are all about the content.
Decising on its presentation is entirely the problem of the Sink.
You can maybe do it by customizing the metaformatter of the ConsoleLogger.
but maybe easier just to declare a custom sink

Here is a untested sketch of the code for the sink
```
import Logging: AbstractLogger, shouldlog, catch_exceptions,min_enabled_level,handle_message

struct AzureSinkLogger{F} <: AbstractLogger
    action_chooser::F
    io::IO
end

AzureSinkLogger(f=_->"task.logissue")=AzureSinkLogger(f, stderr)


function handle_message(logger::AzureSinkLogger, args...; kwargs...)
    #Make it a named tuple for easier working
    log = LoggingExtras.handle_message_args(args...)
    task::String = logger.action_chooser(log)
    
    properties=String[]
    for key in (:level, :_module, :group, :id, :file, :line)
        push!(properties, "$key=$(log[key])")
    end
    for key in keys(args.kwargs)
        push!(properties, "$key=$(log.kwargs[key])")
    end
    props=join(properties, ";")
    # format: ##vso[area.action property1=value;property2=value;...]message
    print(logger.io, "##[$task $props]$(log.message)")
end
shouldlog(::AzureSinkLogger, arg...) = true
min_enabled_level(::AzureSinkLogger) = BelowMinLevel
catch_exceptions(::AzureSinkLogger) = true
```

Then say you only want to do this for warnings and errors
then you use a TeeLogger to send the logging stream to two childs
and on one you put a MinLevelFilter going to a AzureSinkLogger.
And you leave the other with the old `current_logger()`

**Comment by giordano** [comment]
In my fork I issued the following commands in an AZP script:
```sh
      echo "##vso[task.logissue type=error]Something went very wrong."
      echo "##vso[task.logissue type=warning]Something went somewhat wrong."
```
This is the output:
![image](https://user-images.githubusercontent.com/765740/70184895-ba29ac00-16e0-11ea-8882-d92c533c8872.png)
