### ISSUE TITLE
Make unpacked size of rootfs smaller

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#54]
We're running into some size limitations on travis. Looks like what's happening is that when it downloads/stores the cache image, we have two copies of the compressed data and one of the uncrompressed data, which is too much. We can probably reuse at least libgmp and libmpfr as well as the binutils across all the linux toolchains to save some space, which should help at least a little bit.

**Comment by staticfloat** [comment]
We've solved this.  Good job.  ✋
