### ISSUE TITLE
Look into distributing rootfs as a squashfs image

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#55]
https://en.wikipedia.org/wiki/SquashFS

Would help with #54 by getting rid of one copy of the data and would let us save some time on every build by allowing is to forgo the decompression step.

**Comment by Keno** [comment]
Unfortunately it looks like you cannot mount a squashfs inside a user namespace. On travis that'd be fine since we have sudo, but this probably means we can't stop distributing the tar.gz version of this.

**Comment by Keno** [comment]
For my own future reference, this is the most up to date reference I could find on the state of userns fs mounts: https://lwn.net/Articles/652468/.

**Comment by staticfloat** [comment]
Do we know how new of a kernel you need to be running to support loopback mounts within a userns?

**Comment by Keno** [comment]
It's not enabled for mainline kernel at the moment. Ubuntu allows it for ext4 if you manually enable it. Neither allows it for squashfs at the moment.
