### ISSUE TITLE
Check if the tag is already existing before attempting new registration and upload of artifacts

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/BinaryBuilder.jl#554]
Some history:
* https://github.com/JuliaPackaging/Yggdrasil/pull/289 was merged before https://github.com/JuliaRegistries/General/pull/6701 was merged
* `get_next_wrapper_version` decided that the next wrapper version would have been `v"5.4.0+2"`, as `v"5.4.0+1"` is the [last registered version](https://github.com/JuliaRegistries/General/blob/62741f41b7b8c23609a807338abdd4a815bec2d2/S/SuiteSparse_jll/Versions.toml)
* the new artifacts have been uploaded to release [`SuiteSparse-v5.4.0+2`](https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/tag/SuiteSparse-v5.4.0%2B2), **overwriting** the existing ones
* this wreaked havoc into Julia, causing https://github.com/JuliaLang/julia/pull/34082#issuecomment-565837625

We need to check if the tag is already existing before attempting the upload and registration.

**Comment by giordano** [comment]
Thinking more about this, the current behaviour could probably be considered a feature as it avoids manually deleting tags, but it causes problems in the very unlikely case where the artifacts are used outside of the General registry, like if they're used in Julia

**Comment by ViralBShah** [comment]
Would it be possible for Yggdrasil increment the package version irrespective of whether something was merged in General? Basically, always upload new binaries and never overwrite.

**Comment by giordano** [comment]
> Would it be possible for Yggdrasil increment the package version irrespective of whether something was merged in General?

The function [`get_next_wrapper_version`](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/579eb5b2e2c64fa07046f89da676952545bf5dc0/src/AutoBuild.jl#L307-L329) does increment the build version, but it looks at the latest version in the registry.  The problem is that here we had a new tag in the JLL wrapper repository but the corresponding PR had not been merged yet.

**Comment by giordano** [comment]
Oh, I see that the [invocation of `ghr`](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/579eb5b2e2c64fa07046f89da676952545bf5dc0/src/AutoBuild.jl#L295) is
```julia
run(`$ghr_path -replace -u $(dirname(repo)) -r $(basename(repo)) $(tag) $(path)`)
```
so the overwriting behaviour was very much desired :stuck_out_tongue:

**Comment by vchuravy** [comment]
As long as the tag isn't merged the overwrite behaviour makes sense, since it is basically the only way to fix mistakes. More of an argument to integrate the build system closer with Yggdrasil

**Comment by staticfloat** [comment]
I think we will be able to close this once automerge is turned on for JLLs.  That should greatly reduce the chance of issues like this from happening.
