### ISSUE TITLE
Installation of Bzip2_jll fails for user-namespace root users

### ISSUE THREAD

**Issue by rohanlean** [JuliaPackaging/BinaryBuilder.jl#555]
Running `]add Bzip2_jll` as a root user in a user namespace (for example in a julia container started as a regular user with `podman run --rm -it julia`) results in errors such as the following:
```
tar: ./bin/bunzip2: Cannot change ownership to uid 261840, gid 261840: Invalid argument
```
because `tar` tries to preserve ownership by default when run as root, but 261840 will not generally be a subuid available to root in the user namespace.

I suspect that ownership should never be preserved when extracting (and suid/sgid never set).  Other packages may also have this problem, I just encountered it for Bzip2_jll.

**Comment by Keno** [comment]
Yes, we should ignore uid bits when extracting, though I guess this is technically a Pkg bug (though maybe binarybuilder should just set the uids to 0 when it creates the tar file).

**Comment by giordano** [comment]
Should have been fixed by https://github.com/JuliaLang/Pkg.jl/pull/1557, it'll go live in one of the next Julia versions.
