### ISSUE TITLE
Be more parallel

### ISSUE THREAD

**Issue by vchuravy** [JuliaPackaging/BinaryBuilder.jl#565]
There are several steps in the BinaryBuilder pipeline that could benefit from parallelism or at least asynchronicity.

For large builds like `LLVM` the verifier takes a noticeable amount of time and it is indeed the only serial part of the build. A build from ccache can be as fast as 10 minutes with cmake being half that time, but the verifier can add up to 30 minutes on top of that. 

On the other side of the spectrum is the downloading of shards which is also serial and the unpacking of them. We should make these io bound task `@async`.

**Comment by vchuravy** [comment]
closed in favor off #670

**Comment by giordano** [comment]
Partially addressed by #1364.  LLVM audit time spiraled to over 2 hours in recent times, but with that PR we were able to cut up to 80 minutes: https://github.com/JuliaPackaging/Yggdrasil/pull/10479#issuecomment-2646661935
