### ISSUE TITLE
Tests are failing on Julia nightly

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaPackaging/BinaryBuilder.jl#582]
See for example: https://travis-ci.org/JuliaPackaging/BinaryBuilder.jl/jobs/630106276

It's a problem with `Pkg` (specifically, the `Pkg.Compress` module was removed). But I'm opening this issue so we don't forget about this. It would be nice to get the BinaryBuilder tests passing on Julia nightly.

**Comment by staticfloat** [comment]
@KristofferC Do you know where we should go to get the `Compress` module in Pkg on 1.4+?

**Comment by KristofferC** [comment]
It is in the Pkg bin folder. It should be moved to RegistryTools.jl.

**Comment by giordano** [comment]
Tests are now passing on Julia nightly
