### ISSUE TITLE
Allow exporting build_tarballs.jl even from an unfinished wizard state

### ISSUE THREAD

**Issue by NHDaly** [JuliaPackaging/BinaryBuilder.jl#589]
Related to https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/222, if the user kills a build partway through (due to, e.g., a failure), it would be nice to allow them to still generate a build_tarballs.jl file with just the state as recorded so far.

This is especially useful if you've already gone through a couple of the platforms and things worked as expected, and you just want to rush through to the finish line; and/or try something else but not lose all your work so far; and/or maybe the build failed, but you don't know why, and want to upload the result anyway to share it with others and get some help.

This could perhaps be an option when you resume `run_wizard()` after exiting, in addition to "resume," there could be an "export build_tarballs.jl from current state" option or something?

**Comment by NHDaly** [comment]
label:wizard

**Comment by NHDaly** [comment]
And/or maybe the build failed, but you don't know why, and want to upload the result anyway to share it with others and get some help.

**Comment by NHDaly** [comment]
This could perhaps be an option when you resume `run_wizard()` after exiting, in addition to "resume," there could be an "export build_tarballs.jl from current state" option or something?

**Comment by giordano** [comment]
PR at #761
