### ISSUE TITLE
`expand_cxxstring_abis` for FreeBSD and MacOS

### ISSUE THREAD

**Issue by vchuravy** [JuliaPackaging/BinaryBuilder.jl#621]
@staticfloat I recall having a conversation which you recently about building LLVM, where
we were confused about the fact that both Mac and FreeBSD got their cxxstring ABIs expanded.

As we can see here https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases that is indeed the case and it causes issues with https://github.com/JuliaLang/julia/pull/34418 since the base infrastructure doesn't seem to expect the cxxstring ABI on FreeBSD or Mac.

**Comment by staticfloat** [comment]
We just need to tell the Make system to always download the `cxx03` or `cxx11` build.  Because we build with `clang` on those platforms, the extra defines we add don't change anything (it _would_ if we used `g++` or `gcc` in the build, but we know we don't).

**Comment by vchuravy** [comment]
Fixed upstream.
