### ISSUE TITLE
Warn the user if the build already exists in Yggdrasil

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/BinaryBuilder.jl#631]
In https://github.com/JuliaPackaging/Yggdrasil/pull/441 Valentin opened a PR for a library which was actually already in Yggdrasil.

When the user is prompted for the name of the package in the wizard it might be good to check if this is already available in Yggdrasil and ask whether they want to continue anyway: one for example can build a newer version of the package.

Name checking is a bit tricky since we can choose different names, for example with or without "lib", or with different capitalisation (this latter problem can of course be worked around by checking the lowercase names).

**Comment by giordano** [comment]
It turns out that this is already done: https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/a994f7e8a57ae8ffcf2c62f13d0b3937ff05e339/src/wizard/obtain_source.jl#L336-L345

However, this doesn't work for two reasons:
1. `get_yggdrasil()` actually never updates the repo, because it performs only the `fetch`, but not the `merge`.  My local Yggdrasil bare repo is stuck at https://github.com/JuliaPackaging/Yggdrasil/commit/20a84ddd0a0128ee10a0797636544243e0aa9b8c
2. this assumes that all builders have the standard path `X/XYZ/build_tarballs.jl`, which is no longer the case for builders with multiple versions at the same time

Issue 1. can be fixed (and should, regardless the present issue), but 2. cannot.  I think we should check the packages in the registry instead.

**Comment by giordano** [comment]
@00vareladavid pointed out that
```julia
joinpath(yggdrasil_path, yggdrasil_build_tarballs_path(new_name))
```
is completely wrong because `yggdrasil_path` is a bare repo

**Comment by aquatiko** [comment]
It's just an idea, I'm not sure how much of this can be implemented. I'm still getting myself familiar with the project. If this looks good I can give it a try.
I was thinking if we can show the user a list of similar package which already exist when he selects a name (either at his local build on his demand or when he submits a PR automatically). 
This can be done by fetching currently existing packages names and running a script that can do a regex match (after normalizing names ofc) and find packages with high similarity names.

**Comment by giordano** [comment]
Related to this issue, today we had https://github.com/JuliaPackaging/Yggdrasil/pull/680, for `libsharp`, but there is already `libsharp2` (https://github.com/JuliaPackaging/Yggdrasil/pull/607), which is a different version of the same library or something like that.

I know that getting things like this is a bit tricky, but it would save time to users.
