### ISSUE TITLE
Overhaul of sources and dependencies

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/BinaryBuilder.jl#634]
Currently, sources can be specified in this form:
```julia
sources = [
    "https://example.org/source.tar.gz" => "0123456789abcdf0123456789abcdf0123456789abcdf0123456789abcdf",
    "http://example.org/repo.git" => "0123456789abcdf0123456789abcdf0123456789",
    "./local-dir",
]
```
I propose to define an abstract type `AbstractSource`, with the following subtypes:
```julia
struct FileSource <: AbstractSource
    url::String
    hash::String
end

struct GitSource <: AbstractSource
    url::String
    hash::String
end

struct DirectorySource <: AbstractSource
    path::String
end
```
The benefit would be more Julian code, [`download_sources`](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/2eec6a4437f666760a263a7dc3ecc5d4110f5e5d/src/AutoBuild.jl#L349-L425) would be much cleaner, with less trial-and-error to guess the type of the source, and better error	messages (#588 was mostly due to the fact that we don't exactly know what the source should be, so the message is very general and vague).

Currently dependencies are of the type
```julia
dependencies = [
    "HelloWorld_jll",
    PackageSpec(name="Ncurses_jll", uuid="68e3532b-a499-55ff-9963-d1c0c0748b3a")
]
```
However, there is a strong desire for having compile-time-only dependencies (e.g., see https://github.com/JuliaPackaging/Yggdrasil/issues/321).  I propose, similarly to the sources above, to have an abstract type `AbstractDependency`, with subtypes:
```julia
struct Dependency{T<:Union{PkgSpec,String}} <: AbstractDependency
    pkg::T
end

struct CompileDependency{T<:Union{PkgSpec,String}} <: AbstractDependency
    pkg::T
end
```
They are basically equivalent to current dependencies, with the exception that a `CompileDependency` would not be added to the list of dependencies of the generated JLL package.  For example, there are many Xorg JLL packages that actually contain only header files and are needed only at compile time, not to actually load the libraries.  Given the fact that the `artifact"..."` macro is not super efficient, being able to remove these packages from the runtime dependencies of Julia packages would also slightly alleviate the problem of loading times.

**Comment by staticfloat** [comment]
Looks good to me; let's roll in some other options that are useful as well; for instance, we should support optional `unpack_target` options for all our sources; it should default to `""`, but if we specify it, the sources should be unpacked into `${WORKSPACE}/srcdir/${unpack_target}`.
