### ISSUE TITLE
Automatic MIT licensing

### ISSUE THREAD

**Issue by pabloferz** [JuliaPackaging/BinaryBuilder.jl#635]
It seems that currently [BB automatically assigns a MIT licenses](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/2eec6a4437f666760a263a7dc3ecc5d4110f5e5d/src/AutoBuild.jl#L1261-L1271) to jll packages.

It may be wise to avoid this or to give the user the option to at least opt-in if it is known that the jll package will be MIT compatible.

**Comment by staticfloat** [comment]
So the MIT license bundled with the JLL packages is supposed to apply to the actual JLL code itself, since it comes from an MIT-licensed program (BinaryBuilder.jl).

After discussing this with our resident licensing expert, I think we're going to take the following steps:

* Relicense the auto-generated wrapper code under CC0 (essentially putting it out there as public domain).

* Alter the autogenerated `LICENSE.md` to make it explicit that the CC0 applies only to the Julia source code within `src/`, and that the JLL package will download artifacts that may contain their own licenses.  Each JLL should be shipping with a license within it located in `share/licenses/${src_name}`.

* Extract metadata about the build and store it in plain format within the JLL package itself.  For the purposes of this issue, I'm thinking just the licenses and source locations are important, but I'm opening another issue to track other things we might want to store: https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/639

**Comment by pabloferz** [comment]
OK. I like the idea. That way it would be much clearer what is going. And sourcing licenses and URLs seems enough to avoid issues with GPL licenses.

**Comment by stevengj** [comment]
> Relicense the auto-generated wrapper code under CC0 (essentially putting it out there as public domain).

Have you read CC0?  It's way more complicated than the MIT license: https://creativecommons.org/publicdomain/zero/1.0/legalcode

Much easier to just use the MIT license, which has essentially the same effect as being in the public domain and is compatible with all other licenses.

**Comment by pabloferz** [comment]
That is a good point. I still think the other two points proposed by Elliot are worth implementing.

**Comment by StefanKarpinski** [comment]
May I suggest the [ISC license](https://en.wikipedia.org/wiki/ISC_license)? It’s similar to MIT but without and advertising or attribution clauses, which is very minimal.

**Comment by stevengj** [comment]
(The MIT license has no advertising clause—you're thinking of 4-clause BSD.)   ISC seems fine, but I would stick with the functionally equivalent MIT license simply because that's so widely used in the Julia package ecosystem, and license proliferation is confusing.

**Comment by StefanKarpinski** [comment]
I was thinking of the original BSD license / the MIT X11 license. Sticking with MIT seems fine.

**Comment by stevengj** [comment]
CC0 is hugely complicated because there is no uniform way to put things in "public domain".   It's not clear what problem that solves here compared to the [MIT license (aka "expat license")](https://opensource.org/licenses/MIT).

**Comment by StefanKarpinski** [comment]
Dual licensing means that either one can be used, so any complexity of CC0 can be ignored if one prefers. I think the idea behind CC0 is to try to minimize the potential conflict that there could be with _any_ usage of the code. For example, MIT technically requires keeping the copyright notice with the copyright holder's name, whereas CC0 means you can just take the code and use it anywhere and not bother with any license file at all.

**Comment by stevengj** [comment]
I know what dual licensing means, but I doubt the utility of including a complicated CC0 statement and then telling people to ignore it — the mere fact of including it is still a complication.  Nor do I think it's a good idea to encourage people to re-use code without propagating a clear statement of the code's origins and copyright status.

**Comment by giordano** [comment]
I addressed some of the points in #794: the new text of the license points out that it applies only to the JLL package and the wrapped package will have its own license.

**Comment by giordano** [comment]
@pabloferz the discussion diverged from what you initially proposed here.  You can see the new version of the license file for example in [`OpenSSH_jll`](https://github.com/JuliaBinaryWrappers/OpenSSH_jll.jl/blob/dbbbe180d31f9d91ad84575f3ef57d4a8f983fec/LICENSE).  Do you think this is a  good solution or you believe that we should still allow the user to choose a different license?

**Comment by pabloferz** [comment]
To me the most important issue was to address this point summarized by Elliot:

> Alter the autogenerated LICENSE.md to make it explicit that the [CHOOSEN LICENSE] applies only to the Julia source code within src/, and that the JLL package will download artifacts that may contain their own licenses. Each JLL should be shipping with a license within it located in share/licenses/${src_name}.

(which #794 solves)

Initially I had thought of considering another license, but given the discussion above I do not have a strong opinion on changing MIT as the default or giving user the option to choose another. I believe we can close this, unless someone else feels this needs to be further discussed.

**Comment by giordano** [comment]
Ok, I'm going to close the issue, thanks everybody for the discussion!
