### ISSUE TITLE
sorry - this program has been built without plugin support

### ISSUE THREAD

**Issue by recri** [JuliaPackaging/BinaryBuilder.jl#653]
Building a binary for libportmidi failed making a (probably unnecessary) static archive
```
[ 23%] Linking C static library /Release/libportmidi_s.a
cd /workspace/srcdir/build/pm_common && /usr/bin/cmake -P CMakeFiles/portmidi-static.dir/cmake_clean_target.cmake
cd /workspace/srcdir/build/pm_common && /usr/bin/cmake -E cmake_link_script CMakeFiles/portmidi-static.dir/link.txt --verbose=false
sorry - this program has been built without plugin support
```
Googling that last line brings up a who's cross-compiling catalog.  It's the message `binutils` drops when configured without `--enable-plugins`.  The link script that failed was essentially `ar qc $LIB $OBJ && ranlib $LIB`, and running `ar` alone throws the error.
Same error message as reported and fixed in #614 and #615.

**Comment by staticfloat** [comment]
What version of `BinaryBuilder` are you using?  https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/615 is not in a release yet, it's only on `#master`.  Can you submit a PR to [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil/) for us all to take a look at, or try on `BinaryBuilder#master`?

**Comment by recri** [comment]
I was using version"0.2.2", I will try `BinaryBuilder#master` and report what happens.

**Comment by giordano** [comment]
@recri any news?

**Comment by recri** [comment]
This is no longer an issue when using BinaryBuilder#master.
