### ISSUE TITLE
Symlinks generated with builder paths

### ISSUE THREAD

**Issue by samuelpowell** [JuliaPackaging/BinaryBuilder.jl#672]
The [JLL tarballs](https://github.com/JuliaBinaryWrappers/libftd2xx_jll.jl/releases) resulting from the build of [libftd2xx](https://github.com/JuliaPackaging/Yggdrasil/tree/master/L/libftd2xx) has the following contents on Linux:

```
Samuels-MBP:lib spowell$ ls -al
total 592
drwxr-xr-x@ 4 spowell  staff     128 13 Feb 18:24 .
drwxr-xr-x@ 6 spowell  staff     192 14 Feb 17:38 ..
lrwxrwxrwx@ 1 spowell  staff      91 13 Feb 18:24 libftd2xx.so -> /agent/_work/1/s/L/libftd2xx/build/x86_64-linux-gnu/7srSa96K/destdir/lib/libftd2xx.so.1.4.8
-r-xr-xr-x@ 1 spowell  staff  299695 13 Feb 18:24 libftd2xx.so.1.4.8
```

I assume the symlink was created by BB during location of the binary outputs, evidently this causes a problem when trying to load the library!

**Comment by giordano** [comment]
Done :wink:

**Comment by samuelpowell** [comment]
Wow, I didn't even know that was possible

**Comment by giordano** [comment]
My understanding is that the file `libftd2xx.so.1.4.8` has the soname set to `libftd2xx.so`, but the tarball contains only `libftd2xx.so.1.4.8`, which is...

One possible fix is to manually set in the builder the soname of `libftd2xx.so.1.4.8` to itself with `patchelf`, another more general solution is to fix the function `symlink_soname_lib` to not create links with a wrong target, which is done in #674.
