### ISSUE TITLE
Entering product names is annoying

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#677]
Particularly if there are many products. We should try to heuristically suggest a good name (e.g. the executable name for the executable and the library name without `lib` for libraries).

**Comment by giordano** [comment]
The easy part is guessing a default name: we can use `parse_dl_name_version` from `Pkg.BinaryPlatforms` for the libraries:
```julia
replace(parse_dl_name_version(libname, platform)[1], "-" => "_")
```
and `splitext` for the executables:
```
replace(splitext(exename)[1], "-" => "_")
```

The hardest part is to change `nonempty_line_prompt` to accept a default answer in the command line that a user can edit if necessary

**Comment by Keno** [comment]
I have a patch for this. Just need to get through my patch stack.
