### ISSUE TITLE
Lower Glibc version for PowerPC to 2.17

### ISSUE THREAD

**Issue by vchuravy** [JuliaPackaging/BinaryBuilder.jl#694]
Several PPC systems in the wild use RHEL 7.6, which will use glibc v2.17.
@staticfloat you mentioned that you choose 2.25 because it was the only one you got to reliably built?

**Comment by staticfloat** [comment]
Yes, I had a very difficult time building gcc (across all versions) against glibc v2.17.

**Comment by giordano** [comment]
Fixed by https://github.com/JuliaPackaging/Yggdrasil/pull/592 and #705
