### ISSUE TITLE
Repos are tagged and releases uploaded _before_ a commit is made with the Artifact.toml file containing corresponding hashes

### ISSUE THREAD

**Issue by kdheepak** [JuliaPackaging/BinaryBuilder.jl#709]
For example, [this release](https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/releases/tag/HELICS-v2.4.1%2B1) was tagged on the commit https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/commit/5ba0bd549d80a6822516438c4d63080818ac33b9. And then presumably hashes were calculated for the files and added to the Artifacts.toml file to the repository in a separate commit: https://github.com/JuliaBinaryWrappers/HELICS_jll.jl/commit/463513c20a822ec6650db3470e89f71b4251e769. 

Ideally, the tag release would be made after the commit is made with the hashes for all the files that are to be uploaded.

<img width="1000" alt="Screen Shot 2020-03-11 at 2 35 08 PM" src="https://user-images.githubusercontent.com/1813121/76461437-84fabd00-63a5-11ea-861b-202083607d1b.png">

Currently, github shames us with the "1 commit to master since this release" message.

**Comment by giordano** [comment]
Fixed by #https://github.com/JuliaPackaging/Yggdrasil/pull/2044
