### ISSUE TITLE
error building package in julia 1.4

### ISSUE THREAD

**Issue by hros** [JuliaPackaging/BinaryBuilder.jl#718]
in Ubuntu 18.04 and Julia 1.4
```
julia> using BinaryBuilder
[ Info: Precompiling BinaryBuilder [12aac903-9f7c-5d81-afc2-d9565ea332ae]
ERROR: LoadError: LoadError: LoadError: UndefVarError: Compress not defined
```

**Comment by giordano** [comment]
You need to have at least `Registrator.jl` v1.1, just updating it should to the trick.  What version of `BinaryBuilder.jl` are you using?  The correct lower bound for `Registrator.jl` was put in #717.

**Comment by fredrikekre** [comment]
Looks like there was never a release: https://github.com/JuliaPackaging/BinaryBuilder.jl/commit/2ba10a23de173b6b38bf3c7236ac739504c96888#commitcomment-37979662

**Comment by hros** [comment]
@giordano 
Registrator raises the same error with Julia 1.4
Btw, everything still works in Julia 1.3

**Comment by hros** [comment]
after recent update, things are working again
registrator v1.1.0
binarybuilder v0.2.4

**Comment by giordano** [comment]
Thanks for confirmation!
