### ISSUE TITLE
newer gcc versions ?

### ISSUE THREAD

**Issue by j-fu** [JuliaPackaging/BinaryBuilder.jl#720]
Hi, I am trying to cross-compile a part of vtk. 
On  i686-linux-gnu I am getting stuck with:
```
/workspace/srcdir/VTK-9.0.0.rc1/Common/DataModel/vtkExtractStructuredGridHelper.cxx: In static member function ‘static void vtkExtractStructuredGridHelper::GetPartitionedVOI(const int*, const int*, const int*, bool, int*)’:
/workspace/srcdir/VTK-9.0.0.rc1/Common/DataModel/vtkExtractStructuredGridHelper.cxx:541:6: internal compiler error: in vect_analyze_data_ref_accesses, at tree-vect-data-refs.c:2597
 void vtkExtractStructuredGridHelper::GetPartitionedVOI(const int globalVOI[6],
      ^
0x55adefe75999 vect_analyze_data_ref_accesses(_loop_vec_info*, _bb_vec_info*)
        /workspace/srcdir/gcc-5.2.0/gcc/tree-vect-data-refs.c:2597
0x55adefa35bfe vect_slp_analyze_bb_1
        /workspace/srcdir/gcc-5.2.0/gcc/tree-vect-slp.c:2287
0x55adefa35bfe vect_slp_analyze_bb(basic_block_def*)
        /workspace/srcdir/gcc-5.2.0/gcc/tree-vect-slp.c:2434
0x55adefa37d23 execute
        /workspace/srcdir/gcc-5.2.0/gcc/tree-vectorizer.c:722
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
```
It probably is not a good idea to bother the gcc guys with an error in an older version, so is it possible to use a newer compiler version in BinaryBuilder ?

**Comment by vchuravy** [comment]
Absolutely you can set:

```
build_tarballs(ARGS, configure_build(ARGS, version)...;
                     preferred_gcc_version=v"7", preferred_llvm_version=v"8")
```

And I recall seeing the wizard asking if you wanted to select a preferred compiler version.

**Comment by giordano** [comment]
These are the GCC version that you can use in the BB environment: https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/e53faa3629eebd9492a91cea1132e7da6599ea83/src/Rootfs.jl#L343-L348  And I confirm that if you're using the wizard, it'll ask you if you want to use a different set of compilers

**Comment by j-fu** [comment]
Ah thanks, great!
... well the wizard would get a bit overwhelmed here (or may be it's my ignorance...):
https://github.com/j-fu/YggBonsai/blob/master/V/VTKMinimal/build_tarballs.jl
