### ISSUE TITLE
aarch64-linux-gnu-g++ :  exec format error 

### ISSUE THREAD

**Issue by j-fu** [JuliaPackaging/BinaryBuilder.jl#721]
Hi, I am compiling a project which needs some setup tools to be generated before compiling the lib.  
Works well for standard inux  x86_64 and i686, but I got stuck on aarch64-linux .

Here is an mwe of what is essentially  happening and the info about the tools. 

````
sandbox:${WORKSPACE}/srcdir/build # cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.9.0
PRETTY_NAME="Alpine Linux v3.9"
````
````
sandbox:${WORKSPACE}/srcdir/build # cat hello.cxx 
#include <cstdio>
int main()
{
        printf("hello world\n");
        return 0;
}
````
````
/opt/bin/c++ -v
Using built-in specs.
COLLECT_GCC=/opt/aarch64-linux-gnu/bin/aarch64-linux-gnu-g++
COLLECT_LTO_WRAPPER=/opt/aarch64-linux-gnu/bin/../libexec/gcc/aarch64-linux-gnu/9.1.0/lto-wrapper
Target: aarch64-linux-gnu
Configured with: /workspace/srcdir/gcc-9.1.0/configure --prefix=/workspace/destdir --target=aarch64-linux-gnu --host=x86_64-linux-musl --build=x86_64-linux-musl --disable-multilib --disable-werror --enable-shared --enable-host-shared --enable-threads=posix --with-sysroot=/workspace/destdir/aarch64-linux-gnu/sys-root --program-prefix=aarch64-linux-gnu- --disable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++
Thread model: posix
gcc version 9.1.0 (GCC) 
````
````
sandbox:${WORKSPACE}/srcdir/build # /opt/bin/c++  hello.cxx  -o hello
sandbox:${WORKSPACE}/srcdir/build # ./hello 
bash: ./hello: cannot execute binary file: Exec format error
````

**Comment by giordano** [comment]
We can't run foreign executables: https://github.com/JuliaPackaging/Yggdrasil/wiki/Build-Tricks#running-foreign-executables

**Comment by j-fu** [comment]
Well, then catch 22 here: https://gitlab.kitware.com/vtk/vtk/-/issues/17821

**Comment by giordano** [comment]
It's not clear to me what's happening, but a build system that tries to execute a program is not very cross-compilation-friendly...

**Comment by j-fu** [comment]
... well, kitware are the masters to the cmake empire... 

When cross-compiling (detected by specifying a toolchain file) they need to have some wrapper tools created before. I deliberately tried to tick of all python, java etc wrapping to stay clean here, but this didn't help.
... I guess with mingw and macos we will run into the same issue...

**Comment by mathstuf** [comment]
I'll take a look at disabling all wrapping support in a VTK build. That should remove the need for any host tools.

**Comment by mathstuf** [comment]
Note that this will not work for ParaView if you ever want that; it wraps things into its "ClientServer" world and it's just fundamental to how it works.

**Comment by j-fu** [comment]
... wouldn' t it be possible to provide  another C  compiler  just for  building the tools ?

**Comment by j-fu** [comment]
> I'll take a look at disabling all wrapping support in a VTK build. That should remove the need for any host tools.

Sounds great!

**Comment by j-fu** [comment]
> Note that this will not work for ParaView if you ever want that; it wraps things into its "ClientServer" world and it's just fundamental to how it works

Paraview is not part of the plan here. In fact I'd like to figure out to work with ParaView catalyst here if  time permits. But this then should work with what ever paraview installation comes for the respective system.

**Comment by giordano** [comment]
For the record, the native compilers, to compile native programs that can be run on the build system, are available in the `*_FOR_BUILD` environment variables, as it is standard in autotools: `${CC_FOR_BUILD}`, `${CXX_FOR_BUILD}`, etc...

**Comment by j-fu** [comment]
> For the record, the native compilers, to compile native programs that can be run on the build system, are available in the `*_FOR_BUILD` environment variables, as it is standard in autotools: `${CC_FOR_BUILD}`, `${CXX_FOR_BUILD}`, etc...

Ok I'll give it a try tonight.

**Comment by mathstuf** [comment]
Please give https://gitlab.kitware.com/vtk/vtk/-/merge_requests/6648 a try.

**Comment by j-fu** [comment]
> For the record, the native compilers, to compile native programs that can be run on the build system, are available in the `*_FOR_BUILD` environment variables, as it is standard in autotools: `${CC_FOR_BUILD}`, `${CXX_FOR_BUILD}`, etc...

This works when using them as CC and CXX for the precompilation step, but there is good hope now that we get the real thing from vtk.

**Comment by j-fu** [comment]
> Please give https://gitlab.kitware.com/vtk/vtk/-/merge_requests/6648 a try.

I think this is going to work now. Fortunately it seems it was the right time during release candidate phase...

**Comment by mathstuf** [comment]
We can't fix things we don't hear about. RC testing helps us avoid lots of things in .1 patch releases :) . Thanks again for testing.
