### ISSUE TITLE
Have the wizard warn if a package already exists 

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#746]
It's happened more than once that somebody made a PR to yggdrasil that contained a package that we already had. It would be good for the Wizard to check that this doesn't happen. It could check both the name that the user chose and the URL to make sure we don't already have them.

**Comment by giordano** [comment]
Duplicate of #631

**Comment by Keno** [comment]
We've had a longstanding policy in julia that if an issue gets reported three independent times, it gets fixed ;). One more time to go.
