### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/BinaryBuilder.jl#75]
We need to provide documentation (probably as wiki pages on this repository) for:

* [ ] Building Binaries (a Wizard Walkthrough, as it were)
* [ ] Setting up autobuilders on Travis
* [ ] Integrating the new `build.jl` into your Package

Bonus pages:

* [ ] Adding a new build shard for a new architecture

**Comment by Keno** [comment]
> probably as wiki pages on this repository

I'd much rather just have regular markdown files in a doc/ folder
