### ISSUE TITLE
Evaluate other CI services

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/BinaryBuilder.jl#751]
Lately, we're having some troubles with CI in Travis, because we're frequently getting the error
```
curl: (22) The requested URL returned error: 429 too many requests
```
when downloading artifacts.  I'm opening this issue to collect ideas about a possible alternative for running CI of this package

### Pros

* we're already using it, worked fine until a few weeks ago

### Cons

* we're experiencing problems with download of artifacts
* ideally, we could use cache to avoid downloading stuff, but in #646 we got very dangerously close to the 50-minute wall

### Pros

* 6-hour wall time for free, with 20 concurrent jobs ([source](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits))

### Cons

* I ported current Travis setup of BinaryBuilder to GitHub Actions, but many jobs failed with an error like the following during download:
  ```
  curl: (23) Failed writing body (3732 != 16360)
  ```
  Not a great improvement over the current failure in Travis
* [14 GiB of space on disk](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources).   All jobs that didn't fail during download crashed with a
  ```
  System.IO.IOException: No space left on device
  ```
  error.

* The total cache size for a repository is [5 GiB](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy).  Using cache is not an option

Note that an option to overcome the 14 GiB limitation could be to split the tests into multiple jobs.

### Pros

* 6-hour wall time for free, with 10 concurrent jobs ([source](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops#microsoft-hosted-cicd))
* [There is no enforced limit on the size of individual caches or the total size of all caches in an organization](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#is-there-a-limit-on-the-size-of-a-cache)

### Cons

* ["at least 10 GiB of storage"](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#capabilities-and-limitations).  Since they use basically the same runners as GitHub Actions, the storage is likely about the same.

**Comment by Keno** [comment]
> * we're experiencing problems with download of artifacts

Perhaps it's time to include the artifacts in our S3 cache as we have with Julia itself? @staticfloat ?

**Comment by staticfloat** [comment]
Downloading from cache-local servers should be transparently solved by using Pkg Servers.  We should define `JULIA_PKG_SERVER=https://geo.pkg.julialang.org`.  We don't yet have pkg servers sitting in all the warehouses of the world, but we will one day, and we can prioritize serving Azure/Travis/wherever this ends up being hosted if it's a problem.

**Comment by giordano** [comment]
We switched to Azure Pipelines in #918
