### ISSUE TITLE
qemu: can't create libtool: Interrupted system call

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#76]
In the (not yet merged or PR'ed) qemu based runner, we occasionally see:
```
can't create libtool: Interrupted system call
```
This issue exists primarily to document my findings investigating this and so
I get to feel good about closing an issue for all the work I've put in.

For background, in the qemu runner, the workspace is mounted using the 9p
protocol running off of [qemu's built-in 9p server](https://github.com/qemu/qemu/tree/master/hw/9pfs) and the linux kernel's built-in client.

What's happening in this situation is something like the following:
1. BusyBox `sh` tries to open a file via 9pfs
2. The [p9_client_rpc](https://github.com/torvalds/linux/blob/5a787756b809888e8925d722862167f1229b58f7/net/9p/client.c#L749) function sends that request to the server and switches tasks
3. A child dies and sends SIGCHLD to `sh`
4. The process wakes up and decides to cancel the request
5. The server receives both the request and the cancellation request and processes them accordingly
6. The linux kernel passes any errors back to userspace (potentially setting up a restart if the error was ERESTARTSYS)

Now, there's many issues here, so let me look at each of them in turn:

1. The linux kernel cancelling the request. This isn't incorrect, but it's a quirk of network file systems that user space applications are often not equipped to handle. Now, as it turns out, just a few months ago @dezgeg (apologies for the ping, but I figured you might be interested in this analysis) landed https://github.com/torvalds/linux/commit/9523feac272ccad2ad8186ba4fcc89103754de52 which switches that to wait_event_killable, which should no longer cause a cancellation request (cross ref https://github.com/NixOS/nixpkgs/issues/23957, which I believe was the catalyst). This will fix this issue, but on the other hand I believe it'll also rr on 9p file systems, so that's a bit of a double edged sword.

Now for what I believe the real bug is:
2. QEMU doesn't handle cancellation requests properly. The [9p spec](https://9fans.github.io/plan9port/man/man9/flush.html) says: 
```
The server should answer the flush message immediately. If it recognizes oldtag as the tag of a pending transaction, it should abort any pending response and discard that tag. In either case, it should respond with an Rflush echoing the tag (not oldtag) of the Tflush message. A Tflush can never be responded to by an Rerror message.
```
However, qemu doesn't do that. Instead, it records the abort as requested, but then replies with an EINTR message to the `oldtag` message, causing the kernel to relay that error back to userspace, instead of the ERESTARTSYS that it would regularly have passed to user space. **This causes EINTR to appear even for users that have SA_RESTART set** which really, really shouldn't happen. For those that didn't follow the above discussion it goes something like this:
```
Client: Hey, I'd like to open that file
Client: Actually never mind, cancel that
Server cancels operation
Server: Oh hey your original request is done, it failed, tell the user it was an EINTR
Server: Hey I'm done cancelling your request
Client (thinks): Oh cool the request went through to completion even though I tried
to cancel it, let's return it's error result to the user.
```

I have a patch for qemu to fix this. Unfortunately that brings us to

3. Busybox `sh` doesn't set SA_RESTART and doesn't check for EINTR in enough places. For reasons, busyboxes' shell implementation depends on not setting SA_RESTART. However, they don't check for EINTR either, so even absent bug #2, we run into trouble here.

My rough plan is to bump our kernel version to pick up the 9p change, which should fix the immediate issue and also send in my qemu patch. I'll also look whether I can get some changes into busybox to make it more reliable in the face of EINTR, but not sure how successful I'll be at that.

**Comment by staticfloat** [comment]
🐑 ✂️ 💯

**Comment by staticfloat** [comment]
To expand on this a bit more, this unfortunately seems like still the best way forward.  I really appreciate your tenacity in tackling these "deep slice" problems, and I'm just glad that we have a system that "works" even without this, so that the pressure isn't directly on you right now with regards to getting this working.

In your hypothetical system, do we tell users "Run `brew install qemu` and this will 'just work'"?

**Comment by Keno** [comment]
I'm pretty sure this the last of the file system issues.

> In your hypothetical system, do we tell users "Run brew install qemu and this will 'just work'"?

We need patches (I'll submit them upstream, but it'll take a while). If only we had some sort of system for building and downloading binaries ;).

**Comment by staticfloat** [comment]
>  If only we had some sort of system for building and downloading binaries ;)

🐶 🥘 💯

**Comment by Keno** [comment]
qemu patch is in the pipes: https://marc.info/?l=qemu-devel&m=151224928710201&w=2

**Comment by Keno** [comment]
Confirmed fixed by bumping the kernel version. I've also submitted an RFC edit to the man pages to suggest that EINTR should be documented as being a valid return value from stat(). If that goes through, I'll talk to busybox.

**Comment by dezgeg** [comment]
How is EINTR a valid return value for stat()? It was a bug in the kernel 9p driver that caused those.

**Comment by Keno** [comment]
I'm not sure whether it's a valid return value, which is why I sent that email to get some clarification from the kernel developers (as an open source maintainer putting something incorrect in the documentation is often the most assured way to get my attention ;)). If I understand the history correctly EINTR is documented as a valid return value in SVr4, but not by POSIX. It also used to be allowed by BSD, but then they added mandatory syscall restarts. What I want from the kernel developers is to tell me what the ABI contract here is. I was under the impression that the kernel was allowed to EINTR a stat call (I've seen this behavior before for other network file systems on HPC clusters - I also remembered the nfs intr option that appears to be deprecated); I'll be most happy to get a definite statement either way. If it's illegal, I'll know for next time I see it and can immediately jump to debugging the file system or complaining to the HPC system vendor.
