### ISSUE TITLE
Two license files per JLL?

### ISSUE THREAD

**Issue by fingolfin** [JuliaPackaging/BinaryBuilder.jl#792]
I am not sure whether this is the right place for this issue, but...

It seems that JLLs are created with TWO license files; `LICENSE` and `LICENSE.md`; see e.g. <https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl>. This is somewhat confusing.

The `LICENSE` file is added as part of the "initial commit" which has only this file and nothing else. And `LICENSE.md` is added by BinaryBuilder.

**Comment by giordano** [comment]
For reference https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/660
