### ISSUE TITLE
Stable documentation is stuck in v0.0.4

### ISSUE THREAD

**Issue by felipenoris** [JuliaPackaging/BinaryBuilder.jl#801]
https://juliapackaging.github.io/BinaryBuilder.jl/stable/

**Comment by giordano** [comment]
I hope this had been fixed by #783, we'll find out with the next release if this worked

**Comment by giordano** [comment]
I confirm https://juliapackaging.github.io/BinaryBuilder.jl/stable/ now points to the latest stable version
