### ISSUE TITLE
Disable Issues in JuliaBinaryWrapper package repos

### ISSUE THREAD

**Issue by aviks** [JuliaPackaging/BinaryBuilder.jl#819]
There are hundreds of those, and it seems like a waste of effort to follow. We should instead have a pointer in the README to open issues on Yggdrasil?

**Comment by giordano** [comment]
> There are hundreds of those, and it seems like a waste of effort to follow.

I agree, but I don't know if it's possible to disable them via GitHub API.  Anyway I follow (almost) all repos in the organisation.

> We should instead have a pointer in the README to open issues on Yggdrasil?

That's probably a good idea

**Comment by aviks** [comment]
>I don't know if it's possible to disable them via GitHub API

The `repos` POST API call seems to have a `has_issues` parameter:  https://developer.github.com/v3/repos/#create-an-organization-repository

Probably disable wikis and projects as well. 

>  I follow (almost) all repos

Yeah, don't. I'm sure there are better ways to spend your time 🤣
