### ISSUE TITLE
Unable to run unprivileged containers on this system

### ISSUE THREAD

**Issue by Moelf** [JuliaPackaging/BinaryBuilder.jl#839]
```
 Warning: Unable to run unprivileged containers on this system! This may be because your kernel does not support mounting overlay filesystems within user namespaces. To work around this, we will switch to using privileged containers. This requires the use of sudo. To choose this automatically, set the BINARYBUILDER_RUNNER environment variable to "privileged" before starting Julia.
```

the provided alternative doesn't work as later:
```
mount: permission denied (are you root?)
sandbox:${WORKSPACE}/srcdir # ls
```
and
```
ERROR: The build has produced no binary artifacts.
```

**Comment by giordano** [comment]
What operating system is that?


> the provided alternative doesn't work as later:
> ```
> mount: permission denied (are you root?)
> sandbox:${WORKSPACE}/srcdir # ls
> ```
> 

When does this happen?  In the wizard?  If so, that's a known non-fatal error, it means you can't use the automatic diff feature within the wizard: https://github.com/JuliaPackaging/BinaryBuilder.jl/commit/e242bd44baa03bbdc0929caf65b4bd669e0f513b#r37525934

> and
> ```
> ERROR: The build has produced no binary artifacts.
> ```

Are you sure your build script installed any file in the `${prefix}`?

**Comment by Moelf** [comment]
> What operating system is that?

I read the conversation, indeed I am on Arch.

however, for example building `neofetch` with script:
```
	cd $WORKSPACE/srcdir
	cd neofetch-6.1.0/
	export PREFIX=$prefix
	make install
```
and check:
```
sandbox:${WORKSPACE}/srcdir # ls /workspace/destdir/bin/
neofetch
```

but still
`The build has produced no binary artifacts.`

**Comment by giordano** [comment]
That's because you've chosen a particular software: neoftech install only a bash script and the wizard doesn't support non-binary executables.  Note also that neofetch is already in Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/pull/367

**Comment by Moelf** [comment]
yeah I was testing neofetch as an example, trying to build fzf

**Comment by giordano** [comment]
Well, yeah, you've been very luck with your test case, that's like the only case out of 400+ builders that has a bash script in `bin/` as product

**Comment by Moelf** [comment]
oof, ok, for fzf, looks like the issue was that it doesn't use `PREFIX`, is it ok if I just manually move `bin`?

**Comment by giordano** [comment]
I see `fzf` is in written in Go, you should rather look to something like [`ghr`](https://github.com/JuliaPackaging/Yggdrasil/blob/c9f8eb3897a8e1ded875a60b24d709e8afdf35a7/G/ghr/build_tarballs.jl)

**Comment by Moelf** [comment]
they do have a `MAKEFILE` so I was using that https://github.com/junegunn/fzf/blob/master/BUILD.md

**Comment by giordano** [comment]
Try using `make` and manually move the file to `${bindir}/fzf${exeext}` at the end, but in my limited experience with building go packages in BinaryBuiler the three lines of the `ghr` example always work

**Comment by giordano** [comment]
I think this can be closed now?
