### ISSUE TITLE
runshell on arch linux has a premission problem.

### ISSUE THREAD

**Issue by simonschoelly** [JuliaPackaging/BinaryBuilder.jl#852]
When I want to run `BinaryBuilder.runshell`, I can only do this by setting an environment variable like this `env BINARYBUILDER_RUNNER="privileged" julia`. Was told this should not be the case and I should open an issue with some information on my system. So for julia it is:

```julia
julia> versioninfo()
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = gvim
```

```bash
➜  ~ uname -a
Linux simonstp5G 5.7.10-arch1-1 #1 SMP PREEMPT Wed, 22 Jul 2020 19:57:42 +0000 x86_64 GNU/Linux
```

```bash
➜  ~ archey3

               +                OS: Arch Linux x86_64
               #                Hostname: simonstp5G
              ###               Kernel Release: 5.7.10-arch1-1
             #####              Uptime: 1:24
             ######             WM: i3
            ; #####;            DE: None
           +##.#####            Packages: 1935
          +##########           RAM: 4861 MB / 15499 MB
         #############;         Processor Type: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
        ###############+        $EDITOR: /usr/bin/gvim
       #######   #######        Root: 431G / 461G (93%) (ext4)
     .######;     ;###;`".      
    .#######;     ;#####.       
    #########.   .########`     
   ######'           '######    
  ;####                 ####;   
  ##'                     '##   
 #'                         `#  
```

Tell me, if I should provide more information

**Comment by giordano** [comment]
> When I want to run BinaryBuilder.runshell, I can only do this by setting an environment variable like this env BINARYBUILDER_RUNNER="privileged" julia.

Yes, I also use Arch Linux and that's the only way to use BinaryBuilder here because of some limitations of the kernel used by this distribution

> Was told this should not be the case

Not sure where this comes from, but unfortunately doesn't apply to Arch Linux :disappointed:

**Comment by fingolfin** [comment]
I think this can be closed because there is nothing we can do about it?

**Comment by vchuravy** [comment]
You can build a custom kernel with: https://aur.archlinux.org/cgit/aur.git/tree/ubuntu-unprivileged-overlayfs.patch?h=linux-userns

to support overlayfs.
