### ISSUE TITLE
Add a way to adjust the compat entry for Julia in JLL's `Package.toml`

### ISSUE THREAD

**Issue by fingolfin** [JuliaPackaging/BinaryBuilder.jl#856]
See also the discussion in issue #511.

In addition to the use case described there, this would also be useful for e.g. GMP.jl (see https://github.com/JuliaRegistries/General/pull/16517) and MPFR.jl (see @giordano's commit https://github.com/JuliaRegistries/General/pull/18342/commits/0495de0dc77381e6d0ccb791a0b28cfe09c26de6 in https://github.com/JuliaRegistries/General/pull/18342/commits).

**Comment by giordano** [comment]
For whoever wants to work on this, the function to look at is [`build_project_dict`](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/2bfca64a84bda4fa5d7535542d86c395e5bcfaf3/src/AutoBuild.jl#L1420-L1460).

**Comment by fingolfin** [comment]
I guess it would make sense to pass the Julia compat to `build_project_dict` via its existing `dependencies` argument.

Hmmm... how about adding a generic `RuntimeDependency` type, kinda dual to `BuildDependency`: it is only used to generate the `Project.toml` of the JLL but has no effect during build time. Then one could use this for Julia compat, but also for other things. Not that I have any good example in mind, so this may be pointless. However, it seems to be very easy to implement. 

One alternative is to add a new optional keyword argument to `build_tarball` which then has to be threaded through the code until it finally reaches `build_project_dict `. See also https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/511#issuecomment-634974371. That requires modifying quite a few places, and one also has to be careful to make sure it reaches `rebuild_jll_package`; all of this is "for free" if it was just another type of dependency.

**Comment by giordano** [comment]
While I agree `RuntimeDependency` can be useful in some situations (none that we've seen so far though), note that `julia` must be treated specially anyway: it won't go into the `deps` section of `Project.toml`, but only in `compat`, and even if not specified explicitly it must have a compat entry, supporting v1.0 by default.  So I don't think having `julia` as `RuntimeDependency` would be less work.

**Comment by giordano** [comment]
> While I agree `RuntimeDependency` can be useful in some situations (none that we've seen so far though)

There we go: https://github.com/JuliaPackaging/Yggdrasil/pull/2418#issuecomment-763536147
