### ISSUE TITLE
Weird warning for files whose name ends in "so" (but not ".so")

### ISSUE THREAD

**Issue by fingolfin** [JuliaPackaging/BinaryBuilder.jl#857]
When building a JLL which uses Ncurses_jll, one sees warnings like that:
```
##[warning]Could not probe /agent/_work/1/s/G/GAP/build/aarch64-linux-gnu-libgfortran4-cxx11/sjigd7D9/destdir/share/terminfo/c/cons60-iso for an SONAME!
```
My guess here is that some code somewhere assumes that all files whose name ends in "so" are shared libraries. If that's correct, that code ought to be changed to instead check for a suffix of ".so".

Alas, I couldn't find any code doing that, so perhaps my guess is completely wrong? But then why does it print this warning?

**Comment by giordano** [comment]
Oh, interesting guess, I've never got why the audit would care about those files in ncurses

**Comment by giordano** [comment]
This is [happening again](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=7583&view=logs&j=6763690b-af7d-5ec1-9460-9261172c1589&t=501a6578-5181-5fec-5b73-7450f7a11f0c&l=47852):
```
┌ Warning: Could not probe /agent/_work/1/s/E/eccodes/build/x86_64-linux-gnu/gGErUHBq/destdir/share/eccodes/definitions/mars/grib.waef.sot.def for an SONAME!
│   exception = (ObjectFile.MagicMismatch("Object file is not any of ObjectFile.ELF.ELFHandle, ObjectFile.MachO.MachOHandle, ObjectFile.COFF.COFFHandle! To force one object file format use readmeta(io, T)."), Union{Ptr{Nothing}, Base.InterpreterIP}[Ptr{Nothing} @0x00007f25a8eba473, Ptr{Nothing} @0x00007f259dede9b3, Ptr{Nothing} @0x00007f259dedefc9, Ptr{Nothing} @0x00007f259dee2277, Ptr{Nothing} @0x00007f259dee2e96, Ptr{Nothing} @0x00007f259dee2ef5, Ptr{Nothing} @0x00007f25e97997c9, Ptr{Nothing} @0x00007f25a8ebd18b, Ptr{Nothing} @0x00007f25a8ec0cff, Ptr{Nothing} @0x00007f25e97997c9  …  Ptr{Nothing} @0x00007f25e97997c9, Ptr{Nothing} @0x00007f25dbe63d30, Ptr{Nothing} @0x00007f25db93e9db, Ptr{Nothing} @0x00007f25db93eb55, Ptr{Nothing} @0x00007f25e97997c9, Ptr{Nothing} @0x00007f25e97f27f5, Ptr{Nothing} @0x00007f25e97f318c, Ptr{Nothing} @0x0000000000400b6e, Ptr{Nothing} @0x00007f25ea30109a, Ptr{Nothing} @0x0000000000400ba0])
└ @ BinaryBuilder.Auditor /depot/packages/BinaryBuilder/K52TD/src/auditor/soname_matching.jl:9
```

**Comment by fingolfin** [comment]
Weird. Just to double check: I assume Yggdrasil is always running the latest nightly Julia builds?

It's also strange because this filename doesn't even match the old regex that got fix in https://github.com/JuliaLang/julia/pull/37921:
```
julia> match(r"^(.*?)\.so((?:\.[\d]+)*)$", "grib.waef.sot.def") # new regex

julia> match(r"^(.*?).so((?:\.[\d]+)*)$", "grib.waef.sot.def") # old regex
```

**Comment by fingolfin** [comment]
OK, the bug is in valid_library_path -- I'll submit a PR
