### ISSUE TITLE
If my library doesn't link to a specific gfortran version but a dependent library does, do I need to `expand_gfortran_versions`?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaPackaging/BinaryBuilder.jl#860]

**Comment by giordano** [comment]
If your library doesn't depend on gfortran, you don't have to.

This is my workflow: I don't use `expand_gfrotran_versions` at the beginning, and then look at the output of the audit, if it suggests me to use `expand_gfortran_versions`, I'll do that.

**Comment by MikaelSlevinsky** [comment]
Thanks!
