### ISSUE TITLE
ln doesn't support --relative

### ISSUE THREAD

**Issue by bramtayl** [JuliaPackaging/BinaryBuilder.jl#862]
I was trying to build system.d and it looks like BinaryBuilder might be using an old version of ln?

**Comment by staticfloat** [comment]
We base our rootfs on Alpine, which uses `busybox` as the backing implementation for most of these core unix shell utilities.  It does not support `relative`.

If your build system requires it, you can install gnu coreutils via `apk add coreutils` at the beginning of your script, which will replace the default `ln` implementation with a much more fully-featured implementation.
