### ISSUE TITLE
Not finding existing products?

### ISSUE THREAD

**Issue by bramtayl** [JuliaPackaging/BinaryBuilder.jl#868]
This very well could just be me looking stupid, but I think maybe there might be an issue with product matching. Take the following two lines from the build logs of the ORC PR:

```
[ Info: Found a valid dl path liborc-0.4.so.0.31.0 while looking for liborc
[ Info: Could not locate liborc inside ["/agent/_work/1/s/O/ORC/build/i686-linux-gnu/1aBYoMrZ/destdir/lib"]
```

It seems like BinaryBuilder should be able to figure out that liborc-0.4.so.0.31.0 is liborc?

**Comment by giordano** [comment]
Where is the full log?

**Comment by bramtayl** [comment]
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=4651&view=logs&j=0a826bcf-2fff-59cb-eeb2-8bfe3f815915&t=ad383597-b3d1-574f-336c-0414047056aa does this link work?

**Comment by fingolfin** [comment]
I think the problem might be that this is a library named `liborc-0.4` and not `liborc` ?

**Comment by giordano** [comment]
Yes, the problem are libraries with actively borked file names

**Comment by giordano** [comment]
For the record, the [solution](https://github.com/JuliaPackaging/Yggdrasil/blob/392eccdea2ba2f7f8755eb3accf852a6c3f35567/O/ORC/build_tarballs.jl#L27-L32) was
```julia
products = [
    LibraryProduct(["liborc-test-0.4", "liborc-test-0"], :liborc_test),
    ExecutableProduct("orcc", :orcc),
    LibraryProduct(["liborc-0.4", "liborc-0"], :liborc),
    ExecutableProduct("orc-bugreport", :orc_bugreport)
]
```

**Comment by fingolfin** [comment]
Yeah that looks roughly like what I'd have expected :-)
