### ISSUE TITLE
Resolve libresov.so warning

### ISSUE THREAD

**Issue by aviks** [JuliaPackaging/BinaryBuilder.jl#878]
Very often, when I see warnings for :

` Linked library /usr/lib/libresolv.9.dylib could not be resolved and could not be auto-mapped`

It seems common enough that this probably should be handled in BB. I missed some relevant warnings due to the logs filled with this one.

**Comment by giordano** [comment]
Yes, there are many libraries that we should skip, especially for freebsd and macos

**Comment by staticfloat** [comment]
Fixed by https://github.com/JuliaPackaging/BinaryBuilder.jl/commit/c1913c5eafc4e2c220479894b2d47be9167a7307
