### ISSUE TITLE
Drop to environment after successful build

### ISSUE THREAD

**Issue by aviks** [JuliaPackaging/BinaryBuilder.jl#879]
With the `--debug` flag, running `build_tarballs.jl` will drop down into the cross compilation environment if the build fails. However, it does not do that when the build succeds, but audit fails. 

I often find myself adding a `false` statement to the end of the build script when trying to troubleshoot audit failures, or needing to inspect the built libraries for any other reason. As you'd expect, I've sometimes forgotten to remove it before making a PR. 

I think it would be useful to have a `--wait` (or some such) option to `build_tarballs.jl` to ensure that the build drops down to the cross environment even after a successful build.

**Comment by staticfloat** [comment]
Perhaps we can add kwargs to `--debug` so that `--debug` defaults to `--debug=error`, but we could also add `--debug=always` or something.

**Comment by staticfloat** [comment]
I also think the auditor needs to be better integrated, but that's a different issue altogether.

**Comment by giordano** [comment]
Fix in #907
