### ISSUE TITLE
[wizard] patch not saved to disk

### ISSUE THREAD

**Issue by aviks** [JuliaPackaging/BinaryBuilder.jl#885]
When I changed some build files while using the wizard, it correctly prompted to save a patch file with those changes. However, at the end I opted save the file to disk, rather than PR to Yggdrasil. Only the `build_tarball.jl` was saved to disk, the patch file was not saved. It was lost. 😢

**Comment by staticfloat** [comment]
wow, that is so sad.  Did your generated `build_tarballs.jl` have a `DirectorySource("./bundled")` but then not have a `patches` directory inside of it?

**Comment by staticfloat** [comment]
I think this should be fixed by https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/886, would be nice if you can confirm.
