### ISSUE TITLE
Add zst support for archives

### ISSUE THREAD

**Issue by musm** [JuliaPackaging/BinaryBuilder.jl#888]
Msys2 seems to have switched to zst compression format for newer built packages.  It would be good if we could get native zst extraction for `ArchiveSources` i.e. `.tar.zst`.  See https://github.com/facebook/zstd

**Comment by staticfloat** [comment]
Yeah, I like `zstd`.  The storage servers are all sneakily storing packages and artifacts as `zstd` compressed as well, in expectation of a future where we can download them via Pkg.  :)
