### ISSUE TITLE
False? negative produced no binary artifacts

### ISSUE THREAD

**Issue by bramtayl** [JuliaPackaging/BinaryBuilder.jl#895]
This is very likely me being stupid again. I'm trying to build `libatomic_ops` and configure, make, and make install all go smoothly. But when the wizard exits, it issues a warning about there being no binary products. I've put my (not working) attempt so far here https://github.com/JuliaPackaging/Yggdrasil/pull/1526

**Comment by staticfloat** [comment]
It's not a false negative, the recipe does indeed not have any binary products.  Further discussion in the PR.
