### ISSUE TITLE
Request regeneration of all JLLs (or at least related to QML, and Gtk), would indirectly help some plotting packages

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaPackaging/BinaryBuilder.jl#896]
A.
@barche I noticed how slow your QML (also Gtk similarily slow) is to load, tracked down to JLL loading slowly.

I already made a PR (https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/812/files) that shaves of a bit off loading time for each JLL, and they add up, already applied to at least one of your JLLs, but e.g. not:
https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/blob/master/src/Xorg_libxcb_jll.jl

In your case it should shave of some seconds in total, just by regenerating, as my PR adds these lines:

https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/blob/7b8434a49a98fe91edf16fdbba67a6e1d4cd0b28/src/jlqml_jll.jl#L3

I'm not sure what's involved, i.e. if you need to just push some button, or also fix your Project files.

Also FYI: Also https://juliahub.com/ui/Packages?q=QML doesn't work so I can see who use your package (and I'm not sure where to report this).

B.
@timholy Gtk.jl also is slow because of lots of JLLs, seems the main reason also (and why Tk.jl faster with fewer JLLs):

https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/blob/master/src/Cairo_jll.jl

C.
There's some stuff, maybe already merged on master, allowing improvements to my PR, and hen you would need to regenerate again, but for not this is the best you can do for Julia 1.5.

**Comment by barche** [comment]
> I noticed how slow your QML (also Gtk similarily slow) is to load, tracked down to JLL loading slowly.

Yes, we notice that even with CxxWrap, which just loads one JLL, thanks for this!

> I'm not sure what's involved, i.e. if you need to just push some button, or also fix your Project files.

The only way I know if is to commit a change with `[skip build]` in the commit message, but maybe there is a more elegant way to do this globally, @giordano ?


> Also FYI: Also https://juliahub.com/ui/Packages?q=QML doesn't work so I can see who use your package (and I'm not sure where to report this).

Not sure how long that site takes to update, but QML was only released during JuliaCon.

**Comment by timholy** [comment]
@staticfloat and others have some major improvements coming in JLL load performance in Julia 1.6. And of course 1.6 is already way better at package loading in general.

**Comment by PallHaraldsson** [comment]
>The only way I know if is to commit a change with [skip build] in the commit message

I'm not even sure where I would do that (and with git only, not in GitHub possible?), i.e. not at the wrapped packages themselves, as they are autogenerated. Additionally, I think you need to update Project files, so I think I need to leave this to you, and the fixing of the packages that have the JLLs as dependencies.

I'm using Julia 1.6 (not brand-new master), and people can't be relied on having that, even after release, so I think we should to the small changes we can for Julia 1.5 in those important packages (maybe more).

**Comment by staticfloat** [comment]
You can try using this script: https://github.com/JuliaPackaging/Yggdrasil/blob/master/recursively_regenerate_jlls.jl

Run that with the name of the package you want to regenerate JLLs for, and it will recursively find all dependencies, and if you give it leave to do so, it will open PRs for all of those dependencies, causing them to get regenerated.

**Comment by PallHaraldsson** [comment]
I've already made 38+ PRs automatically this way (more in the pipeline), for Gtk, Tk for good measure, and for QML, partially there, it's simple enough when it works, only for 1 of 2 root JLLs:

```
$ git clone https://github.com/JuliaPackaging/Yggdrasil

$ ./recursively_regenerate_jlls.jl Mesa_jll
[..]

[this one worked, then, not sure if it failed since I ran on Xorg_libxcb_jll previously]

$ ./recursively_regenerate_jlls.jl jlqml_jll
[ Info: Parsing /home/pharaldsson_sym/Yggdrasil/Yggdrasil/J/jlqml/build_tarballs.jl
[ Info: Parsing /home/pharaldsson_sym/Yggdrasil/Yggdrasil/L/libcxxwrap_julia/build_tarballs.jl
[ Info: Parsing /home/pharaldsson_sym/Yggdrasil/Yggdrasil/J/Julia/build_tarballs.jl
[ Info: Parsing /home/pharaldsson_sym/Yggdrasil/Yggdrasil/Z/Zlib/build_tarballs.jl
[ Info: Parsing /home/pharaldsson_sym/Yggdrasil/Yggdrasil/Q/Qt/build_tarballs.jl
ERROR: LoadError: Expected end of input
Line: 1
Around: ...5.15.0"} {"dependencies":[{"na...
                    ^

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] _error(::String, ::JSON.Parser.MemoryParserState) at /home/pharaldsson_sym/.julia/packages/JSON/d89fA/src/Parser.jl:142
 [3] parse(::String; dicttype::Type{T} where T, inttype::Type{Int64}, allownan::Bool, null::Nothing) at /home/pharaldsson_sym/.julia/packages/JSON/d89fA/src/Parser.jl:466
 [4] parse(::String) at /home/pharaldsson_sym/.julia/packages/JSON/d89fA/src/Parser.jl:461
 [5] recursively_collect_dependencies(::String, ::Set{String}) at /home/pharaldsson_sym/Yggdrasil/Yggdrasil/recursively_regenerate_jlls.jl:24
 [6] recursively_collect_dependencies(::String, ::Set{String}) at /home/pharaldsson_sym/Yggdrasil/Yggdrasil/recursively_regenerate_jlls.jl:32
 [7] recursively_collect_dependencies(::String) at /home/pharaldsson_sym/Yggdrasil/Yggdrasil/recursively_regenerate_jlls.jl:22
 [8] top-level scope at /home/pharaldsson_sym/Yggdrasil/Yggdrasil/recursively_regenerate_jlls.jl:107
in expression starting at /home/pharaldsson_sym/Yggdrasil/Yggdrasil/recursively_regenerate_jlls.jl:107
```

**Comment by PallHaraldsson** [comment]
I'm a bit impatient to see how the lot of these PRs go (now I see "Merging is blocked"). I now have "121 Open" PRs, my record... and it seems a bit over half are for this, I suspect it will be single-largest startup improvement to Gtk etc. and thus time-to-first-plot.

@timholy All of the PRs for Gtk (and Tk and Pango) should be in, not merged, but only partially for QML. I suspect a non-automated step is needed at Gtk.jl to enable the JLLs after they've geen regenerated from the PRs.

**Comment by vchuravy** [comment]
We need an auto-merge for rebuilds this large... I started with the manual merges, good to see that the cache is very effective.

**Comment by giordano** [comment]
> good to see that the cache is very effective.

If the git message contains `[skip build]` we don't build at all and only updates the wrappers 😉

**Comment by PallHaraldsson** [comment]
Hi, @staticfloat I did as you pointed out (without any arguments) and see the 70 PRs merged, but not sure if effective. I'm not sure if the pipeline is longer, and what I'm then waiting for, but at least I see no change at:

https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/blob/master/src/Xorg_libxcb_jll.jl

and I assume none of the JLLs. Is there something more to do? The PRs seemed all "dummy" PRs just to regenerate. Were they supposed to be look differently?

**Comment by giordano** [comment]
We have a [huge build queue](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build?definitionId=1&_a=summary) right now because most pull requests where merged without squashing, so the merge commit triggered the CI job, but that doesn't have the `[skip build]` text and thus we're unfortunately rebuilding all packages

**Comment by PallHaraldsson** [comment]
Thanks,

It seems I just need to be patient, with this multi-staged.

I do see failed: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=5422&view=results

And (while I'm less concerned about Tk working faster): https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=5420&view=results

**Comment by PallHaraldsson** [comment]
>most pull requests where merged without squashing, so the merge commit triggered the CI job, but that doesn't have the [skip build]

Since I don't actually need building, this is good to know, or how I would apply it (next time around, if that happens), with the script (maybe not possible).

**Comment by giordano** [comment]
Out of curiosity, which plotting package use any of `Gtk_jll` or `Qt_jll`?

**Comment by PallHaraldsson** [comment]
https://juliahub.com/ui/Packages/Gtk/Vjnq0/1.1.4?t=2
https://juliahub.com/ui/Packages/GTK3_jll/D35Um/3.24.11+2?t=2

juliahub is good to see this (usually, broken now for QML..., I've reported that), but actually only 2-3:

>[..] InspectDR
>    Immerse ("Currently, Immerse supports Gadfly")
>    Minesweeper
>    ProfileView
>    Winston
>Indirect Dependents (8)
>    EasyPlotting

I actually thought there were more (e.g. GR.jl), as I recall seeing Gtk info messages, but I guess GR uses Gtk through other means. I was looking into Winston, and it sparked me to look into slow-start again.

**Comment by giordano** [comment]
I'm not sure anyone would call `Gtk.jl` would call a "plotting" package

**Comment by PallHaraldsson** [comment]
```
julia> @time using Gtk
 17.631630 seconds (9.77 M allocations: 548.242 MiB, 2.01% gc time)
```
Disappointingly my change would take only about 1.3 sec off that (potentially better with new 1.6 functionality, and then maybe a new PR needed).

**Comment by PallHaraldsson** [comment]
I'm not saying it is, but Gtk is a dependency of some plotting packages, so to the user it "is". Also good to help Gtk independently.

**Comment by giordano** [comment]
> Disappointingly my change would take only about 1.3 sec off that

I'm still not sure why you expect large speedups by lowering the optimisation level, I've always seen very modest improvements (and I believe I repeated this quite a few times).

> but Gtk is a dependency of some plotting packages, so to the user it "is".

For example which one?  I don't know any

**Comment by PallHaraldsson** [comment]
Because of a problem at eu-central.pkg.julialang.org (reported; or my connection) I can't cant' add InspectDR, but it wouldn't load faster than its dependency. Maybe you can try it and tell me how fast it loads?

Also for:
```
(@v1.6) pkg> add Winston#master   # I do have it already at master, I guess it may be trying to download to know about potential new version, or knows about updated dependencies?:
[..]
HTTP request sent, awaiting response...
```

**Comment by PallHaraldsson** [comment]
>I'm still not sure why you expect large speedups by lowering the optimisation level

Ok, maybe 2 sec. isn't large, but that's what I see with `-O0`, still it's something. For any one JLL it's smaller, but those add up. If parallel JLL loading were allowed (I've been thinking about that, but hard to do in a non-breaking way, at least not yet done), the picture would be different, but with the many JLLs loaded, by one (even plotting, see 3+ in the comment I mentioned in the comment you immediately responded too) package (and its dependencies) you would get a the larger speedup.

**Comment by staticfloat** [comment]
This is helpful, thanks Pall.  I do think that the 1.6 changes will be impressive on top of this, and yes, we'll need to regenerate everything in the future as well.

Just so you know, if you want to test things out locally without having to bother with Yggdrasil and General and whatnot, you can use the same `https://github.com/JuliaPackaging/Yggdrasil/blob/master/recursively_regenerate_jlls.jl` script to do the regeneration locally.  It will take a little bit (because it downloads _all_ artifacts, not just the ones for the current platform) but doing that, combined with `dev`'ing out all those packages in some local environment, is how I have been testing my timings for the upcoming 1.6 changes.

**Comment by PallHaraldsson** [comment]
Some JLLs, at least Glib_jll.jl have been generated recently, presumably because I triggered it. But not all, some are failing e.g.

https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=5453&view=results

**Comment by barche** [comment]
> this latter one has three JSONs generated.

Yes, Qt has multiple build_tarballs to enable the building of FrameworkProducts on Mac and also to differentiate between GCC versions depending on the platform. Probably the jll rebuild script needs a patch similar to this one:

https://github.com/JuliaPackaging/Yggdrasil/pull/894/files

**Comment by PallHaraldsson** [comment]
Debugging Qt/build_tarballs.jl I ran it (with no arguments, not what the script here does to invoke it), it did some huge downloads, then I forgot about it, now 5+ hours killed it, was seeing lots of cc1plus processes, and makefile running. No wander my machine felt a bit sluggish.

**Comment by PallHaraldsson** [comment]
Now after updating all packages (hopefully all JLLs at latest version, while at least 1-2 failed to regenerate):
```julia> @time using Gtk
[..]
 11.004978 seconds (9.98 M allocations: 558.540 MiB, 2.77% gc time)

I'm not really sure if this is an improvement (or a large one) with my machine loaded before, and also, still:

$ julia -O0 -q
julia> @time using Gtk
[..]
  9.636287 seconds (9.98 M allocations: 558.539 MiB, 3.18% gc time)
````

Maybe someone, @timholy or other, can test a before and after. I guess I'm done with this experiment, at least for now.

**Comment by PallHaraldsson** [comment]
Anyway, I tried again in Julia 1.6, this time after downloading my "0 days old master":

```
julia> @time using Gtk
Gtk-Message: 09:13:58.729: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:13:58.730: Failed to load module "canberra-gtk-module"
  5.864934 seconds (6.82 M allocations: 446.869 MiB, 5.79% gc time)

$ julia -O0 -q
julia> @time using Gtk
  5.457358 seconds (6.82 M allocations: 446.868 MiB, 6.31% gc time)

vs. 1.4.0:
 13.544828 seconds (9.33 M allocations: 492.148 MiB, 1.93% gc time)

$ ~/julia-1.4.0/bin/julia -O0 -q
 11.616856 seconds (9.33 M allocations: 492.157 MiB, 2.31% gc time)
```

Most of the gain, is changes in Julia, but I'm not sure if my change enabled some of the gain.
