### ISSUE TITLE
Apple platforms gets filtered away on Julia 1.6 because the wrapper file is not found

### ISSUE THREAD

**Issue by KristofferC** [JuliaPackaging/BinaryBuilder.jl#913]
Using `[77ec8976] GTK3_jll v3.24.11+3` if I insert some debug statement here (to see what gets filtered away):

https://github.com/JuliaBinaryWrappers/GTK3_jll.jl/blob/93dac42b7362ed4c5ae8643fa81ae4aef8d4d668/src/GTK3_jll.jl#L41

I get:

```
...
f = "/Users/kristoffercarlsson/.julia/packages/GTK3_jll/T5lqK/src/wrappers/powerpc64le-linux-gnu.jl"
isfile(f) = true
f = "/Users/kristoffercarlsson/.julia/packages/GTK3_jll/T5lqK/src/wrappers/x86_64-apple-darwin.jl"
isfile(f) = false
f = "/Users/kristoffercarlsson/.julia/packages/GTK3_jll/T5lqK/src/wrappers/x86_64-linux-gnu.jl"
isfile(f) = true
f = "/Users/kristoffercarlsson/.julia/packages/GTK3_jll/T5lqK/src/wrappers/x86_64-linux-musl.jl"
isfile(f) = true
...
```

Note that it filters out the Apple one. The file is called `x86_64-apple-darwin14.jl` (note the missing 14)

**Comment by fingolfin** [comment]
I guess that explains why I can't use any JLLs in Julia 1.6dev right now ... :-(

**Comment by giordano** [comment]
Should be fixed by https://github.com/JuliaLang/Pkg.jl/pull/2042

**Comment by KristofferC** [comment]
Seems to work now.
