### ISSUE TITLE
New download stuff seems needlessly complicated and overly unreliable

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/BinaryBuilder.jl#928]
Seven jobs [of this build](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=6052&view=results) failed because the build steps got mismatch in the hash of the source tarball.  I didn't follow the details of recent changes of how the sources are fetched now, but this is too unreliable

**Comment by giordano** [comment]
New record: [9 failures out of 13 platforms](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=6053&view=results)

**Comment by giordano** [comment]
And [4 failures out of 9 in the next attempt](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=6054&view=results)...

**Comment by maleadt** [comment]
The problem with https://github.com/JuliaPackaging/Yggdrasil/pull/1723 and https://github.com/JuliaPackaging/Yggdrasil/pull/1724 is that Pkg's downloader used to not perform any request when the file already existed, whereas Downloads.jl does. The latter is probably more correct (e.g. to check if filesize matches and if not redownload), but it breaks the particular use case here where the links are not directly downloadable because they require a browser + login form:

```julia
# 1.5
julia> BinaryBuilder.BinaryBuilderBase.download_verify("https://developer.nvidia.com/compute/machine-learning/cudnn/secure/8.0.4/11.0_20200923/cudnn-11.0-windows-x64-v8.0.4.30.zip", "1b1438b828ce61888b7f1ed3ac506b32137425dd48aed8bc71abd5d4a7006143", "/home/tim/Downloads/cudnn-11.0-windows-x64-v8.0.4.30.zip")
true

#new
julia> BinaryBuilderBase.download_verify("https://developer.nvidia.com/compute/machine-learning/cudnn/secure/8.0.4/11.0_20200923/cudnn-11.0-windows-x64-v8.0.4.30.zip", "1b1438b828ce61888b7f1ed3ac506b32137425dd48aed8bc71abd5d4a7006143", "/home/tim/Downloads/cudnn-11.0-windows-x64-v8.0.4.30.zip")
ERROR: HTTP/2 403
```

I guess we can just fix that in BinaryBuilderBase though, by checking here whether the file already exists (since we have a hash to check against): https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/891ca2e97b3ff2c85f19ef492da09501d4d6bc6b/src/Sources.jl#L138

**Comment by fingolfin** [comment]
The way I dealt with this kind of issue in other projects in the past is to have an API which takes an URL, a filename (optional, extracted from the URL if missing; but useful to have for URLs where this is impossible); and a checksum. Then one can deal with files which are already there, and can also implement retries etc

**Comment by giordano** [comment]
Slightly related, but now we get also _lots_ of
```
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```
when unpacking the few tarballs that don't get hash mismatches...  It's all a bit frustrating :disappointed:

**Comment by ViralBShah** [comment]
Cc @StefanKarpinski I suppose.

**Comment by StefanKarpinski** [comment]
Since we aren't using the new download stuff in Pkg yet, I don't see how it can be at fault.

**Comment by giordano** [comment]
`Downloads.jl` is used to download the archives: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/426411b6f7816afbfb13f9e41b1e1327351dd5ed/src/ArchiveUtils.jl.

What confuses me is why we need to use "download" at all during the build job, since the tarballs are already cached on the disk.

**Comment by StefanKarpinski** [comment]
Beats me.

**Comment by giordano** [comment]
After some discussions on Slack, I'm quite convinced that there is nothing wrong in BinaryBuilder but there is a misconfiguration in Yggdrasil sot that the archive sources aren't fetched and each job needs to redownload, causing race conditions (archives get rewritten while other jobs are verifying or uncompressing them) and all sort of errors we're seeing these days.

**Comment by StefanKarpinski** [comment]
When looking into these hash mismatches, the uploaded incorrect tarballs were always truncated versions of what was expected, which could be happening if there are multiple tasks or processes downloading the same tarballs to the same location at the same time, leading to some processes apparently succeeding but then seeing the incomplete download started by another process.

**Comment by StefanKarpinski** [comment]
I'm not sure what the logic here is, but if Yggdrasil uses the presence/absence of a file to indicate whether it needs to download something or not and there can be more than one task/process downloading the same file at the same time then it _must_ do downloads by downloading to a temporary location first (ideally in the same directory as the final location, but with some random junk in the name to prevent collisions) and then moving the temp file to the final location. That way the file either doesn't exist or it does exist and is complete.
