### ISSUE TITLE
Wizard tries to fetch `git://` url using libcurl rather than libgit

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryBuilder.jl#935]
```
Please enter a URL (git repository or compressed archive) containing the source code to build:
> git://opencircuitdesign.com/magic

[23:14:21] curl: (1) Protocol "git" not supported or disabled in libcurl
Could not download git://opencircuitdesign.com/magic to /tmp/jl_Jkr5gI
```

**Comment by giordano** [comment]
More than the protocol, the problem is the trailing part of the URL: https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/4a0e367f0ceb49b8fce8b0bafa96cf9c7da98153/src/wizard/obtain_source.jl#L135 This autodetection isn't exactly bullet-proof, but checking the protocol here should be easy enough

**Comment by Moelf** [comment]
do we want to just check `|| startswith(url, git:)`? or we want to use something from LibGit2 to actually try to fetch a repo and try-catch on that.

**Comment by giordano** [comment]
> do we want to just check `|| startswith(url, "git:")`? or we want to use something from LibGit2 to actually try to fetch a repo and `try-catch` on that.

For the time being I'd check `startswith(url, "git://")`, since that's safe enough.  I'm a bit wary of try/catching errors, what if you actually pass a wrong URL?
