### ISSUE TITLE
MbedTLS dependency chain is accidentally picking up a system library rather than artifact libraries

### ISSUE THREAD

**Issue by musm** [JuliaPackaging/BinaryBuilder.jl#973]
Reported at:
https://github.com/JuliaIO/HDF5.jl/issues/751#issuecomment-738188799

Specifically:
https://github.com/JuliaIO/HDF5.jl/issues/751#issuecomment-738188799

For some reason BB is accidentally resolving to system library instead of  artifact libraries, leading to 
```
/nix/store/7xkbxjxaryrz8ka1padvgh61ljfn85cr-mbedtls-2.16.3/lib/libmbedx509.so.0: undefined symbol: mbedtls_mutex_unlock
```

**Comment by giordano** [comment]
This isn't a BinaryBuilder issue.  There is nothing we can do
