### ISSUE TITLE
issues with calling build_tarballs.jl  (no constructors have been defined for Platform)

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaPackaging/BinaryBuilder.jl#974]
I am try to run the following on Julia v1.5.1 with BinaryBuilder v0.2.6 and Linux (x86_64):

```bash
cd ~/src/Yggdrasil/H/HDF5 
julia build_tarballs.jl --help
```
As shown [here](
https://juliapackaging.github.io/BinaryBuilder.jl/dev/FAQ/#I-love-the-wizard,-but-now-I-want-to-break-free:-can-I-build-the-tarballs-without-it?).  However I get the following error:

```
ERROR: LoadError: MethodError: no constructors have been defined for Platform
Stacktrace:
 [1] top-level scope at /home/abarth/src/Yggdrasil/H/HDF5/build_tarballs.jl:93
 [2] include(::Function, ::Module, ::String) at ./Base.jl:380
 [3] include(::Module, ::String) at ./Base.jl:368
 [4] exec_options(::Base.JLOptions) at ./client.jl:296
 [5] _start() at ./client.jl:506
in expression starting at /home/abarth/src/Yggdrasil/H/HDF5/build_tarballs.jl:93
```

Any ideas how to test the build of a specific platform would be greatly appreciated.

**Comment by Alexander-Barth** [comment]
OK, I think I need to use BinaryBuilder#master and Julia 1.6-dev to compile HDF5.

**Comment by giordano** [comment]
Yes, Yggdrasil uses `BinaryBuilder#master` (and `BinaryBuilderBase#master`), which requires a reasonably recent version of Julia from `master` because we need some features available only there.

Answering your original question, you could locally modify to have `platform = Platform[]` and then run the script with
```
julia build_tarballs.jl --verbose --debug <triplet>
```

**Comment by Alexander-Barth** [comment]
Good to know. Thanks a lot @giordano !
