### ISSUE TITLE
Disable the wiki

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/BinaryBuilder.jl#978]
I think the BB wiki is quite old. Should we disable it? @ararslan It seems like you might have set it up, but most of the things seem to have been accomplished and we are now using GH issues to track these things.

**Comment by ararslan** [comment]
Huh, I don't recall setting it up (that's not to say I didn't though). I can disable it if desired.

**Comment by ViralBShah** [comment]
Done! Mostly because it was out of date. Can always bring it back.
