### ISSUE TITLE
Add test for sandbox capabilities

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/BinaryBuilder.jl#98]
Rather than just failing in the middle of launching `sandbox`, we should have a test that checks for all necessary capabilities.  Example:

```
[17:31:27] Child Process PID is -1
[17:31:27] At line 56, ABORTED (No such file or directory)!
```

Should instead throw a warning upon first run of a `UserNSRunner` that complains about inability to run.

**Comment by bicycle1885** [comment]
Hi, I see this error when running `BinaryBuilder.run_wizard()` on Linux and cannot finish building. Is there any way to avoid the problem? I tried to build zlib and libxml2 but both failed with the same error.

**Comment by staticfloat** [comment]
Please open a new issue with the exact error you're seeing, as well as the kernel version of Linux you're using.  :)

**Comment by staticfloat** [comment]
With https://github.com/JuliaPackaging/BinaryBuilder.jl/commit/e879ecf3377e34662ef041f18753d37501a5c63a, this is now automatically seen as a problem with unprivileged containers, and privileged containers will automatically be used.
