### ISSUE TITLE
Redistribute compiled sandbox binary

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/BinaryBuilder.jl#99]
Don't compile `sandbox.c` on user's machines; redistribute a compiled version instead.

**Comment by Keno** [comment]
We need to build it into the rootfs as /sandbox anyway for the qemu stuff to work, so we can re-use that.

**Comment by staticfloat** [comment]
@Keno just to be sure I'm understanding here, you're suggesting I move `sandbox.c` out of this repository and instead build it as a part of the base build image, storing it as `/sandbox`?

**Comment by Keno** [comment]
I feel like it might be nice for the sandbox.c to continue to live in this repo, but yes, I'm suggesting putting it into the base build image as `/sandbox`.

**Comment by Keno** [comment]
I believe this is done. Re-open if not @staticfloat
